In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras

In [2]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()


In [3]:
x_train2 = x_train.reshape(len(x_train), 28 * 28)
df1 = pd.DataFrame(x_train2)


In [4]:
df1

0    1    2    3    4    5    6    7    8    9    ...  774  775  776  \
0        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
2        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
3        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
4        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
59995    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59996    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59997    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59998    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59999    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   

       777  778  779  780  781  782  783  
0        0    0    0    0    0    0    0  
1        0    0    0    0    0    0    0  
2        0    0    0    0    0    0    0  
3        0    0    0    0    0    0    0  
4        0    0    0    0    0    0    0  
...    ...  ...  ...  ...  ...  ...  ...  
59995    0    0    0    0    0    0    0  
59996    0    0    0    0    0    0    0  
59997    0    0    0    0    0    0    0  
59998    0    0    0    0    0    0    0  
59999    0    0    0    0    0    0    0  

[60000 rows x 784 columns]

In [5]:
df1_target = pd.DataFrame(y_train)

In [6]:
df1_target

0
0      5
1      0
2      4
3      1
4      9
...   ..
59995  8
59996  3
59997  5
59998  6
59999  8

[60000 rows x 1 columns]

In [7]:
df1['target'] = df1_target[0]
df1.head()

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  782  \
0  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
1  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
2  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
3  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
4  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   

   783  target  
0    0       5  
1    0       0  
2    0       4  
3    0       1  
4    0       9  

[5 rows x 785 columns]

# We did the merging for X_train and y_train, now lets do it for X_test and y_test

In [8]:
x_test2 = x_test.reshape(len(x_test), 28 * 28)
df2 = pd.DataFrame(x_test2)
df2_target = pd.DataFrame(y_test)
df2['target'] = df2_target[0]
df2.head()

##MERGING HAS BEEN DONE. WE NOW HAVE DF1 and DF2

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  782  \
0  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
1  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
2  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
3  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
4  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   

   783  target  
0    0       7  
1    0       2  
2    0       1  
3    0       0  
4    0       4  

[5 rows x 785 columns]

In [9]:
##NOW GETTING THE DF IN WHICH WE WILL MERGE ALL OF THESE
df3 = pd.concat([df1, df2], ignore_index = True)
df3

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  \
0      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
1      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
2      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
3      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
4      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
...   .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
69995  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69996  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69997  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69998  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69999  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   

       782  783  target  
0        0    0       5  
1        0    0       0  
2        0    0       4  
3        0    0       1  
4        0    0       9  
...    ...  ...     ...  
69995    0    0       2  
69996    0    0       3  
69997    0    0       4  
69998    0    0       5  
69999    0    0       6  

[70000 rows x 785 columns]

In [10]:
# y = df3['target']
# y = pd.DataFrame(y)
# y.head()
df_train = df3.sample(frac=0.67,random_state=7)
df_test = df3.drop(df_train.index)
df_train

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  \
7653   0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
66274  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
9119   0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
10760  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
43166  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
...   .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
19934  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
42962  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
54026  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
4057   0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
41425  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   

       782  783  target  
7653     0    0       2  
66274    0    0       2  
9119     0    0       9  
10760    0    0       3  
43166    0    0       6  
...    ...  ...     ...  
19934    0    0       9  
42962    0    0       3  
54026    0    0       9  
4057     0    0       5  
41425    0    0       0  

[46900 rows x 785 columns]

In [11]:
y_train = df_train['target']
y_train = pd.DataFrame(y_train)
y_train.head()
# df_train = df_train.drop('target', axis = 1, inplace = True)
# df_train.head()

target
7653        2
66274       2
9119        9
10760       3
43166       6

In [12]:
df_train = df_train.drop('target', axis=1)


In [13]:
df_train.head()
df_test

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  \
0      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
4      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
5      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
10     0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
11     0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
...   .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
69990  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69992  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69993  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69997  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69998  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   

       782  783  target  
0        0    0       5  
4        0    0       9  
5        0    0       2  
10       0    0       3  
11       0    0       5  
...    ...  ...     ...  
69990    0    0       7  
69992    0    0       9  
69993    0    0       0  
69997    0    0       4  
69998    0    0       5  

[23100 rows x 785 columns]

In [14]:
y_test = df_test['target']
y_test = pd.DataFrame(y_test)
y_test.head()

target
0        5
4        9
5        2
10       3
11       5

In [15]:
df_test = df_test.drop('target', axis=1)


In [16]:
df_test.head()

0    1    2    3    4    5    6    7    8    9    ...  774  775  776  777  \
0     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
4     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
5     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
10    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
11    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   

    778  779  780  781  782  783  
0     0    0    0    0    0    0  
4     0    0    0    0    0    0  
5     0    0    0    0    0    0  
10    0    0    0    0    0    0  
11    0    0    0    0    0    0  

[5 rows x 784 columns]

# Converting these into NumPy arrays for use in the ANN model

In [17]:
x_train = df_train.to_numpy()
x_train
x_test = df_test.to_numpy()
y_train = y_train.to_numpy()
y_test = y_test.to_numpy()

# Performing the required pre-processing

In [18]:
x_train = x_train/255
x_test = x_test/255

In [19]:
#x_train[0]

In [20]:
X_trainf = x_train.reshape(len(x_train), 28 * 28)
#we choose to flatten the data in order to make the first input layer of the neural network have 784 values, since we currently have values stored in 28*28 form

In [21]:
X_testf = x_test.reshape(len(x_test), 28*28)

# MODEL 1 -- 150 neurons, 2 layers, sigmoid

In [22]:
model1 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'sigmoid'),
    keras.layers.Dense(10, activation = 'softmax')
])

model1.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model1.fit(X_trainf, y_train, epochs = 5)



Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.5870 - accuracy: 0.8533
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.2137 - accuracy: 0.9381
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1561 - accuracy: 0.9542
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1229 - accuracy: 0.9646
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0991 - accuracy: 0.9711


In [23]:
model1.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 917us/step - loss: 0.1183 - accuracy: 0.9632


[0.11827634274959564, 0.963203489780426]

In [24]:
y_predict = model1.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 827us/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2262,    0,    9,    1,    3,   16,   14,    3,   13,    2],
       [   0, 2575,    7,    6,    2,    6,    0,    4,   34,    9],
       [  14,    4, 2219,   15,   14,    1,    8,   22,   28,    3],
       [   5,    2,   22, 2160,    0,   34,    0,   10,   47,   17],
       [   1,    0,    3,    0, 2215,    2,   13,    1,    5,   37],
       [   7,    1,    5,   18,    6, 1986,   10,    2,   12,   13],
       [  19,    3,    5,    0,    6,   26, 2204,    0,   10,    0],
       [   6,    6,   15,   10,   13,    2,    0, 2291,    5,   20],
       [   7,    9,    3,   14,   12,   21,   12,    3, 2159,    8],
       [   2,    5,    0,   14,   48,   11,    1,   14,    9, 2179]])>

# MODEL 2 -- 100 Neurons, 3 Hidden Layers

In [25]:
model2 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'sigmoid'),
    keras.layers.Dense(20, activation = 'sigmoid'),
    keras.layers.Dense(10, activation = 'softmax')
])

model2.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model2.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 1.1162 - accuracy: 0.6866
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.3638 - accuracy: 0.9109
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.2266 - accuracy: 0.9398
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1698 - accuracy: 0.9549
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1368 - accuracy: 0.9628


In [26]:
model2.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1571 - accuracy: 0.9545


[0.15708571672439575, 0.9545454382896423]

In [27]:
y_predict = model2.predict(X_testf)

722/722 [==============================] - 1s 915us/step


In [28]:
y_predict[0]

array([1.0327233e-03, 2.7302105e-03, 1.8704368e-04, 6.5667398e-02,
       8.6009568e-06, 9.2691857e-01, 1.5037769e-04, 1.5493472e-04,
       2.5767426e-03, 5.7337695e-04], dtype=float32)

In [29]:
np.argmax(y_predict[0]) #gives the maximum value out of the given ones

5

In [30]:
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array

In [31]:
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices


In [32]:
cm #this is the confusion matrix, we are supposed to do this for all 15 of the models. Preferable if we beautify this a bit using matPlotLib, or seaborn if permitted by sir

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2255,    0,    7,    6,    1,   21,   13,    3,   10,    7],
       [   0, 2591,   11,    4,    3,    5,    2,    4,   20,    3],
       [   5,    5, 2220,   21,   13,    2,   14,   20,   28,    0],
       [   7,    2,   26, 2179,    0,   24,    0,   20,   34,    5],
       [   1,    6,    7,    0, 2141,    0,   23,    3,   22,   74],
       [   3,    9,   10,   49,    2, 1945,    9,    1,   16,   16],
       [  11,    7,   15,    0,    3,   20, 2207,    1,    7,    2],
       [   2,    4,   19,   11,    6,    1,    0, 2287,    3,   35],
       [   3,   21,   21,   50,    9,   30,    3,    5, 2102,    4],
       [   2,    5,    2,   42,   55,   14,    2,   32,    6, 2123]])>

# MODEL 3 -- 150 Neurons, 2 Hidden Layers, ReLU

In [33]:
model3 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model3.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model3.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.2928 - accuracy: 0.9150
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1307 - accuracy: 0.9605
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0922 - accuracy: 0.9716
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0713 - accuracy: 0.9777
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0556 - accuracy: 0.9822


In [34]:
model3.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1086 - accuracy: 0.9701


[0.1085798516869545, 0.9700865745544434]

In [35]:
y_predict = model3.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 880us/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2302,    0,    0,    1,    0,    8,    2,    5,    1,    4],
       [   0, 2613,    6,    3,    1,    1,    5,    8,    4,    2],
       [  18,    5, 2252,   11,    8,    3,    2,   26,    2,    1],
       [   7,    3,   14, 2236,    0,   15,    0,   10,    4,    8],
       [   4,    1,    2,    3, 2218,    1,    7,    3,    0,   38],
       [   6,    1,    3,   27,    2, 2000,   11,    2,    1,    7],
       [  32,    2,    1,    1,    1,   20, 2212,    1,    3,    0],
       [   4,    3,    9,    9,    5,    1,    0, 2327,    2,    8],
       [  10,   18,    9,   49,   10,   47,   14,    7, 2055,   29],
       [   4,    2,    1,   21,   19,   15,    0,   23,    4, 2194]])>

In [36]:
model4 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'tanh'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model4.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model4.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.3028 - accuracy: 0.9132
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1445 - accuracy: 0.9575
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1018 - accuracy: 0.9700
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0762 - accuracy: 0.9767
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0581 - accuracy: 0.9822


In [37]:
model4.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.0967 - accuracy: 0.9711


[0.09669938683509827, 0.9711255431175232]

In [38]:
y_predict = model4.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 902us/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2286,    0,    4,    2,    1,    5,   12,    0,    5,    8],
       [   0, 2606,    4,    5,    3,    2,    4,    4,   10,    5],
       [  17,   11, 2251,   13,    9,    1,    5,    9,    9,    3],
       [  10,    1,   16, 2202,    0,   28,    2,   11,   17,   10],
       [   1,    1,   10,    1, 2199,    1,    9,    7,    1,   47],
       [  10,    2,    4,   18,    4, 1987,   17,    0,    5,   13],
       [  12,    0,    1,    0,    5,    6, 2245,    0,    4,    0],
       [   2,    5,   15,    6,    8,    2,    0, 2291,    6,   33],
       [  12,    5,   11,   17,    5,   18,   22,    5, 2140,   13],
       [   4,    1,    0,    8,   24,    8,    0,    9,    3, 2226]])>

In [39]:
model5 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'relu'),
    keras.layers.Dense(20, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model5.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model5.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.3809 - accuracy: 0.8896
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1680 - accuracy: 0.9511
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1233 - accuracy: 0.9640
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1000 - accuracy: 0.9691
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0832 - accuracy: 0.9748


In [40]:
model5.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1415 - accuracy: 0.9581


[0.1414782553911209, 0.9580952525138855]

In [41]:
y_predict = model5.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 932us/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2284,    1,    7,    1,    3,    0,   24,    2,    1,    0],
       [   1, 2608,    8,    5,    3,    1,    3,    6,    7,    1],
       [  13,    7, 2242,    3,   11,    0,   11,   29,   12,    0],
       [   7,    5,   52, 2137,    3,   23,    3,   22,   39,    6],
       [   2,    0,    3,    1, 2241,    1,   18,    3,    2,    6],
       [  22,    2,    5,   28,    5, 1927,   42,    4,   13,   12],
       [  13,    3,    5,    0,    2,    3, 2243,    2,    2,    0],
       [  11,    8,   13,    1,    5,    0,    1, 2318,    1,   10],
       [  17,   16,    8,   12,   12,   16,   29,    8, 2126,    4],
       [  11,    7,    0,   16,  167,   11,    1,   49,   15, 2006]])>

In [42]:
model6 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'tanh'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'tanh'),
    keras.layers.Dense(20, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model6.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model6.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.3860 - accuracy: 0.8973
Epoch 2/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1606 - accuracy: 0.9532
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1163 - accuracy: 0.9652
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0921 - accuracy: 0.9714
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0757 - accuracy: 0.9773


In [43]:
model6.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1134 - accuracy: 0.9657


[0.1134166494011879, 0.9656710028648376]

In [44]:
y_predict = model6.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 982us/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2276,    0,    8,    2,    7,    5,    9,    1,   13,    2],
       [   0, 2607,   10,    1,    2,    4,    4,    3,    7,    5],
       [   9,    3, 2235,   19,   15,    0,    9,   13,   23,    2],
       [   4,    5,   21, 2174,    0,   26,    0,   16,   44,    7],
       [   2,    3,    8,    1, 2204,    2,   12,    7,    2,   36],
       [   3,    6,    4,   31,    3, 1966,   22,    1,   15,    9],
       [  13,    3,    0,    0,    4,   11, 2231,    1,   10,    0],
       [   1,    8,   15,    7,    6,    0,    0, 2307,    4,   20],
       [   4,   15,    4,   12,    8,   11,   25,    7, 2154,    8],
       [   4,    5,    0,   14,   40,   21,    1,   26,   19, 2153]])>

In [45]:
model7 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'relu'),
    keras.layers.Dense(20, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model7.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model7.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.4902 - accuracy: 0.8719
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1861 - accuracy: 0.9452
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1386 - accuracy: 0.9588
Epoch 4/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1113 - accuracy: 0.9671
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0942 - accuracy: 0.9721


In [46]:
model7.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1260 - accuracy: 0.9625


[0.12597821652889252, 0.9625108242034912]

In [47]:
y_predict = model1.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 955us/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2262,    0,    9,    1,    3,   16,   14,    3,   13,    2],
       [   0, 2575,    7,    6,    2,    6,    0,    4,   34,    9],
       [  14,    4, 2219,   15,   14,    1,    8,   22,   28,    3],
       [   5,    2,   22, 2160,    0,   34,    0,   10,   47,   17],
       [   1,    0,    3,    0, 2215,    2,   13,    1,    5,   37],
       [   7,    1,    5,   18,    6, 1986,   10,    2,   12,   13],
       [  19,    3,    5,    0,    6,   26, 2204,    0,   10,    0],
       [   6,    6,   15,   10,   13,    2,    0, 2291,    5,   20],
       [   7,    9,    3,   14,   12,   21,   12,    3, 2159,    8],
       [   2,    5,    0,   14,   48,   11,    1,   14,    9, 2179]])>

In [48]:
model8 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model8.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model8.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.4190 - accuracy: 0.8860
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1918 - accuracy: 0.9425
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1393 - accuracy: 0.9589
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1086 - accuracy: 0.9673
Epoch 5/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.0873 - accuracy: 0.9739


In [49]:
model8.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1173 - accuracy: 0.9639


[0.11731552332639694, 0.9638528227806091]

In [50]:
y_predict = model8.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 940us/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2275,    0,    4,    4,    1,   17,    7,    1,    8,    6],
       [   0, 2592,    7,    8,    2,   10,    2,    4,   15,    3],
       [   8,    4, 2251,   24,    8,    3,    5,   10,   14,    1],
       [   2,    0,   16, 2199,    1,   44,    0,   11,   17,    7],
       [   1,    1,    8,    3, 2189,    2,   13,    6,    4,   50],
       [   4,    1,    6,   23,    2, 2014,    4,    0,    3,    3],
       [  14,    3,    7,    0,    4,   37, 2200,    0,    7,    1],
       [   4,    6,   14,   18,    3,    7,    0, 2297,    5,   14],
       [   6,   18,    6,   42,    3,   65,    9,    2, 2089,    8],
       [   3,    7,    1,   29,   20,   37,    1,   18,    8, 2159]])>

In [51]:
model9 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model9.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model9.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.4033 - accuracy: 0.8883
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1884 - accuracy: 0.9434
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1351 - accuracy: 0.9594
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1047 - accuracy: 0.9686
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0830 - accuracy: 0.9746


In [52]:
model9.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1164 - accuracy: 0.9638


[0.1164446547627449, 0.9637662172317505]

In [53]:
y_predict = model9.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2298,    0,    3,    4,    1,    1,    8,    2,    4,    2],
       [   0, 2595,   10,   15,    2,    1,    0,    3,   14,    3],
       [  15,    3, 2244,   29,    4,    0,    2,   13,   16,    2],
       [   4,    1,   13, 2239,    1,    4,    1,   10,   17,    7],
       [   4,    1,   15,    3, 2178,    1,   13,    7,   10,   45],
       [  16,    1,   11,   93,    2, 1889,   16,    2,   15,   15],
       [  23,    5,    6,    0,    2,    5, 2222,    2,    8,    0],
       [   7,    6,   12,   12,    3,    0,    0, 2305,    5,   18],
       [  10,   14,   10,   51,    5,   11,   10,    4, 2126,    7],
       [   6,    8,    2,   31,   38,    4,    1,   15,   11, 2167]])>

In [54]:
model10 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model10.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model10.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.2629 - accuracy: 0.9239
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1084 - accuracy: 0.9673
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0774 - accuracy: 0.9759
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0582 - accuracy: 0.9815
Epoch 5/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.0436 - accuracy: 0.9860


In [55]:
model10.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.0957 - accuracy: 0.9721


[0.09567327052354813, 0.9720779061317444]

In [56]:
y_predict = model10.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2299,    0,    0,    0,    2,    5,    4,    1,   10,    2],
       [   0, 2611,    2,    0,    8,    1,    5,    3,    8,    5],
       [  14,   10, 2240,    7,    7,    2,    5,   19,   21,    3],
       [   5,    4,   15, 2201,    2,   20,    0,   13,   27,   10],
       [   4,    0,    6,    0, 2226,    1,   11,    1,    3,   25],
       [   2,    2,    3,   16,    6, 2011,    5,    0,    6,    9],
       [  25,    2,    1,    0,    6,   25, 2206,    0,    7,    1],
       [   3,    9,   11,    2,   14,    2,    0, 2290,    7,   30],
       [   4,   10,    0,   11,    6,   23,    9,    4, 2168,   13],
       [   3,    2,    0,   12,   41,    6,    1,    8,    7, 2203]])>

In [57]:
model11 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'sigmoid'),
    keras.layers.Dense(40, activation = 'sigmoid'),
    keras.layers.Dense(10, activation = 'softmax')
])

model11.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model11.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.8849 - accuracy: 0.7629
Epoch 2/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.2638 - accuracy: 0.9291
Epoch 3/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1799 - accuracy: 0.9488
Epoch 4/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1407 - accuracy: 0.9597
Epoch 5/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1176 - accuracy: 0.9652


In [58]:
model11.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1350 - accuracy: 0.9609


[0.13504554331302643, 0.9608657956123352]

In [59]:
y_predict = model11.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2257,    0,    8,    3,    7,   12,   22,    2,    6,    6],
       [   0, 2594,    9,   10,    1,    5,    3,    6,   12,    3],
       [  13,    5, 2234,   13,    7,    1,   11,   19,   24,    1],
       [   2,    2,   28, 2176,    0,   28,    1,   13,   37,   10],
       [   0,    2,    5,    1, 2175,    1,   22,    4,    9,   58],
       [   8,    1,   10,   25,    3, 1967,   15,    1,   20,   10],
       [  11,    2,    4,    0,    5,   17, 2231,    0,    3,    0],
       [   6,    9,   28,    7,    6,    2,    0, 2270,    3,   37],
       [   1,   19,    7,   23,    5,   25,   17,    2, 2137,   12],
       [   4,    7,    2,   15,   43,   17,    1,   14,   25, 2155]])>

In [60]:
model12 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'relu'),
    keras.layers.Dense(40, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model12.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model12.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.3239 - accuracy: 0.9058
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1437 - accuracy: 0.9565
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1062 - accuracy: 0.9679
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0852 - accuracy: 0.9734
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0699 - accuracy: 0.9775


In [61]:
model12.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1045 - accuracy: 0.9687


[0.10449087619781494, 0.9686580300331116]

In [62]:
y_predict = model12.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2293,    0,    2,    0,    2,    6,    9,    1,    7,    3],
       [   0, 2597,    8,    1,    3,    2,    3,    5,   22,    2],
       [  18,    3, 2260,    7,    7,    2,    6,   14,    9,    2],
       [   8,    3,   27, 2131,    1,   45,    3,    9,   59,   11],
       [   6,    1,    4,    0, 2213,    0,    8,    2,    2,   41],
       [   4,    1,    4,   17,    3, 1986,   20,    1,   17,    7],
       [  16,    2,    6,    0,    5,    5, 2232,    0,    7,    0],
       [   1,    5,   18,    2,    6,    1,    0, 2299,   11,   25],
       [  14,    8,    6,    5,   10,   12,    7,    2, 2175,    9],
       [   4,    3,    1,    8,   35,   15,    1,   14,   12, 2190]])>

In [63]:
model13 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'tanh'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'tanh'),
    keras.layers.Dense(40, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model13.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model13.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.3181 - accuracy: 0.9104
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1411 - accuracy: 0.9577
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1019 - accuracy: 0.9695
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0783 - accuracy: 0.9761
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0621 - accuracy: 0.9806


In [64]:
model13.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 2ms/step - loss: 0.1017 - accuracy: 0.9687


[0.10174334049224854, 0.9687013030052185]

In [65]:
y_predict = model13.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2294,    0,    6,    1,    2,    2,    8,    4,    3,    3],
       [   0, 2621,    3,    2,    1,    2,    2,    3,    8,    1],
       [  15,   19, 2249,    9,    6,    1,   10,   11,    7,    1],
       [   3,    5,   22, 2202,    1,   18,    0,   15,   26,    5],
       [   1,    5,   11,    1, 2186,    1,   15,   14,    8,   35],
       [   7,    3,    4,   27,    1, 1973,   23,    2,   10,   10],
       [  15,    6,    4,    0,    5,    5, 2231,    0,    7,    0],
       [   3,    8,   19,    6,    1,    0,    0, 2315,    7,    9],
       [   7,   22,    9,   18,    3,   14,   10,    8, 2153,    4],
       [   5,    9,    1,   22,   33,   16,    3,   28,   13, 2153]])>

In [66]:
model14 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'relu'),
    keras.layers.Dense(40, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model14.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model14.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.4298 - accuracy: 0.8784
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1779 - accuracy: 0.9467
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1294 - accuracy: 0.9602
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1028 - accuracy: 0.9682
Epoch 5/5
1466/1466 [==============================] - 4s 3ms/step - loss: 0.0858 - accuracy: 0.9729


In [67]:
model14.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 2ms/step - loss: 0.1303 - accuracy: 0.9602


[0.1302613615989685, 0.9602164626121521]

In [68]:
y_predict = model14.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2301,    0,    6,    4,    0,    1,    8,    0,    2,    1],
       [   1, 2569,   16,   11,    6,    2,    7,    8,   17,    6],
       [  20,    2, 2262,   15,    7,    0,    7,    8,    4,    3],
       [  10,    1,   27, 2210,    1,   10,    2,   10,    8,   18],
       [   6,    0,   12,    1, 2193,    1,   17,    1,    2,   44],
       [  32,    2,    8,   38,    5, 1914,   25,    3,    6,   27],
       [  32,    0,    5,    0,    3,    3, 2227,    0,    3,    0],
       [  14,    4,   25,   15,   16,    1,    0, 2248,    4,   41],
       [  22,   10,   22,   38,   10,   13,   22,    1, 2058,   52],
       [  10,    3,    3,   13,   41,    5,    0,    8,    1, 2199]])>

In [69]:
model15 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model15.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model15.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 4s 2ms/step - loss: 0.4789 - accuracy: 0.8674
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.2023 - accuracy: 0.9396
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1513 - accuracy: 0.9550
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1214 - accuracy: 0.9637
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1009 - accuracy: 0.9695


In [70]:
model15.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 2ms/step - loss: 0.1272 - accuracy: 0.9608


[0.12715817987918854, 0.9607792496681213]

In [71]:
y_predict = model15.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2257,    0,    6,    3,    2,    7,   26,    1,   17,    4],
       [   0, 2602,    7,    5,    3,    1,    6,    5,   11,    3],
       [  12,    4, 2244,    8,   10,    3,   15,   17,   13,    2],
       [   7,    4,   28, 2142,    2,   30,    8,   18,   52,    6],
       [   0,    4,    6,    0, 2182,    1,   42,    2,    3,   37],
       [   6,    5,    6,   26,    6, 1942,   46,    1,    9,   13],
       [   8,    1,    3,    0,    2,    4, 2252,    0,    3,    0],
       [   3,    7,   16,    3,    8,    2,    0, 2303,    6,   20],
       [   6,   19,    6,   18,    5,   16,   49,    4, 2120,    5],
       [   4,    8,    2,   21,   53,    6,    3,   16,   20, 2150]])>