In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras

In [2]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()


In [3]:
x_train2 = x_train.reshape(len(x_train), 28 * 28)
df1 = pd.DataFrame(x_train2)


In [4]:
df1

0    1    2    3    4    5    6    7    8    9    ...  774  775  776  \
0        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
2        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
3        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
4        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
59995    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59996    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59997    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59998    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59999    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   

       777  778  779  780  781  782  783  
0        0    0    0    0    0    0    0  
1        0    0    0    0    0    0    0  
2        0    0    0    0    0    0    0  
3        0    0    0    0    0    0    0  
4        0    0    0    0    0    0    0  
...    ...  ...  ...  ...  ...  ...  ...  
59995    0    0    0    0    0    0    0  
59996    0    0    0    0    0    0    0  
59997    0    0    0    0    0    0    0  
59998    0    0    0    0    0    0    0  
59999    0    0    0    0    0    0    0  

[60000 rows x 784 columns]

In [5]:
df1_target = pd.DataFrame(y_train)

In [6]:
df1_target

0
0      5
1      0
2      4
3      1
4      9
...   ..
59995  8
59996  3
59997  5
59998  6
59999  8

[60000 rows x 1 columns]

In [7]:
df1['target'] = df1_target[0]
df1.head()

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  782  \
0  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
1  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
2  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
3  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
4  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   

   783  target  
0    0       5  
1    0       0  
2    0       4  
3    0       1  
4    0       9  

[5 rows x 785 columns]

# We did the merging for X_train and y_train, now lets do it for X_test and y_test

In [8]:
x_test2 = x_test.reshape(len(x_test), 28 * 28)
df2 = pd.DataFrame(x_test2)
df2_target = pd.DataFrame(y_test)
df2['target'] = df2_target[0]
df2.head()

##MERGING HAS BEEN DONE. WE NOW HAVE DF1 and DF2

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  782  \
0  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
1  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
2  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
3  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
4  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   

   783  target  
0    0       7  
1    0       2  
2    0       1  
3    0       0  
4    0       4  

[5 rows x 785 columns]

In [9]:
##NOW GETTING THE DF IN WHICH WE WILL MERGE ALL OF THESE
df3 = pd.concat([df1, df2], ignore_index = True)
df3

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  \
0      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
1      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
2      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
3      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
4      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
...   .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
69995  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69996  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69997  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69998  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69999  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   

       782  783  target  
0        0    0       5  
1        0    0       0  
2        0    0       4  
3        0    0       1  
4        0    0       9  
...    ...  ...     ...  
69995    0    0       2  
69996    0    0       3  
69997    0    0       4  
69998    0    0       5  
69999    0    0       6  

[70000 rows x 785 columns]

In [10]:
# y = df3['target']
# y = pd.DataFrame(y)
# y.head()
df_train = df3.sample(frac=0.67,random_state=8)
df_test = df3.drop(df_train.index)
df_train

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  \
3787   0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
57724  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
22576  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
53743  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
58755  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
...   .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
24327  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
55761  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
22908  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
42251  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
54348  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   

       782  783  target  
3787     0    0       9  
57724    0    0       4  
22576    0    0       9  
53743    0    0       8  
58755    0    0       6  
...    ...  ...     ...  
24327    0    0       4  
55761    0    0       8  
22908    0    0       6  
42251    0    0       3  
54348    0    0       6  

[46900 rows x 785 columns]

In [11]:
y_train = df_train['target']
y_train = pd.DataFrame(y_train)
y_train.head()
# df_train = df_train.drop('target', axis = 1, inplace = True)
# df_train.head()

target
3787        9
57724       4
22576       9
53743       8
58755       6

In [12]:
df_train = df_train.drop('target', axis=1)


In [13]:
df_train.head()
df_test

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  \
3      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
6      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
8      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
12     0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
13     0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
...   .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
69985  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69991  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69992  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69994  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69995  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   

       782  783  target  
3        0    0       1  
6        0    0       1  
8        0    0       1  
12       0    0       3  
13       0    0       6  
...    ...  ...     ...  
69985    0    0       2  
69991    0    0       8  
69992    0    0       9  
69994    0    0       1  
69995    0    0       2  

[23100 rows x 785 columns]

In [14]:
y_test = df_test['target']
y_test = pd.DataFrame(y_test)
y_test.head()

target
3        1
6        1
8        1
12       3
13       6

In [15]:
df_test = df_test.drop('target', axis=1)


In [16]:
df_test.head()

0    1    2    3    4    5    6    7    8    9    ...  774  775  776  777  \
3     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
6     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
8     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
12    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
13    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   

    778  779  780  781  782  783  
3     0    0    0    0    0    0  
6     0    0    0    0    0    0  
8     0    0    0    0    0    0  
12    0    0    0    0    0    0  
13    0    0    0    0    0    0  

[5 rows x 784 columns]

# Converting these into NumPy arrays for use in the ANN model

In [17]:
x_train = df_train.to_numpy()
x_train
x_test = df_test.to_numpy()
y_train = y_train.to_numpy()
y_test = y_test.to_numpy()

# Performing the required pre-processing

In [18]:
x_train = x_train/255
x_test = x_test/255

In [19]:
#x_train[0]

In [20]:
X_trainf = x_train.reshape(len(x_train), 28 * 28)
#we choose to flatten the data in order to make the first input layer of the neural network have 784 values, since we currently have values stored in 28*28 form

In [21]:
X_testf = x_test.reshape(len(x_test), 28*28)

# MODEL 1 -- 150 neurons, 2 layers, sigmoid

In [22]:
model1 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'sigmoid'),
    keras.layers.Dense(10, activation = 'softmax')
])

model1.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model1.fit(X_trainf, y_train, epochs = 5)



Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.5690 - accuracy: 0.8600
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.2084 - accuracy: 0.9393
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1519 - accuracy: 0.9550
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1183 - accuracy: 0.9647
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0948 - accuracy: 0.9724


In [23]:
model1.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 938us/step - loss: 0.1289 - accuracy: 0.9604


[0.1289404332637787, 0.9603896141052246]

In [24]:
y_predict = model1.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 828us/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2206,    0,    0,    3,    2,    4,    8,    0,   10,    5],
       [   1, 2549,    6,   17,    0,    4,    1,   11,   26,   10],
       [  10,    4, 2204,   41,   15,    3,    8,   28,   33,    3],
       [   1,    1,   10, 2225,    0,   15,    1,   22,   15,   11],
       [   3,    0,    6,    3, 2165,    2,    7,    5,    5,   69],
       [  12,    1,    3,   55,    7, 1964,    6,    3,   20,   15],
       [  20,    5,    1,    1,   14,   20, 2236,    2,   22,    0],
       [   5,    6,    9,    7,   20,    1,    1, 2301,    1,   19],
       [   8,    9,    2,   38,    3,   11,    9,    6, 2102,   26],
       [  10,    1,    0,   24,   23,    4,    0,   28,    8, 2233]])>

# MODEL 2 -- 100 Neurons, 3 Hidden Layers

In [25]:
model2 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'sigmoid'),
    keras.layers.Dense(20, activation = 'sigmoid'),
    keras.layers.Dense(10, activation = 'softmax')
])

model2.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model2.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 1.1605 - accuracy: 0.6883
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.3753 - accuracy: 0.9122
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.2316 - accuracy: 0.9403
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1772 - accuracy: 0.9533
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1458 - accuracy: 0.9599


In [26]:
model2.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1806 - accuracy: 0.9487


[0.18061915040016174, 0.9486579895019531]

In [27]:
y_predict = model2.predict(X_testf)

722/722 [==============================] - 1s 899us/step


In [28]:
y_predict[0]

array([6.3200999e-04, 9.9367148e-01, 2.7148605e-03, 3.9194074e-05,
       3.2150249e-06, 2.3001796e-05, 9.7261648e-07, 6.8616739e-04,
       2.1563331e-03, 7.2624542e-05], dtype=float32)

In [29]:
np.argmax(y_predict[0]) #gives the maximum value out of the given ones

1

In [30]:
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array

In [31]:
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices


In [32]:
cm #this is the confusion matrix, we are supposed to do this for all 15 of the models. Preferable if we beautify this a bit using matPlotLib, or seaborn if permitted by sir

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2172,    1,    5,    2,   19,   12,   10,    0,   12,    5],
       [   0, 2568,   14,    7,    0,    2,    1,    7,   23,    3],
       [  14,   13, 2194,   16,   20,    6,   18,   32,   35,    1],
       [   2,    3,   22, 2125,    1,   52,    8,   34,   47,    7],
       [   2,    4,    8,    2, 2167,    2,   13,   10,    5,   52],
       [  11,    1,   11,   86,    6, 1890,   29,    0,   39,   13],
       [   6,    4,   16,    1,   18,   21, 2235,    0,   20,    0],
       [   2,   10,   16,    2,   20,    1,    0, 2276,    9,   34],
       [   8,   24,    4,   17,    4,    8,   25,    8, 2103,   13],
       [  10,    5,    2,   20,   54,    4,    0,   30,   22, 2184]])>

# MODEL 3 -- 150 Neurons, 2 Hidden Layers, ReLU

In [33]:
model3 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model3.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model3.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.2890 - accuracy: 0.9143
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1226 - accuracy: 0.9631
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0885 - accuracy: 0.9730
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0681 - accuracy: 0.9784
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0538 - accuracy: 0.9829


In [34]:
model3.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1084 - accuracy: 0.9678


[0.10837101936340332, 0.9678354859352112]

In [35]:
y_predict = model3.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 941us/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2213,    0,    2,    2,    0,    5,   12,    0,    2,    2],
       [   6, 2581,   10,    5,    1,    5,    5,    4,    2,    6],
       [  12,    4, 2287,   17,    6,    2,    2,   10,    8,    1],
       [   1,    1,    7, 2244,    0,   24,    2,    9,    3,   10],
       [   3,    2,    9,    0, 2209,    6,    7,    5,    1,   23],
       [   4,    1,    2,   28,    2, 2023,   13,    2,    4,    7],
       [  16,    2,    5,    1,    6,    7, 2283,    0,    1,    0],
       [   9,    7,   24,   10,   17,    2,    0, 2269,    3,   29],
       [  20,   16,   22,   55,    9,   32,   19,    1, 2016,   24],
       [  14,    3,    0,   13,   38,   12,    0,   18,    1, 2232]])>

In [36]:
model4 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'tanh'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model4.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model4.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.3005 - accuracy: 0.9129
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1411 - accuracy: 0.9578
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0994 - accuracy: 0.9700
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0754 - accuracy: 0.9774
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0570 - accuracy: 0.9826


In [37]:
model4.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1089 - accuracy: 0.9668


[0.10889414697885513, 0.9667532444000244]

In [38]:
y_predict = model4.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 985us/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2194,    0,    5,    3,    2,    8,   19,    0,    5,    2],
       [   1, 2601,    3,    3,    0,    0,    3,    2,    6,    6],
       [   7,    8, 2276,   13,   15,    3,    4,    9,   13,    1],
       [   2,    2,   13, 2227,    1,   15,    2,   11,   20,    8],
       [   1,    5,    6,    2, 2206,    3,    6,    1,    4,   31],
       [   3,    2,    3,   42,    5, 1980,   23,    2,   20,    6],
       [   9,    6,    3,    1,   23,    7, 2262,    2,    8,    0],
       [   4,   19,   23,   14,   22,    2,    1, 2248,   11,   26],
       [   5,   13,    9,   17,    4,    9,   13,    2, 2133,    9],
       [   6,    5,    6,   22,   47,   12,    1,   17,   10, 2205]])>

In [39]:
model5 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'relu'),
    keras.layers.Dense(20, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model5.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model5.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.3709 - accuracy: 0.8880
Epoch 2/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1593 - accuracy: 0.9522
Epoch 3/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1178 - accuracy: 0.9645
Epoch 4/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.0970 - accuracy: 0.9706
Epoch 5/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.0830 - accuracy: 0.9743


In [40]:
model5.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1272 - accuracy: 0.9613


[0.12721951305866241, 0.9613419771194458]

In [41]:
y_predict = model5.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2181,    0,    4,    2,    6,    9,   14,    2,   19,    1],
       [   1, 2590,    4,    5,    2,    0,    6,    7,    8,    2],
       [  15,    8, 2234,   18,   17,    5,    7,   16,   25,    4],
       [   2,    2,   15, 2225,    2,   15,    1,   14,   14,   11],
       [   1,    3,    3,    0, 2232,    1,    5,    9,    0,   11],
       [   6,    2,    5,   54,   14, 1961,    7,   12,   14,   11],
       [  16,    9,    3,    0,   30,   24, 2226,    0,   13,    0],
       [   3,    5,   16,   17,   17,    2,    0, 2296,    1,   13],
       [   5,   22,    8,   22,   14,    9,   12,    9, 2101,   12],
       [   9,    2,    3,   28,   74,    4,    0,   39,   11, 2161]])>

In [42]:
model6 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'tanh'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'tanh'),
    keras.layers.Dense(20, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model6.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model6.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.3832 - accuracy: 0.9008
Epoch 2/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1617 - accuracy: 0.9523
Epoch 3/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1164 - accuracy: 0.9651
Epoch 4/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.0924 - accuracy: 0.9723
Epoch 5/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.0757 - accuracy: 0.9776


In [43]:
model6.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1194 - accuracy: 0.9663


[0.11939489841461182, 0.9663203358650208]

In [44]:
y_predict = model6.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2211,    0,    1,    1,    1,    7,    7,    0,    8,    2],
       [   2, 2573,   10,    7,    0,    0,    8,    7,   12,    6],
       [   6,    3, 2269,   14,    8,    3,    9,   15,   19,    3],
       [   3,    1,   14, 2190,    3,   31,    0,   30,   19,   10],
       [   5,    3,    4,    2, 2192,    2,    6,   10,    3,   38],
       [   5,    2,    3,   29,    3, 1996,   12,    8,   17,   11],
       [  17,    2,    3,    1,   12,   16, 2260,    1,    9,    0],
       [   5,    8,   13,    1,    8,    2,    2, 2303,    4,   24],
       [  12,   16,   10,   14,    5,   16,   11,    6, 2112,   12],
       [  11,    0,    2,   16,   27,   10,    1,   39,    9, 2216]])>

In [45]:
model7 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'relu'),
    keras.layers.Dense(20, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model7.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model7.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.4823 - accuracy: 0.8726
Epoch 2/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1979 - accuracy: 0.9414
Epoch 3/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1463 - accuracy: 0.9564
Epoch 4/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1171 - accuracy: 0.9654
Epoch 5/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.0987 - accuracy: 0.9705


In [46]:
model7.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1287 - accuracy: 0.9625


[0.12869030237197876, 0.9625108242034912]

In [47]:
y_predict = model1.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2206,    0,    0,    3,    2,    4,    8,    0,   10,    5],
       [   1, 2549,    6,   17,    0,    4,    1,   11,   26,   10],
       [  10,    4, 2204,   41,   15,    3,    8,   28,   33,    3],
       [   1,    1,   10, 2225,    0,   15,    1,   22,   15,   11],
       [   3,    0,    6,    3, 2165,    2,    7,    5,    5,   69],
       [  12,    1,    3,   55,    7, 1964,    6,    3,   20,   15],
       [  20,    5,    1,    1,   14,   20, 2236,    2,   22,    0],
       [   5,    6,    9,    7,   20,    1,    1, 2301,    1,   19],
       [   8,    9,    2,   38,    3,   11,    9,    6, 2102,   26],
       [  10,    1,    0,   24,   23,    4,    0,   28,    8, 2233]])>

In [48]:
model8 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model8.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model8.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.4111 - accuracy: 0.8878
Epoch 2/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1836 - accuracy: 0.9449
Epoch 3/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1346 - accuracy: 0.9596
Epoch 4/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1055 - accuracy: 0.9684
Epoch 5/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.0844 - accuracy: 0.9739


In [49]:
model8.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1185 - accuracy: 0.9630


[0.11847444623708725, 0.9629870057106018]

In [50]:
y_predict = model8.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2190,    0,    4,    1,    5,    6,   17,    1,   13,    1],
       [   1, 2594,    8,    1,    0,    3,    4,    3,    9,    2],
       [   4,    7, 2283,    0,    9,    3,    4,   12,   27,    0],
       [   4,    7,   36, 2064,    2,   67,    5,   25,   82,    9],
       [   2,    3,    8,    0, 2211,    1,    7,    4,    4,   25],
       [   6,    4,    7,   16,    8, 1985,   17,    2,   30,   11],
       [  11,    5,    5,    0,   11,   15, 2257,    0,   17,    0],
       [   4,   10,   18,    2,   23,    1,    1, 2288,    3,   20],
       [   5,   13,    8,    4,    4,    8,    9,    2, 2147,   14],
       [   7,    2,    0,    8,   35,    3,    1,   23,   26, 2226]])>

In [51]:
model9 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model9.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model9.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.3860 - accuracy: 0.8921
Epoch 2/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1806 - accuracy: 0.9459
Epoch 3/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1304 - accuracy: 0.9610
Epoch 4/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1002 - accuracy: 0.9695
Epoch 5/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.0794 - accuracy: 0.9749


In [52]:
model9.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1050 - accuracy: 0.9677


[0.10500309616327286, 0.9677489399909973]

In [53]:
y_predict = model9.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2200,    0,    2,    2,    2,    8,   13,    1,    6,    4],
       [   1, 2593,    7,    3,    0,    3,    3,    7,    5,    3],
       [  13,    7, 2264,   11,    7,    5,    4,   17,   16,    5],
       [   3,    2,   13, 2197,    0,   33,    0,   20,   17,   16],
       [   3,    3,    4,    0, 2201,    2,    5,    5,    3,   39],
       [   4,    3,    4,   20,    5, 2017,   10,    0,   11,   12],
       [  16,    7,    3,    1,   15,   21, 2246,    5,    7,    0],
       [   8,   11,   11,    2,   16,    2,    1, 2299,    2,   18],
       [  10,   22,    7,   14,    5,   18,   12,    3, 2092,   31],
       [   5,    4,    0,   14,   30,    5,    0,   22,    5, 2246]])>

In [54]:
model10 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model10.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model10.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.2756 - accuracy: 0.9205
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1217 - accuracy: 0.9632
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0821 - accuracy: 0.9753
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0632 - accuracy: 0.9795
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0477 - accuracy: 0.9849


In [55]:
model10.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1044 - accuracy: 0.9682


[0.10436118394136429, 0.9681817889213562]

In [56]:
y_predict = model10.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2187,    0,    2,    3,    0,    2,   13,    0,   24,    7],
       [   0, 2583,    4,    4,    0,    0,    1,   10,   15,    8],
       [   4,    8, 2228,   34,    7,    2,    6,   13,   44,    3],
       [   0,    1,   10, 2181,    1,   30,    1,   19,   36,   22],
       [   2,    5,    4,    1, 2166,    1,    8,    5,    3,   70],
       [   6,    1,    2,   24,    3, 2006,    5,    2,   25,   12],
       [   8,    5,    2,    2,    3,   24, 2267,    0,   10,    0],
       [   2,    0,   13,    1,   15,    2,    0, 2314,    5,   18],
       [   2,    3,    1,    7,    4,    7,    1,    3, 2152,   34],
       [   2,    0,    0,    5,   11,    3,    1,   19,    9, 2281]])>

In [57]:
model11 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'sigmoid'),
    keras.layers.Dense(40, activation = 'sigmoid'),
    keras.layers.Dense(10, activation = 'softmax')
])

model11.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model11.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.8663 - accuracy: 0.7774
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.2622 - accuracy: 0.9290
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1846 - accuracy: 0.9483
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1418 - accuracy: 0.9607
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1148 - accuracy: 0.9676


In [58]:
model11.evaluate(X_testf, y_test)

722/722 [==============================] - 2s 2ms/step - loss: 0.1448 - accuracy: 0.9581


[0.14475764334201813, 0.9581385254859924]

In [59]:
y_predict = model11.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 2ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2191,    0,   10,    2,    3,    5,   12,    3,   11,    1],
       [   1, 2571,    7,    9,    0,    5,    1,    7,   15,    9],
       [   9,   10, 2242,   18,   10,    8,   10,   13,   25,    4],
       [   1,    3,   19, 2163,    0,   37,    0,   21,   46,   11],
       [   2,    4,    8,    1, 2170,    3,   11,    3,   12,   51],
       [   7,    1,    5,   27,   10, 1989,   11,    2,   27,    7],
       [  14,    7,    8,    1,   18,   37, 2225,    0,   11,    0],
       [  10,   10,   18,    5,   19,    3,    1, 2262,    8,   34],
       [   5,   11,    6,   21,    4,   24,    6,    3, 2121,   13],
       [   8,    2,    4,   17,   30,   10,    1,   29,   31, 2199]])>

In [60]:
model12 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'relu'),
    keras.layers.Dense(40, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model12.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model12.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.3207 - accuracy: 0.9052
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1456 - accuracy: 0.9567
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1091 - accuracy: 0.9664
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0860 - accuracy: 0.9730
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0712 - accuracy: 0.9780


In [61]:
model12.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1155 - accuracy: 0.9664


[0.11545099318027496, 0.9664069414138794]

In [62]:
y_predict = model12.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2209,    0,    5,    1,    1,    0,    6,    1,   14,    1],
       [   0, 2588,    5,    4,    0,    0,    3,    6,   11,    8],
       [   6,    7, 2272,   17,    8,    1,    3,    8,   25,    2],
       [   1,    1,   21, 2222,    0,   17,    0,    8,   22,    9],
       [   1,    3,   10,    0, 2199,    0,   11,    8,    4,   29],
       [   9,    1,    5,   44,    3, 1970,    9,    2,   28,   15],
       [  21,    7,    5,    2,   12,   18, 2235,    0,   21,    0],
       [   5,    5,   19,    8,   17,    1,    0, 2281,    6,   28],
       [   6,    5,   12,   19,    7,    8,    2,    4, 2138,   13],
       [   8,    1,    3,   36,   39,    2,    1,   17,   14, 2210]])>

In [63]:
model13 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'tanh'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'tanh'),
    keras.layers.Dense(40, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model13.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model13.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.3119 - accuracy: 0.9121
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1436 - accuracy: 0.9574
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1050 - accuracy: 0.9686
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0807 - accuracy: 0.9747
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0656 - accuracy: 0.9795


In [64]:
model13.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1200 - accuracy: 0.9635


[0.11999968439340591, 0.9635065197944641]

In [65]:
y_predict = model13.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2162,    0,    3,    4,    3,   11,   31,    1,   12,   11],
       [   0, 2566,    7,   10,    4,    1,    5,    7,   20,    5],
       [   3,    1, 2271,   17,   10,    5,   11,    5,   25,    1],
       [   1,    0,   13, 2152,    3,   60,    4,   22,   34,   12],
       [   1,    2,    8,    2, 2198,    2,    9,    4,    8,   31],
       [   1,    1,    0,   27,    6, 2012,    5,    2,   19,   13],
       [   6,    1,    2,    1,    8,   31, 2257,    0,   14,    1],
       [   3,    7,   15,    2,   15,    2,    0, 2287,    7,   32],
       [   5,    5,    4,   19,    3,   21,   12,    2, 2134,    9],
       [   4,    2,    1,   14,   37,   11,    3,   17,   24, 2218]])>

In [66]:
model14 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'relu'),
    keras.layers.Dense(40, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model14.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model14.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.4159 - accuracy: 0.8816
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1837 - accuracy: 0.9454
Epoch 3/5
1466/1466 [==============================] - 4s 3ms/step - loss: 0.1347 - accuracy: 0.9599
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1088 - accuracy: 0.9671
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0889 - accuracy: 0.9729


In [67]:
model14.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 2ms/step - loss: 0.1297 - accuracy: 0.9597


[0.1296979784965515, 0.9597402811050415]

In [68]:
y_predict = model14.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2180,    0,    1,    1,   12,    5,   16,    1,   16,    6],
       [   1, 2572,    8,    3,    6,    5,    2,    3,   15,   10],
       [   8,   12, 2247,    9,   16,    3,    9,   14,   26,    5],
       [   2,    3,   20, 2116,    2,   40,    1,   18,   65,   34],
       [   1,    4,    4,    0, 2219,    1,    7,    3,    3,   23],
       [  12,    2,    2,   21,   16, 1961,    9,    3,   38,   22],
       [  11,    4,    2,    1,   18,   23, 2243,    0,   19,    0],
       [   3,    7,   16,    3,   27,    1,    0, 2256,    9,   48],
       [   9,    7,    3,    6,   12,    9,    7,    1, 2138,   22],
       [   4,    1,    0,    4,   50,    3,    1,   13,   17, 2238]])>

In [69]:
model15 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model15.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model15.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.4478 - accuracy: 0.8771
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1970 - accuracy: 0.9433
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1491 - accuracy: 0.9552
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1185 - accuracy: 0.9644
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0976 - accuracy: 0.9703


In [70]:
model15.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1326 - accuracy: 0.9591


[0.1325998604297638, 0.9591342210769653]

In [71]:
y_predict = model15.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2205,    0,    1,    2,    3,    4,   10,    1,    6,    6],
       [   1, 2572,    7,   10,    0,    4,    8,    7,    9,    7],
       [  15,    7, 2229,   15,   13,    7,   13,   22,   18,   10],
       [   6,    3,   18, 2150,    2,   49,    1,   25,   19,   28],
       [   2,    2,    7,    0, 2173,    3,    9,    3,    2,   64],
       [  10,    1,    4,   21,    9, 2006,    7,    2,   14,   12],
       [  22,    5,    2,    1,   14,   18, 2251,    1,    6,    1],
       [   6,    9,   10,    1,   13,    1,    2, 2276,    2,   50],
       [  13,   20,    5,   29,    7,   28,   16,    5, 2035,   56],
       [   8,    1,    0,   14,   22,    6,    0,   18,    3, 2259]])>