In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras

In [2]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()


In [3]:
x_train2 = x_train.reshape(len(x_train), 28 * 28)
df1 = pd.DataFrame(x_train2)


In [4]:
df1

0    1    2    3    4    5    6    7    8    9    ...  774  775  776  \
0        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
2        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
3        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
4        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
59995    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59996    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59997    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59998    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59999    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   

       777  778  779  780  781  782  783  
0        0    0    0    0    0    0    0  
1        0    0    0    0    0    0    0  
2        0    0    0    0    0    0    0  
3        0    0    0    0    0    0    0  
4        0    0    0    0    0    0    0  
...    ...  ...  ...  ...  ...  ...  ...  
59995    0    0    0    0    0    0    0  
59996    0    0    0    0    0    0    0  
59997    0    0    0    0    0    0    0  
59998    0    0    0    0    0    0    0  
59999    0    0    0    0    0    0    0  

[60000 rows x 784 columns]

In [5]:
df1_target = pd.DataFrame(y_train)

In [6]:
df1_target

0
0      5
1      0
2      4
3      1
4      9
...   ..
59995  8
59996  3
59997  5
59998  6
59999  8

[60000 rows x 1 columns]

In [7]:
df1['target'] = df1_target[0]
df1.head()

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  782  \
0  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
1  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
2  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
3  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
4  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   

   783  target  
0    0       5  
1    0       0  
2    0       4  
3    0       1  
4    0       9  

[5 rows x 785 columns]

# We did the merging for X_train and y_train, now lets do it for X_test and y_test

In [8]:
x_test2 = x_test.reshape(len(x_test), 28 * 28)
df2 = pd.DataFrame(x_test2)
df2_target = pd.DataFrame(y_test)
df2['target'] = df2_target[0]
df2.head()

##MERGING HAS BEEN DONE. WE NOW HAVE DF1 and DF2

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  782  \
0  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
1  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
2  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
3  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
4  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   

   783  target  
0    0       7  
1    0       2  
2    0       1  
3    0       0  
4    0       4  

[5 rows x 785 columns]

In [9]:
##NOW GETTING THE DF IN WHICH WE WILL MERGE ALL OF THESE
df3 = pd.concat([df1, df2], ignore_index = True)
df3

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  \
0      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
1      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
2      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
3      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
4      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
...   .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
69995  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69996  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69997  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69998  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69999  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   

       782  783  target  
0        0    0       5  
1        0    0       0  
2        0    0       4  
3        0    0       1  
4        0    0       9  
...    ...  ...     ...  
69995    0    0       2  
69996    0    0       3  
69997    0    0       4  
69998    0    0       5  
69999    0    0       6  

[70000 rows x 785 columns]

In [10]:
# y = df3['target']
# y = pd.DataFrame(y)
# y.head()
df_train = df3.sample(frac=0.67,random_state=4)
df_test = df3.drop(df_train.index)
df_train

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  \
60025  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
64579  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
30112  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
45138  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
21691  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
...   .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
832    0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
39589  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
17598  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
2643   0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
11663  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   

       782  783  target  
60025    0    0       0  
64579    0    0       6  
30112    0    0       5  
45138    0    0       6  
21691    0    0       2  
...    ...  ...     ...  
832      0    0       5  
39589    0    0       6  
17598    0    0       5  
2643     0    0       9  
11663    0    0       1  

[46900 rows x 785 columns]

In [11]:
y_train = df_train['target']
y_train = pd.DataFrame(y_train)
y_train.head()
# df_train = df_train.drop('target', axis = 1, inplace = True)
# df_train.head()

target
60025       0
64579       6
30112       5
45138       6
21691       2

In [12]:
df_train = df_train.drop('target', axis=1)


In [13]:
df_train.head()
df_test

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  \
1      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
2      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
12     0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
13     0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
14     0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
...   .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
69983  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69987  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69993  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69995  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69996  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   

       782  783  target  
1        0    0       0  
2        0    0       4  
12       0    0       3  
13       0    0       6  
14       0    0       1  
...    ...  ...     ...  
69983    0    0       0  
69987    0    0       4  
69993    0    0       0  
69995    0    0       2  
69996    0    0       3  

[23100 rows x 785 columns]

In [14]:
y_test = df_test['target']
y_test = pd.DataFrame(y_test)
y_test.head()

target
1        0
2        4
12       3
13       6
14       1

In [15]:
df_test = df_test.drop('target', axis=1)


In [16]:
df_test.head()

0    1    2    3    4    5    6    7    8    9    ...  774  775  776  777  \
1     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
2     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
12    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
13    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
14    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   

    778  779  780  781  782  783  
1     0    0    0    0    0    0  
2     0    0    0    0    0    0  
12    0    0    0    0    0    0  
13    0    0    0    0    0    0  
14    0    0    0    0    0    0  

[5 rows x 784 columns]

# Converting these into NumPy arrays for use in the ANN model

In [17]:
x_train = df_train.to_numpy()
x_train
x_test = df_test.to_numpy()
y_train = y_train.to_numpy()
y_test = y_test.to_numpy()

# Performing the required pre-processing

In [18]:
x_train = x_train/255
x_test = x_test/255

In [19]:
#x_train[0]

In [20]:
X_trainf = x_train.reshape(len(x_train), 28 * 28)
#we choose to flatten the data in order to make the first input layer of the neural network have 784 values, since we currently have values stored in 28*28 form

In [21]:
X_testf = x_test.reshape(len(x_test), 28*28)

# MODEL 1 -- 150 neurons, 2 layers, sigmoid

In [22]:
model1 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'sigmoid'),
    keras.layers.Dense(10, activation = 'softmax')
])

model1.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model1.fit(X_trainf, y_train, epochs = 5)



Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.5890 - accuracy: 0.8543
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.2149 - accuracy: 0.9381
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1589 - accuracy: 0.9539
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1253 - accuracy: 0.9641
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1013 - accuracy: 0.9701


In [23]:
model1.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 942us/step - loss: 0.1250 - accuracy: 0.9610


[0.12502571940422058, 0.9609524011611938]

In [24]:
y_predict = model1.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 825us/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2230,    0,    3,    5,    0,   14,   11,    5,   14,   14],
       [   0, 2552,   10,   10,    4,    2,    3,    7,    8,    4],
       [   7,    7, 2187,   35,   13,    3,    3,   20,   17,    4],
       [   2,    4,   13, 2221,    1,   43,    1,   11,   14,   13],
       [   2,    7,    6,    1, 2161,    1,   11,    2,    6,   82],
       [   7,    3,    2,   29,    5, 1992,   14,    4,    5,   13],
       [  11,    7,    3,    4,   11,   26, 2139,    3,    6,    0],
       [   1,    9,   16,   10,    8,    1,    1, 2393,    4,   22],
       [   8,   27,    5,   46,    6,   24,    7,    3, 2160,   20],
       [   3,    2,    0,   23,   25,    8,    2,   22,    3, 2163]])>

# MODEL 2 -- 100 Neurons, 3 Hidden Layers

In [25]:
model2 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'sigmoid'),
    keras.layers.Dense(20, activation = 'sigmoid'),
    keras.layers.Dense(10, activation = 'softmax')
])

model2.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model2.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 1.1298 - accuracy: 0.7212
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.3458 - accuracy: 0.9168
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.2237 - accuracy: 0.9413
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1743 - accuracy: 0.9530
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1431 - accuracy: 0.9612


In [26]:
model2.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1667 - accuracy: 0.9513


[0.1666625589132309, 0.951298713684082]

In [27]:
y_predict = model2.predict(X_testf)

722/722 [==============================] - 1s 1ms/step


In [28]:
y_predict[0]

array([9.9583071e-01, 6.5443265e-07, 8.7698470e-05, 5.8533018e-04,
       1.1263703e-04, 1.4824913e-03, 2.3046756e-04, 4.1259911e-05,
       2.8851664e-06, 1.6258536e-03], dtype=float32)

In [29]:
np.argmax(y_predict[0]) #gives the maximum value out of the given ones

0

In [30]:
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array

In [31]:
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices


In [32]:
cm #this is the confusion matrix, we are supposed to do this for all 15 of the models. Preferable if we beautify this a bit using matPlotLib, or seaborn if permitted by sir

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2252,    0,    5,    4,    2,   11,   11,    2,    6,    3],
       [   0, 2527,   21,   10,    1,    1,    5,   12,   15,    8],
       [   4,    6, 2195,   17,    8,    8,   16,   17,   24,    1],
       [   3,   10,   29, 2173,    1,   62,    2,   10,   16,   17],
       [   5,    5,    7,    1, 2157,    4,   21,    1,    6,   72],
       [  21,    1,    8,   50,   10, 1915,   24,    1,   22,   22],
       [  14,    3,   18,    0,   13,   17, 2138,    0,    7,    0],
       [   1,   10,   21,    6,    8,    1,    2, 2366,    7,   43],
       [   8,   23,   29,   21,   11,   41,   17,   12, 2119,   25],
       [  15,    1,    0,   24,   39,   15,    1,   21,    2, 2133]])>

# MODEL 3 -- 150 Neurons, 2 Hidden Layers, ReLU

In [33]:
model3 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model3.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model3.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.2819 - accuracy: 0.9182
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1252 - accuracy: 0.9620
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0916 - accuracy: 0.9725
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0708 - accuracy: 0.9779
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0557 - accuracy: 0.9823


In [34]:
model3.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1055 - accuracy: 0.9686


[0.10553912818431854, 0.9685714244842529]

In [35]:
y_predict = model3.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 926us/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2264,    0,    3,    3,    2,    2,    8,    1,    2,   11],
       [   0, 2564,    7,    4,    6,    2,    3,    5,    5,    4],
       [  11,    4, 2232,   12,    2,    0,    5,   25,    1,    4],
       [   2,    2,   23, 2232,    1,   35,    2,   11,    4,   11],
       [   1,    5,    7,    1, 2170,    0,   16,    3,    2,   74],
       [   9,    1,    1,   15,    1, 2007,   19,    0,    6,   15],
       [   9,    2,    0,    0,    7,   16, 2175,    0,    1,    0],
       [   0,    4,    5,    4,    4,    1,    1, 2432,    2,   12],
       [   8,   17,   12,   64,    5,   37,   12,   20, 2091,   40],
       [   4,    1,    0,    8,    6,    7,    0,   16,    2, 2207]])>

In [36]:
model4 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'tanh'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model4.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model4.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.2980 - accuracy: 0.9138
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1412 - accuracy: 0.9590
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0976 - accuracy: 0.9703
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0715 - accuracy: 0.9784
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0555 - accuracy: 0.9828


In [37]:
model4.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.0994 - accuracy: 0.9698


[0.099443718791008, 0.9697835445404053]

In [38]:
y_predict = model4.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 947us/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2274,    1,    4,    0,    1,    2,    5,    0,    6,    3],
       [   0, 2568,    4,    5,    6,    2,    2,    8,    4,    1],
       [   8,    8, 2240,    7,    5,    1,    4,    6,   14,    3],
       [   4,    5,   22, 2203,    2,   33,    2,   10,   32,   10],
       [   4,    6,    9,    2, 2206,    0,   13,    4,    5,   30],
       [  14,    2,    2,   10,    2, 1977,   37,    2,   19,    9],
       [   9,    2,    3,    0,   12,    2, 2177,    0,    5,    0],
       [   2,    9,   25,    6,    9,    4,    0, 2389,    5,   16],
       [   7,   12,   12,    8,    4,   12,   10,    2, 2230,    9],
       [   5,    2,    0,   12,   50,   10,    1,   28,    5, 2138]])>

In [39]:
model5 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'relu'),
    keras.layers.Dense(20, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model5.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model5.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.3672 - accuracy: 0.8870
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1553 - accuracy: 0.9543
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1179 - accuracy: 0.9642
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0925 - accuracy: 0.9721
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0802 - accuracy: 0.9755


In [40]:
model5.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1153 - accuracy: 0.9652


[0.1153378039598465, 0.9651514887809753]

In [41]:
y_predict = model5.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 955us/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2251,    1,    2,    1,    2,    4,   15,    1,   17,    2],
       [   0, 2559,    5,    9,    4,    0,    4,    5,    9,    5],
       [   8,    9, 2217,   16,    5,    0,    5,   14,   18,    4],
       [   1,    4,   23, 2219,    0,   17,    1,   14,   29,   15],
       [   4,    6,    8,    0, 2125,    0,   13,    8,    9,  106],
       [  14,    1,    2,   34,    2, 1947,   20,    2,   22,   30],
       [  10,    7,    4,    1,    2,    8, 2162,    0,   16,    0],
       [   1,    8,   11,    2,    7,    1,    1, 2401,    3,   30],
       [  12,    9,    1,   14,    4,    7,    6,    4, 2228,   21],
       [   8,    1,    3,   15,    8,    3,    2,   17,    8, 2186]])>

In [42]:
model6 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'tanh'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'tanh'),
    keras.layers.Dense(20, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model6.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model6.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.3872 - accuracy: 0.8986
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1605 - accuracy: 0.9534
Epoch 3/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1160 - accuracy: 0.9654
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0929 - accuracy: 0.9723
Epoch 5/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.0770 - accuracy: 0.9763


In [43]:
model6.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1219 - accuracy: 0.9620


[0.12185728549957275, 0.9619913697242737]

In [44]:
y_predict = model6.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 975us/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2247,    0,    3,    2,    1,    3,   21,    0,   13,    6],
       [   0, 2539,   13,   10,   10,    1,    6,    7,    6,    8],
       [   8,    3, 2237,    7,    8,    0,    6,    7,   16,    4],
       [   0,    3,   35, 2181,    2,   34,    1,   17,   22,   28],
       [   3,    2,    9,    3, 2187,    2,   13,    0,    2,   58],
       [  10,    1,    5,   27,    6, 1955,   30,    1,   19,   20],
       [   8,    0,    3,    0,    9,    4, 2182,    0,    4,    0],
       [   3,    7,   31,    7,   15,    1,    1, 2344,    5,   51],
       [   6,   15,   18,   11,    3,   15,   19,    2, 2175,   42],
       [   5,    2,    0,   10,   28,   12,    2,   13,    4, 2175]])>

In [45]:
model7 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'relu'),
    keras.layers.Dense(20, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model7.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model7.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.4762 - accuracy: 0.8753
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1951 - accuracy: 0.9431
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1445 - accuracy: 0.9571
Epoch 4/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1154 - accuracy: 0.9652
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0955 - accuracy: 0.9723


In [46]:
model7.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1223 - accuracy: 0.9623


[0.12230061739683151, 0.9622943997383118]

In [47]:
y_predict = model1.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2230,    0,    3,    5,    0,   14,   11,    5,   14,   14],
       [   0, 2552,   10,   10,    4,    2,    3,    7,    8,    4],
       [   7,    7, 2187,   35,   13,    3,    3,   20,   17,    4],
       [   2,    4,   13, 2221,    1,   43,    1,   11,   14,   13],
       [   2,    7,    6,    1, 2161,    1,   11,    2,    6,   82],
       [   7,    3,    2,   29,    5, 1992,   14,    4,    5,   13],
       [  11,    7,    3,    4,   11,   26, 2139,    3,    6,    0],
       [   1,    9,   16,   10,    8,    1,    1, 2393,    4,   22],
       [   8,   27,    5,   46,    6,   24,    7,    3, 2160,   20],
       [   3,    2,    0,   23,   25,    8,    2,   22,    3, 2163]])>

In [48]:
model8 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model8.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model8.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.4043 - accuracy: 0.8885
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1819 - accuracy: 0.9463
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1331 - accuracy: 0.9602
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1030 - accuracy: 0.9691
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0825 - accuracy: 0.9755


In [49]:
model8.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1150 - accuracy: 0.9638


[0.1150006353855133, 0.9638095498085022]

In [50]:
y_predict = model8.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 954us/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2243,    0,    4,    0,    0,   18,   11,    1,   11,    8],
       [   0, 2544,    6,    6,    5,    4,    6,   11,   14,    4],
       [  14,    5, 2223,    7,   13,    3,    4,   12,   12,    3],
       [   5,    5,   28, 2135,    3,   84,    1,   24,   18,   20],
       [   2,    4,    6,    0, 2194,    2,   10,    5,    4,   52],
       [   8,    2,    2,   11,    3, 2017,   14,    5,    4,    8],
       [  14,    2,    1,    0,   17,   18, 2153,    0,    5,    0],
       [   0,    7,   22,    1,    8,    3,    0, 2412,    4,    8],
       [   7,   15,    7,    7,    7,   34,   11,    7, 2195,   16],
       [   5,    1,    0,    6,   26,   16,    0,   44,    5, 2148]])>

In [51]:
model9 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model9.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model9.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.3996 - accuracy: 0.8896
Epoch 2/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1827 - accuracy: 0.9458
Epoch 3/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1339 - accuracy: 0.9594
Epoch 4/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1035 - accuracy: 0.9688
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0823 - accuracy: 0.9746


In [52]:
model9.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1119 - accuracy: 0.9642


[0.11193865537643433, 0.9641558527946472]

In [53]:
y_predict = model9.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2258,    0,    3,    2,    1,   10,   10,    4,    5,    3],
       [   0, 2552,   18,    5,    5,    2,    2,    7,    6,    3],
       [  12,    2, 2244,   10,    4,    2,    4,   10,    7,    1],
       [   3,    2,   29, 2193,    3,   44,    2,   20,   16,   11],
       [   3,    4,   21,    0, 2184,    0,   10,    2,    7,   48],
       [  16,    6,    4,   17,    4, 1983,   25,    5,    5,    9],
       [  11,    4,    9,    0,   11,    8, 2164,    0,    3,    0],
       [   1,   11,   31,    7,    7,    1,    0, 2394,    2,   11],
       [  11,   32,   20,   25,    7,   21,   13,    6, 2148,   23],
       [   9,    4,    1,   12,   27,   10,    0,   32,    4, 2152]])>

In [54]:
model10 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model10.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model10.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.2656 - accuracy: 0.9249
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1187 - accuracy: 0.9639
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0831 - accuracy: 0.9746
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0628 - accuracy: 0.9809
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0480 - accuracy: 0.9849


In [55]:
model10.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1021 - accuracy: 0.9685


[0.10206154733896255, 0.9684848189353943]

In [56]:
y_predict = model10.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2241,    1,    9,    1,    1,    8,   15,    0,   12,    8],
       [   0, 2572,    5,    4,    3,    1,    1,    5,    7,    2],
       [   5,    7, 2249,    5,    7,    1,    4,    2,   13,    3],
       [   1,    4,   24, 2215,    2,   37,    0,    5,   20,   15],
       [   1,    5,    7,    1, 2186,    3,    8,    0,    2,   66],
       [   3,    2,    2,   29,    2, 1997,   12,    0,   15,   12],
       [   4,    6,    3,    0,    6,   13, 2174,    0,    4,    0],
       [   1,   13,   35,   15,    8,    1,    0, 2323,   11,   58],
       [   4,   23,    9,    8,    5,   12,    4,    3, 2203,   35],
       [   2,    3,    1,    5,    7,    6,    2,    9,    4, 2212]])>

In [57]:
model11 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'sigmoid'),
    keras.layers.Dense(40, activation = 'sigmoid'),
    keras.layers.Dense(10, activation = 'softmax')
])

model11.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model11.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.7951 - accuracy: 0.8024
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.2304 - accuracy: 0.9368
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1645 - accuracy: 0.9538
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1305 - accuracy: 0.9625
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1068 - accuracy: 0.9693


In [58]:
model11.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1315 - accuracy: 0.9609


[0.13147211074829102, 0.9608657956123352]

In [59]:
y_predict = model11.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2235,    0,   16,    4,    2,    7,   17,    5,    7,    3],
       [   0, 2544,    8,   15,    4,    1,    3,   15,    8,    2],
       [   5,    4, 2226,   17,   11,    0,    4,   21,    6,    2],
       [   1,    4,   32, 2208,    3,   22,    1,   24,   22,    6],
       [   3,    8,   10,    2, 2201,    0,   12,    3,    4,   36],
       [   6,    1,    4,   42,   12, 1949,   33,    3,   12,   12],
       [   5,    2,    9,    0,   14,   12, 2166,    0,    2,    0],
       [   1,   13,   27,    5,    7,    1,    2, 2394,    2,   13],
       [   6,   27,   21,   35,   13,   21,    6,    7, 2163,    7],
       [   6,    4,    1,   26,   49,    7,    1,   44,    3, 2110]])>

In [60]:
model12 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'relu'),
    keras.layers.Dense(40, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model12.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model12.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 4s 2ms/step - loss: 0.3428 - accuracy: 0.9001
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1427 - accuracy: 0.9574
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1062 - accuracy: 0.9678
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0821 - accuracy: 0.9742
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0685 - accuracy: 0.9784


In [61]:
model12.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 2ms/step - loss: 0.1386 - accuracy: 0.9587


[0.1386113166809082, 0.9587013125419617]

In [62]:
y_predict = model12.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 2ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2209,    2,    4,    2,    1,    9,   46,    1,   22,    0],
       [   0, 2579,    8,    1,    3,    2,    2,    3,    2,    0],
       [   9,    8, 2239,    4,    4,    6,    8,    9,    8,    1],
       [   4,   14,   39, 2131,    0,   95,    2,   14,   19,    5],
       [   2,   15,   13,    3, 2135,    5,   44,    2,   16,   44],
       [   5,    6,    3,    4,    2, 2018,   28,    0,    2,    6],
       [   3,    7,    2,    0,    2,    4, 2192,    0,    0,    0],
       [   3,   16,   25,    3,    6,    4,    1, 2382,    7,   18],
       [   5,   44,   19,    9,    1,   41,   24,    5, 2150,    8],
       [  10,    5,    0,   23,   21,   36,    0,   28,   17, 2111]])>

In [63]:
model13 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'tanh'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'tanh'),
    keras.layers.Dense(40, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model13.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model13.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.3205 - accuracy: 0.9090
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1477 - accuracy: 0.9559
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1033 - accuracy: 0.9696
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0810 - accuracy: 0.9755
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0654 - accuracy: 0.9794


In [64]:
model13.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1029 - accuracy: 0.9684


[0.10286888480186462, 0.9683550000190735]

In [65]:
y_predict = model13.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2225,    0,    9,    5,    3,    8,   17,    2,   22,    5],
       [   0, 2518,   19,   10,   10,    4,    5,    9,   22,    3],
       [   2,    0, 2248,    9,    4,    1,    3,   17,    9,    3],
       [   0,    1,   21, 2215,    1,   36,    2,   18,   17,   12],
       [   1,    0,   12,    0, 2192,    0,   11,    9,    6,   48],
       [   3,    0,    1,   21,    4, 2006,   13,    2,   16,    8],
       [   8,    2,    4,    0,    6,   10, 2174,    2,    4,    0],
       [   0,    3,   21,    6,    6,    4,    1, 2397,    8,   19],
       [   2,   10,   17,    8,    4,    8,    8,    8, 2232,    9],
       [   5,    1,    1,   15,   29,   10,    0,   18,   10, 2162]])>

In [66]:
model14 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'relu'),
    keras.layers.Dense(40, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model14.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model14.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.4141 - accuracy: 0.8850
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1828 - accuracy: 0.9462
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1355 - accuracy: 0.9596
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1076 - accuracy: 0.9675
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0873 - accuracy: 0.9733


In [67]:
model14.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1234 - accuracy: 0.9616


[0.12335477769374847, 0.961601734161377]

In [68]:
y_predict = model14.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2243,    0,    2,    2,    0,   16,   15,    0,    7,   11],
       [   0, 2546,   13,   10,    2,    1,    5,    8,    4,   11],
       [   7,    4, 2219,   24,    4,    2,    3,   11,   16,    6],
       [   1,    2,   15, 2231,    1,   25,    1,   13,   19,   15],
       [   2,    5,    9,    2, 2076,    4,   29,    4,   11,  137],
       [   5,    2,    3,   24,    0, 1993,   20,    4,    7,   16],
       [  10,    3,    0,    0,    1,   13, 2181,    0,    2,    0],
       [   0,    7,   20,    8,    3,    5,    2, 2372,    4,   44],
       [   5,   17,    8,   20,    4,   30,   13,    7, 2170,   32],
       [   5,    2,    0,   17,    9,   12,    2,   19,    3, 2182]])>

In [69]:
model15 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model15.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model15.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.4526 - accuracy: 0.8817
Epoch 2/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.2042 - accuracy: 0.9401
Epoch 3/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1534 - accuracy: 0.9549
Epoch 4/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1234 - accuracy: 0.9638
Epoch 5/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1025 - accuracy: 0.9698


In [70]:
model15.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1280 - accuracy: 0.9604


[0.12801909446716309, 0.9603896141052246]

In [71]:
y_predict = model15.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2266,    0,    4,    5,    0,    5,    4,    1,    6,    5],
       [   0, 2544,    5,   12,    6,    1,    4,   10,   11,    7],
       [  18,   13, 2196,   30,    7,    0,    2,    8,   16,    6],
       [   8,    6,   13, 2225,    2,   19,    2,    7,   21,   20],
       [   5,    3,   11,    1, 2173,    1,   12,    1,    3,   69],
       [  14,    4,    2,   39,    5, 1938,   29,    2,   15,   26],
       [  23,    5,    5,    1,   17,   16, 2138,    0,    5,    0],
       [   3,    9,   21,   22,    9,    1,    1, 2364,    5,   30],
       [  14,   25,   10,   26,    4,   14,   12,    3, 2165,   33],
       [   9,    2,    0,   12,   31,    2,    0,   17,    2, 2176]])>