In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras

In [2]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()


In [3]:
x_train2 = x_train.reshape(len(x_train), 28 * 28)
df1 = pd.DataFrame(x_train2)


In [4]:
df1

0    1    2    3    4    5    6    7    8    9    ...  774  775  776  \
0        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
2        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
3        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
4        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
59995    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59996    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59997    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59998    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59999    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   

       777  778  779  780  781  782  783  
0        0    0    0    0    0    0    0  
1        0    0    0    0    0    0    0  
2        0    0    0    0    0    0    0  
3        0    0    0    0    0    0    0  
4        0    0    0    0    0    0    0  
...    ...  ...  ...  ...  ...  ...  ...  
59995    0    0    0    0    0    0    0  
59996    0    0    0    0    0    0    0  
59997    0    0    0    0    0    0    0  
59998    0    0    0    0    0    0    0  
59999    0    0    0    0    0    0    0  

[60000 rows x 784 columns]

In [5]:
df1_target = pd.DataFrame(y_train)

In [6]:
df1_target

0
0      5
1      0
2      4
3      1
4      9
...   ..
59995  8
59996  3
59997  5
59998  6
59999  8

[60000 rows x 1 columns]

In [7]:
df1['target'] = df1_target[0]
df1.head()

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  782  \
0  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
1  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
2  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
3  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
4  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   

   783  target  
0    0       5  
1    0       0  
2    0       4  
3    0       1  
4    0       9  

[5 rows x 785 columns]

# We did the merging for X_train and y_train, now lets do it for X_test and y_test

In [8]:
x_test2 = x_test.reshape(len(x_test), 28 * 28)
df2 = pd.DataFrame(x_test2)
df2_target = pd.DataFrame(y_test)
df2['target'] = df2_target[0]
df2.head()

##MERGING HAS BEEN DONE. WE NOW HAVE DF1 and DF2

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  782  \
0  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
1  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
2  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
3  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
4  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   

   783  target  
0    0       7  
1    0       2  
2    0       1  
3    0       0  
4    0       4  

[5 rows x 785 columns]

In [9]:
##NOW GETTING THE DF IN WHICH WE WILL MERGE ALL OF THESE
df3 = pd.concat([df1, df2], ignore_index = True)
df3

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  \
0      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
1      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
2      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
3      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
4      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
...   .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
69995  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69996  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69997  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69998  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69999  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   

       782  783  target  
0        0    0       5  
1        0    0       0  
2        0    0       4  
3        0    0       1  
4        0    0       9  
...    ...  ...     ...  
69995    0    0       2  
69996    0    0       3  
69997    0    0       4  
69998    0    0       5  
69999    0    0       6  

[70000 rows x 785 columns]

In [10]:
# y = df3['target']
# y = pd.DataFrame(y)
# y.head()
df_train = df3.sample(frac=0.67,random_state=39)
df_test = df3.drop(df_train.index)
df_train

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  \
28691  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
47047  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
54270  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
59638  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
4205   0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
...   .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
8588   0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
58455  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
39867  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
14307  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
33174  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   

       782  783  target  
28691    0    0       4  
47047    0    0       6  
54270    0    0       3  
59638    0    0       7  
4205     0    0       4  
...    ...  ...     ...  
8588     0    0       1  
58455    0    0       7  
39867    0    0       4  
14307    0    0       7  
33174    0    0       9  

[46900 rows x 785 columns]

In [11]:
y_train = df_train['target']
y_train = pd.DataFrame(y_train)
y_train.head()
# df_train = df_train.drop('target', axis = 1, inplace = True)
# df_train.head()

target
28691       4
47047       6
54270       3
59638       7
4205        4

In [12]:
df_train = df_train.drop('target', axis=1)


In [13]:
df_train.head()
df_test

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  \
1      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
2      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
3      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
5      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
12     0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
...   .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
69988  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69991  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69993  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69995  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69998  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   

       782  783  target  
1        0    0       0  
2        0    0       4  
3        0    0       1  
5        0    0       2  
12       0    0       3  
...    ...  ...     ...  
69988    0    0       5  
69991    0    0       8  
69993    0    0       0  
69995    0    0       2  
69998    0    0       5  

[23100 rows x 785 columns]

In [14]:
y_test = df_test['target']
y_test = pd.DataFrame(y_test)
y_test.head()

target
1        0
2        4
3        1
5        2
12       3

In [15]:
df_test = df_test.drop('target', axis=1)


In [16]:
df_test.head()

0    1    2    3    4    5    6    7    8    9    ...  774  775  776  777  \
1     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
2     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
3     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
5     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
12    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   

    778  779  780  781  782  783  
1     0    0    0    0    0    0  
2     0    0    0    0    0    0  
3     0    0    0    0    0    0  
5     0    0    0    0    0    0  
12    0    0    0    0    0    0  

[5 rows x 784 columns]

# Converting these into NumPy arrays for use in the ANN model

In [17]:
x_train = df_train.to_numpy()
x_train
x_test = df_test.to_numpy()
y_train = y_train.to_numpy()
y_test = y_test.to_numpy()

# Performing the required pre-processing

In [18]:
x_train = x_train/255
x_test = x_test/255

In [19]:
#x_train[0]

In [20]:
X_trainf = x_train.reshape(len(x_train), 28 * 28)
#we choose to flatten the data in order to make the first input layer of the neural network have 784 values, since we currently have values stored in 28*28 form

In [21]:
X_testf = x_test.reshape(len(x_test), 28*28)

# MODEL 1 -- 150 neurons, 2 layers, sigmoid

In [22]:
model1 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'sigmoid'),
    keras.layers.Dense(10, activation = 'softmax')
])

model1.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model1.fit(X_trainf, y_train, epochs = 5)



Epoch 1/5
1466/1466 [==============================] - 3s 1ms/step - loss: 0.5795 - accuracy: 0.8557
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.2171 - accuracy: 0.9365
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1575 - accuracy: 0.9539
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1234 - accuracy: 0.9629
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1005 - accuracy: 0.9697


In [23]:
model1.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1170 - accuracy: 0.9661


[0.11703000217676163, 0.9660605788230896]

In [24]:
y_predict = model1.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 929us/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2292,    0,    1,    2,    5,    7,   16,    0,    5,    3],
       [   0, 2618,    5,    3,    1,    4,    1,    4,    4,    2],
       [  13,    8, 2158,   15,   17,    4,   17,   11,   17,    1],
       [   0,    9,   16, 2345,    2,   31,    3,   12,   12,   10],
       [   2,    6,    3,    0, 2165,    2,    6,    5,    2,   35],
       [  12,    1,    2,   20,    5, 1986,   22,    1,   10,   10],
       [  12,    1,    2,    0,    6,   16, 2165,    0,    9,    0],
       [  11,   13,    9,   12,   10,    5,    0, 2249,    2,   29],
       [  12,   19,   11,   23,    9,   25,   20,    2, 2106,   11],
       [   6,    8,    0,   14,   35,   18,    2,   18,    9, 2232]])>

# MODEL 2 -- 100 Neurons, 3 Hidden Layers

In [25]:
model2 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'sigmoid'),
    keras.layers.Dense(20, activation = 'sigmoid'),
    keras.layers.Dense(10, activation = 'softmax')
])

model2.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model2.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 1.1857 - accuracy: 0.7051
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.3621 - accuracy: 0.9096
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.2381 - accuracy: 0.9369
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1821 - accuracy: 0.9508
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1481 - accuracy: 0.9603


In [26]:
model2.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1584 - accuracy: 0.9564


[0.15842032432556152, 0.9564069509506226]

In [27]:
y_predict = model2.predict(X_testf)

722/722 [==============================] - 1s 982us/step


In [28]:
y_predict[0]

array([9.9393296e-01, 4.0903906e-08, 1.3544700e-04, 1.0311697e-04,
       8.8670386e-05, 1.1237164e-03, 1.2173334e-03, 3.1974963e-03,
       1.9603876e-04, 5.1922834e-06], dtype=float32)

In [29]:
np.argmax(y_predict[0]) #gives the maximum value out of the given ones

0

In [30]:
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array

In [31]:
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices


In [32]:
cm #this is the confusion matrix, we are supposed to do this for all 15 of the models. Preferable if we beautify this a bit using matPlotLib, or seaborn if permitted by sir

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2280,    0,    3,    4,    1,   16,   13,    6,    7,    1],
       [   0, 2589,   13,    3,    2,    4,    3,    5,   15,    8],
       [   8,    8, 2136,   26,   16,   13,   19,   12,   22,    1],
       [   4,    4,   28, 2296,    3,   50,    0,   15,   29,   11],
       [   0,    6,    7,    0, 2138,   15,   10,    1,    2,   47],
       [   8,    1,    3,   21,    9, 1987,   13,    2,   19,    6],
       [  10,    1,    8,    0,   13,   20, 2143,    0,   16,    0],
       [   6,    9,   10,   18,   15,    7,    4, 2219,    6,   46],
       [   5,   21,    9,   23,    3,   44,   17,    1, 2106,    9],
       [   2,    8,    0,   18,   44,   31,    2,   27,   11, 2199]])>

# MODEL 3 -- 150 Neurons, 2 Hidden Layers, ReLU

In [33]:
model3 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model3.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model3.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.2915 - accuracy: 0.9146
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1285 - accuracy: 0.9610
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0922 - accuracy: 0.9718
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0714 - accuracy: 0.9778
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0547 - accuracy: 0.9826


In [34]:
model3.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1006 - accuracy: 0.9713


[0.10059336572885513, 0.9713419675827026]

In [35]:
y_predict = model3.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2287,    0,    5,    2,    0,    4,   14,    2,   12,    5],
       [   0, 2609,    9,    1,    1,    1,    2,    7,    9,    3],
       [   7,    3, 2186,   13,    4,    0,    9,   24,   14,    1],
       [   0,    8,   17, 2343,    1,   14,    2,   15,   28,   12],
       [   0,    6,    3,    0, 2125,    1,    9,    8,    6,   68],
       [   5,    2,    0,   16,    2, 1976,   26,    3,   23,   16],
       [  11,    0,    1,    1,    2,    2, 2185,    0,    9,    0],
       [   5,    4,    7,    1,    7,    2,    0, 2292,    4,   18],
       [   7,   12,    6,   12,    3,   17,    8,    3, 2162,    8],
       [   9,    3,    0,    3,    7,    3,    0,   24,   20, 2273]])>

In [36]:
model4 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'tanh'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model4.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model4.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 3s 1ms/step - loss: 0.3046 - accuracy: 0.9116
Epoch 2/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1425 - accuracy: 0.9575
Epoch 3/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1003 - accuracy: 0.9695
Epoch 4/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.0752 - accuracy: 0.9770
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0580 - accuracy: 0.9818


In [37]:
model4.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.0957 - accuracy: 0.9713


[0.09570720791816711, 0.9712986946105957]

In [38]:
y_predict = model4.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 2ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2292,    0,    9,    2,    2,    7,   11,    2,    5,    1],
       [   0, 2607,   12,    2,    2,    2,    1,    8,    6,    2],
       [   6,    5, 2224,    5,    4,    1,    3,    9,    4,    0],
       [   2,    4,   32, 2336,    2,   28,    1,   22,    7,    6],
       [   1,    4,   12,    0, 2175,    0,    2,   10,    3,   19],
       [   4,    0,    2,   21,    1, 1999,   26,    4,    7,    5],
       [   5,    0,    4,    1,    5,   13, 2179,    0,    4,    0],
       [   0,    5,   10,    2,    6,    5,    0, 2305,    1,    6],
       [   6,   12,   22,   12,    3,   21,   16,    8, 2128,   10],
       [   7,    7,    0,    9,   47,   16,    2,   52,   10, 2192]])>

In [39]:
model5 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'relu'),
    keras.layers.Dense(20, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model5.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model5.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.3923 - accuracy: 0.8842
Epoch 2/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1685 - accuracy: 0.9492
Epoch 3/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1255 - accuracy: 0.9613
Epoch 4/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1014 - accuracy: 0.9681
Epoch 5/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.0853 - accuracy: 0.9726


In [40]:
model5.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1181 - accuracy: 0.9658


[0.1180746853351593, 0.9657575488090515]

In [41]:
y_predict = model5.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2293,    0,    1,    1,    6,    5,   16,    4,    5,    0],
       [   0, 2596,   11,    0,    5,    1,   12,    2,   13,    2],
       [  14,    4, 2176,   10,    9,    5,   23,    8,   12,    0],
       [   1,    7,   23, 2304,    2,   62,    2,   13,   16,   10],
       [   2,    5,    1,    0, 2175,    3,    9,    4,    5,   22],
       [   9,    0,    1,   12,    4, 1979,   34,    5,   14,   11],
       [   7,    0,    0,    0,    4,    8, 2188,    0,    4,    0],
       [   2,    8,   16,    5,   11,    3,    1, 2274,    4,   16],
       [   9,    8,    9,   17,    6,   13,   32,    1, 2126,   17],
       [   9,    8,    1,    5,   79,   14,    0,   23,    5, 2198]])>

In [42]:
model6 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'tanh'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'tanh'),
    keras.layers.Dense(20, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model6.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model6.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.3811 - accuracy: 0.8994
Epoch 2/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1634 - accuracy: 0.9522
Epoch 3/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1174 - accuracy: 0.9652
Epoch 4/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.0939 - accuracy: 0.9716
Epoch 5/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.0759 - accuracy: 0.9769


In [43]:
model6.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1244 - accuracy: 0.9642


[0.12435916066169739, 0.9642423987388611]

In [44]:
y_predict = model6.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2264,    0,   15,    3,    4,    5,   14,    6,    6,   14],
       [   0, 2607,    7,    2,    3,    2,    3,    6,    9,    3],
       [   4,    5, 2195,   15,    3,    1,    8,   21,    8,    1],
       [   2,    9,   13, 2338,    5,   31,    2,   12,   12,   16],
       [   1,    2,   18,    0, 2069,    1,   11,   13,    4,  107],
       [   6,    1,    4,   33,    2, 1971,   22,    2,   12,   16],
       [   8,    0,    2,    0,    2,    7, 2186,    0,    6,    0],
       [   2,    5,    8,    3,    3,    2,    2, 2281,    3,   31],
       [   7,    8,   25,   48,    7,   19,   11,    5, 2075,   33],
       [   6,    3,    1,    9,    3,    6,    1,   20,    5, 2288]])>

In [45]:
model7 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'relu'),
    keras.layers.Dense(20, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model7.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model7.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.4780 - accuracy: 0.8755
Epoch 2/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.2007 - accuracy: 0.9391
Epoch 3/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1445 - accuracy: 0.9564
Epoch 4/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1136 - accuracy: 0.9655
Epoch 5/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.0939 - accuracy: 0.9716


In [46]:
model7.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1208 - accuracy: 0.9656


[0.12084733694791794, 0.965584397315979]

In [47]:
y_predict = model1.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2292,    0,    1,    2,    5,    7,   16,    0,    5,    3],
       [   0, 2618,    5,    3,    1,    4,    1,    4,    4,    2],
       [  13,    8, 2158,   15,   17,    4,   17,   11,   17,    1],
       [   0,    9,   16, 2345,    2,   31,    3,   12,   12,   10],
       [   2,    6,    3,    0, 2165,    2,    6,    5,    2,   35],
       [  12,    1,    2,   20,    5, 1986,   22,    1,   10,   10],
       [  12,    1,    2,    0,    6,   16, 2165,    0,    9,    0],
       [  11,   13,    9,   12,   10,    5,    0, 2249,    2,   29],
       [  12,   19,   11,   23,    9,   25,   20,    2, 2106,   11],
       [   6,    8,    0,   14,   35,   18,    2,   18,    9, 2232]])>

In [48]:
model8 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model8.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model8.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.4132 - accuracy: 0.8856
Epoch 2/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1858 - accuracy: 0.9436
Epoch 3/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1368 - accuracy: 0.9586
Epoch 4/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1072 - accuracy: 0.9676
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0854 - accuracy: 0.9736


In [49]:
model8.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1069 - accuracy: 0.9671


[0.10691584646701813, 0.9670995473861694]

In [50]:
y_predict = model8.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2269,    0,    6,    2,    4,   11,   15,    2,   19,    3],
       [   0, 2602,    9,    2,    5,    3,    3,    7,    9,    2],
       [   5,    2, 2208,    8,    8,    0,    7,   17,    6,    0],
       [   2,    8,   25, 2333,    4,   19,    3,   17,   21,    8],
       [   0,    3,    5,    1, 2186,    0,    5,    4,    5,   17],
       [   5,    5,    3,   37,    5, 1954,   28,    3,   22,    7],
       [   7,    0,    2,    1,    3,    7, 2182,    0,    9,    0],
       [   0,    5,    7,    7,   16,    5,    0, 2284,    2,   14],
       [   6,   12,   11,   13,   12,    6,   20,    2, 2151,    5],
       [   6,    6,    0,   12,   85,   10,    2,   30,   20, 2171]])>

In [51]:
model9 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model9.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model9.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.4051 - accuracy: 0.8871
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1922 - accuracy: 0.9421
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1378 - accuracy: 0.9579
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1051 - accuracy: 0.9678
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0843 - accuracy: 0.9736


In [52]:
model9.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1070 - accuracy: 0.9682


[0.10700733959674835, 0.9681817889213562]

In [53]:
y_predict = model9.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2294,    0,    2,    3,    0,    7,    9,    2,    8,    6],
       [   2, 2588,   13,    8,    1,    2,    0,    8,   16,    4],
       [   8,    3, 2190,   27,    3,    0,    5,   17,    8,    0],
       [   1,    3,   10, 2378,    0,   14,    1,   11,   15,    7],
       [   3,    4,   10,    1, 2098,    1,    5,    7,   15,   82],
       [   7,    0,    3,   47,    0, 1968,   12,    2,   18,   12],
       [  10,    2,    6,    2,    4,   13, 2159,    0,   15,    0],
       [   2,    4,    6,   13,    6,    8,    0, 2255,    7,   39],
       [   8,    8,    6,   25,    3,   11,   10,    2, 2154,   11],
       [   6,    4,    0,   10,    8,    7,    1,   11,   14, 2281]])>

In [54]:
model10 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model10.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model10.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 4s 2ms/step - loss: 0.2795 - accuracy: 0.9206
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1189 - accuracy: 0.9638
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0847 - accuracy: 0.9729
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0643 - accuracy: 0.9797
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0495 - accuracy: 0.9847


In [55]:
model10.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 2ms/step - loss: 0.0904 - accuracy: 0.9735


[0.09044395387172699, 0.9734631776809692]

In [56]:
y_predict = model10.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2291,    0,    0,    3,    3,    7,    7,    2,   10,    8],
       [   0, 2606,   11,    4,    2,    2,    2,    6,    5,    4],
       [   4,    3, 2203,   21,    4,    2,    2,    6,   13,    3],
       [   1,    1,   11, 2378,    1,   19,    0,    8,   12,    9],
       [   2,    6,    3,    0, 2141,    1,    2,    6,    2,   63],
       [   3,    1,    2,   22,    0, 2002,   14,    1,   11,   13],
       [  10,    4,    0,    0,    5,   10, 2175,    0,    7,    0],
       [   5,    4,    8,    6,    6,    2,    0, 2263,    4,   42],
       [   8,    8,    7,   21,    6,   18,    7,    3, 2139,   21],
       [   6,    2,    0,   10,   12,    8,    1,    9,    5, 2289]])>

In [57]:
model11 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'sigmoid'),
    keras.layers.Dense(40, activation = 'sigmoid'),
    keras.layers.Dense(10, activation = 'softmax')
])

model11.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model11.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 4s 2ms/step - loss: 0.8930 - accuracy: 0.7678
Epoch 2/5
1466/1466 [==============================] - 5s 3ms/step - loss: 0.2758 - accuracy: 0.9255
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1829 - accuracy: 0.9473
Epoch 4/5
1466/1466 [==============================] - 4s 2ms/step - loss: 0.1387 - accuracy: 0.9603
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1121 - accuracy: 0.9669


In [58]:
model11.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1280 - accuracy: 0.9640


[0.12804490327835083, 0.9640259742736816]

In [59]:
y_predict = model11.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2286,    0,    1,    3,    0,    9,    9,    7,   10,    6],
       [   0, 2585,   14,    6,    3,    2,    1,    8,   16,    7],
       [   3,    5, 2169,   20,    3,    3,    6,   32,   19,    1],
       [   3,    4,   21, 2320,    0,   39,    1,   17,   24,   11],
       [   0,    6,    7,    0, 2115,    1,    9,   11,    4,   73],
       [  14,    0,    3,   27,    3, 1962,   19,    5,   16,   20],
       [   9,    5,    8,    1,   10,   19, 2153,    0,    6,    0],
       [   4,    5,    7,    6,    6,    2,    0, 2278,    2,   30],
       [   5,    7,   10,   16,    6,   17,    4,    4, 2144,   25],
       [   6,    3,    0,    8,   15,    9,    1,   30,   13, 2257]])>

In [60]:
model12 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'relu'),
    keras.layers.Dense(40, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model12.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model12.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.3173 - accuracy: 0.9061
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1389 - accuracy: 0.9572
Epoch 3/5
1466/1466 [==============================] - 4s 2ms/step - loss: 0.1015 - accuracy: 0.9683
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0804 - accuracy: 0.9748
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0684 - accuracy: 0.9783


In [61]:
model12.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 2ms/step - loss: 0.1100 - accuracy: 0.9681


[0.10999144613742828, 0.9680952429771423]

In [62]:
y_predict = model12.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2284,    0,    3,    2,    2,    4,   21,    2,    8,    5],
       [   0, 2610,   14,    0,    1,    2,    5,    4,    6,    0],
       [   6,    3, 2198,    9,    1,    1,   14,    5,   22,    2],
       [   1,   11,   17, 2312,    0,   28,    7,    9,   48,    7],
       [   0,    9,   11,    1, 2168,    0,   13,    6,    4,   14],
       [   4,    2,    1,   24,    0, 1969,   33,    7,   22,    7],
       [   2,    1,    0,    1,    0,    6, 2199,    0,    2,    0],
       [   6,   10,   14,    5,   10,    1,    0, 2266,    3,   25],
       [   6,   25,   11,   10,    5,    7,   31,    1, 2135,    7],
       [   5,   11,    0,   10,   54,   10,    1,   17,   12, 2222]])>

In [63]:
model13 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'tanh'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'tanh'),
    keras.layers.Dense(40, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model13.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model13.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.3252 - accuracy: 0.9078
Epoch 2/5
1466/1466 [==============================] - 4s 3ms/step - loss: 0.1472 - accuracy: 0.9553
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1063 - accuracy: 0.9675
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0829 - accuracy: 0.9748
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0670 - accuracy: 0.9794


In [64]:
model13.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 2ms/step - loss: 0.1126 - accuracy: 0.9678


[0.11257725954055786, 0.9677922129631042]

In [65]:
y_predict = model13.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2252,    0,   11,    2,    2,   22,    8,    2,   24,    8],
       [   0, 2603,    9,    3,    3,    3,    2,    6,   10,    3],
       [   3,    2, 2187,   25,    8,    2,    6,   19,    8,    1],
       [   3,    6,    7, 2366,    2,   28,    0,   14,    8,    6],
       [   1,    3,    6,    0, 2163,    1,    4,    9,    4,   35],
       [   5,    1,    1,   34,    2, 1987,    7,    4,   24,    4],
       [   8,    1,    3,    0,    8,   25, 2151,    2,   13,    0],
       [   2,    1,    9,    7,    8,    6,    0, 2287,    4,   16],
       [   3,    8,   12,   41,    5,   32,    3,    3, 2113,   18],
       [   4,    4,    1,   18,   23,   13,    1,   24,    7, 2247]])>

In [66]:
model14 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'relu'),
    keras.layers.Dense(40, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model14.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model14.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 4s 3ms/step - loss: 0.4340 - accuracy: 0.8772
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1858 - accuracy: 0.9437
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1390 - accuracy: 0.9570
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1099 - accuracy: 0.9660
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0900 - accuracy: 0.9723


In [67]:
model14.evaluate(X_testf, y_test)

722/722 [==============================] - 2s 2ms/step - loss: 0.1139 - accuracy: 0.9662


[0.11393807083368301, 0.9662337899208069]

In [68]:
y_predict = model14.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2295,    0,    4,    3,    0,    8,   11,    0,    6,    4],
       [   0, 2605,    7,    4,    1,    4,    3,    7,    9,    2],
       [   8,    3, 2183,   29,    2,    3,   11,   14,    6,    2],
       [   0,    4,   10, 2352,    0,   44,    2,   13,   10,    5],
       [   5,    5,   20,    1, 2113,    0,   18,    7,    4,   53],
       [  10,    0,    1,   19,    1, 2003,   23,    1,    8,    3],
       [  11,    0,    1,    0,    2,   13, 2179,    0,    5,    0],
       [   6,    7,    9,   11,    8,    5,    0, 2275,    1,   18],
       [  10,   12,   13,   42,    1,   28,   20,    2, 2096,   14],
       [  11,    7,    1,   29,   24,   19,    0,   20,   12, 2219]])>

In [69]:
model15 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model15.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model15.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.4742 - accuracy: 0.8711
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.2041 - accuracy: 0.9394
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1531 - accuracy: 0.9550
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1232 - accuracy: 0.9621
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1016 - accuracy: 0.9696


In [70]:
model15.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 2ms/step - loss: 0.1151 - accuracy: 0.9665


[0.11510258167982101, 0.966536819934845]

In [71]:
y_predict = model15.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2295,    0,    2,    2,    0,   10,   10,    3,    7,    2],
       [   0, 2596,    9,    5,    3,    8,    3,    6,    8,    4],
       [  13,    7, 2183,   12,    6,    2,   13,   15,   10,    0],
       [   3,    4,   20, 2305,    1,   65,    4,   14,   14,   10],
       [   5,    6,    6,    0, 2134,    1,    6,    6,    6,   56],
       [  10,    0,    2,   21,    3, 1979,   24,    2,   17,   11],
       [   9,    1,    2,    0,    4,   11, 2176,    0,    8,    0],
       [   3,    7,   11,   10,    8,    7,    0, 2272,    3,   19],
       [   7,   15,   13,   17,    1,   16,   17,    3, 2135,   14],
       [   8,    3,    0,   10,   21,   11,    2,   25,   10, 2252]])>