In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras

In [2]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()


In [3]:
x_train2 = x_train.reshape(len(x_train), 28 * 28)
df1 = pd.DataFrame(x_train2)


In [4]:
df1

0    1    2    3    4    5    6    7    8    9    ...  774  775  776  \
0        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
2        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
3        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
4        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
59995    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59996    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59997    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59998    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59999    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   

       777  778  779  780  781  782  783  
0        0    0    0    0    0    0    0  
1        0    0    0    0    0    0    0  
2        0    0    0    0    0    0    0  
3        0    0    0    0    0    0    0  
4        0    0    0    0    0    0    0  
...    ...  ...  ...  ...  ...  ...  ...  
59995    0    0    0    0    0    0    0  
59996    0    0    0    0    0    0    0  
59997    0    0    0    0    0    0    0  
59998    0    0    0    0    0    0    0  
59999    0    0    0    0    0    0    0  

[60000 rows x 784 columns]

In [5]:
df1_target = pd.DataFrame(y_train)

In [6]:
df1_target

0
0      5
1      0
2      4
3      1
4      9
...   ..
59995  8
59996  3
59997  5
59998  6
59999  8

[60000 rows x 1 columns]

In [7]:
df1['target'] = df1_target[0]
df1.head()

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  782  \
0  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
1  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
2  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
3  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
4  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   

   783  target  
0    0       5  
1    0       0  
2    0       4  
3    0       1  
4    0       9  

[5 rows x 785 columns]

# We did the merging for X_train and y_train, now lets do it for X_test and y_test

In [8]:
x_test2 = x_test.reshape(len(x_test), 28 * 28)
df2 = pd.DataFrame(x_test2)
df2_target = pd.DataFrame(y_test)
df2['target'] = df2_target[0]
df2.head()

##MERGING HAS BEEN DONE. WE NOW HAVE DF1 and DF2

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  782  \
0  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
1  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
2  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
3  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
4  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   

   783  target  
0    0       7  
1    0       2  
2    0       1  
3    0       0  
4    0       4  

[5 rows x 785 columns]

In [9]:
##NOW GETTING THE DF IN WHICH WE WILL MERGE ALL OF THESE
df3 = pd.concat([df1, df2], ignore_index = True)
df3

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  \
0      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
1      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
2      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
3      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
4      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
...   .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
69995  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69996  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69997  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69998  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69999  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   

       782  783  target  
0        0    0       5  
1        0    0       0  
2        0    0       4  
3        0    0       1  
4        0    0       9  
...    ...  ...     ...  
69995    0    0       2  
69996    0    0       3  
69997    0    0       4  
69998    0    0       5  
69999    0    0       6  

[70000 rows x 785 columns]

In [10]:
# y = df3['target']
# y = pd.DataFrame(y)
# y.head()
df_train = df3.sample(frac=0.67,random_state=6)
df_test = df3.drop(df_train.index)
df_train

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  \
2294   0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
42341  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
45427  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
47574  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
49490  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
...   .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
3264   0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
64875  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
17478  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
48812  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
35109  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   

       782  783  target  
2294     0    0       4  
42341    0    0       2  
45427    0    0       8  
47574    0    0       6  
49490    0    0       5  
...    ...  ...     ...  
3264     0    0       3  
64875    0    0       6  
17478    0    0       4  
48812    0    0       5  
35109    0    0       1  

[46900 rows x 785 columns]

In [11]:
y_train = df_train['target']
y_train = pd.DataFrame(y_train)
y_train.head()
# df_train = df_train.drop('target', axis = 1, inplace = True)
# df_train.head()

target
2294        4
42341       2
45427       8
47574       6
49490       5

In [12]:
df_train = df_train.drop('target', axis=1)


In [13]:
df_train.head()
df_test

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  \
0      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
3      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
5      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
6      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
10     0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
...   .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
69981  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69985  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69987  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69995  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69996  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   

       782  783  target  
0        0    0       5  
3        0    0       1  
5        0    0       2  
6        0    0       1  
10       0    0       3  
...    ...  ...     ...  
69981    0    0       6  
69985    0    0       2  
69987    0    0       4  
69995    0    0       2  
69996    0    0       3  

[23100 rows x 785 columns]

In [14]:
y_test = df_test['target']
y_test = pd.DataFrame(y_test)
y_test.head()

target
0        5
3        1
5        2
6        1
10       3

In [15]:
df_test = df_test.drop('target', axis=1)


In [16]:
df_test.head()

0    1    2    3    4    5    6    7    8    9    ...  774  775  776  777  \
0     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
3     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
5     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
6     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
10    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   

    778  779  780  781  782  783  
0     0    0    0    0    0    0  
3     0    0    0    0    0    0  
5     0    0    0    0    0    0  
6     0    0    0    0    0    0  
10    0    0    0    0    0    0  

[5 rows x 784 columns]

# Converting these into NumPy arrays for use in the ANN model

In [17]:
x_train = df_train.to_numpy()
x_train
x_test = df_test.to_numpy()
y_train = y_train.to_numpy()
y_test = y_test.to_numpy()

# Performing the required pre-processing

In [18]:
x_train = x_train/255
x_test = x_test/255

In [19]:
#x_train[0]

In [20]:
X_trainf = x_train.reshape(len(x_train), 28 * 28)
#we choose to flatten the data in order to make the first input layer of the neural network have 784 values, since we currently have values stored in 28*28 form

In [21]:
X_testf = x_test.reshape(len(x_test), 28*28)

# MODEL 1 -- 150 neurons, 2 layers, sigmoid

In [22]:
model1 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'sigmoid'),
    keras.layers.Dense(10, activation = 'softmax')
])

model1.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model1.fit(X_trainf, y_train, epochs = 5)



Epoch 1/5
1466/1466 [==============================] - 4s 2ms/step - loss: 0.5894 - accuracy: 0.8535
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.2207 - accuracy: 0.9360
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1613 - accuracy: 0.9528
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1265 - accuracy: 0.9626
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1023 - accuracy: 0.9699


In [23]:
model1.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1205 - accuracy: 0.9637


[0.1204783171415329, 0.9636796712875366]

In [24]:
y_predict = model1.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2326,    1,    7,    3,    3,    2,   12,    4,    5,    1],
       [   0, 2527,   13,    1,    3,    2,    5,    4,    6,    4],
       [   5,    3, 2223,   13,   15,    2,    7,   20,   12,    1],
       [   4,    2,   24, 2197,    4,   36,    3,   26,   25,    5],
       [   1,    2,    9,    1, 2251,    1,    9,    6,    5,   21],
       [  15,    0,    5,   31,    7, 1988,   23,    5,   17,    4],
       [  13,    0,    3,    0,    8,    8, 2189,    1,    7,    0],
       [   3,   15,   13,    2,   11,    1,    2, 2311,    5,    9],
       [  14,   13,   21,   18,    7,   15,   14,    7, 2123,   14],
       [  10,    5,    0,   17,   79,   13,    1,   34,   11, 2126]])>

# MODEL 2 -- 100 Neurons, 3 Hidden Layers

In [25]:
model2 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'sigmoid'),
    keras.layers.Dense(20, activation = 'sigmoid'),
    keras.layers.Dense(10, activation = 'softmax')
])

model2.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model2.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 1.1074 - accuracy: 0.7304
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.3644 - accuracy: 0.9134
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.2350 - accuracy: 0.9383
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1784 - accuracy: 0.9514
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1452 - accuracy: 0.9591


In [26]:
model2.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 2ms/step - loss: 0.1659 - accuracy: 0.9535


[0.16587020456790924, 0.9535064697265625]

In [27]:
y_predict = model2.predict(X_testf)

722/722 [==============================] - 1s 1ms/step


In [28]:
y_predict[0]

array([1.5186167e-02, 3.1287447e-05, 8.2355073e-05, 5.3217481e-03,
       3.3029576e-06, 9.7446698e-01, 7.8936975e-04, 9.8797915e-05,
       1.5988101e-03, 2.4213549e-03], dtype=float32)

In [29]:
np.argmax(y_predict[0]) #gives the maximum value out of the given ones

5

In [30]:
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array

In [31]:
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices


In [32]:
cm #this is the confusion matrix, we are supposed to do this for all 15 of the models. Preferable if we beautify this a bit using matPlotLib, or seaborn if permitted by sir

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2307,    2,    1,    5,    4,   19,    8,    7,    5,    6],
       [   0, 2513,   17,    4,    5,    2,    5,    5,   10,    4],
       [   6,   10, 2178,   15,   31,    6,    8,   22,   23,    2],
       [   6,    5,   22, 2153,    3,   47,    1,   21,   51,   17],
       [   1,    2,   12,    0, 2227,    0,    5,    5,    4,   50],
       [  17,    0,    4,   27,    5, 1990,   21,    1,   16,   14],
       [  14,    1,    2,    0,   20,   26, 2156,    0,    9,    1],
       [   6,   20,   12,    8,    9,    0,    0, 2266,    4,   47],
       [   5,   11,   24,   23,   19,   38,   16,    4, 2073,   33],
       [  10,    4,    0,   16,   52,    7,    1,   32,   11, 2163]])>

# MODEL 3 -- 150 Neurons, 2 Hidden Layers, ReLU

In [33]:
model3 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model3.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model3.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 4s 2ms/step - loss: 0.2965 - accuracy: 0.9141
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1263 - accuracy: 0.9614
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0886 - accuracy: 0.9728
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0687 - accuracy: 0.9782
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0566 - accuracy: 0.9823


In [34]:
model3.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 2ms/step - loss: 0.1055 - accuracy: 0.9692


[0.10547981411218643, 0.969220757484436]

In [35]:
y_predict = model3.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 2ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2318,    4,    2,    2,    1,    2,   22,    1,    9,    3],
       [   0, 2536,    8,    1,    6,    2,    2,    3,    6,    1],
       [   7,    6, 2185,   58,    6,    3,    4,   16,   14,    2],
       [   1,    1,   10, 2257,    0,   29,    2,    4,   19,    3],
       [   1,    0,    5,    0, 2260,    2,    7,    6,    3,   22],
       [   2,    1,    0,   27,    2, 2031,   15,    0,   12,    5],
       [   3,    5,    1,    1,    4,   13, 2198,    0,    4,    0],
       [   2,   17,   11,   15,    9,    1,    0, 2226,   14,   77],
       [   8,    9,    1,   12,    9,   16,    9,    3, 2169,   10],
       [  10,    2,    0,   13,   39,    7,    0,    5,   11, 2209]])>

In [36]:
model4 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'tanh'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model4.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model4.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 4s 2ms/step - loss: 0.3039 - accuracy: 0.9116
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1417 - accuracy: 0.9578
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0976 - accuracy: 0.9707
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0726 - accuracy: 0.9778
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0573 - accuracy: 0.9816


In [37]:
model4.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.0959 - accuracy: 0.9725


[0.09593110531568527, 0.9724675416946411]

In [38]:
y_predict = model4.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2340,    0,    2,    2,    4,    1,    4,    4,    5,    2],
       [   0, 2541,    7,    0,    3,    0,    1,    6,    5,    2],
       [   8,    4, 2217,   18,   10,    2,    6,   24,   11,    1],
       [   5,    4,   10, 2220,    1,   27,    1,   25,   23,   10],
       [   1,    1,    8,    0, 2238,    2,    7,   17,    4,   28],
       [   6,    2,    2,   31,    3, 2016,   25,    0,    7,    3],
       [  16,    4,    0,    0,    5,    4, 2192,    1,    7,    0],
       [   3,    4,    5,    3,    8,    0,    1, 2332,    6,   10],
       [  19,   10,    6,    8,    5,    7,    8,   11, 2165,    7],
       [  10,    2,    3,    8,   22,    7,    0,   32,    9, 2203]])>

In [39]:
model5 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'relu'),
    keras.layers.Dense(20, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model5.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model5.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.3712 - accuracy: 0.8873
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1568 - accuracy: 0.9535
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1186 - accuracy: 0.9642
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0948 - accuracy: 0.9718
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0818 - accuracy: 0.9747


In [40]:
model5.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1208 - accuracy: 0.9656


[0.12076117098331451, 0.965584397315979]

In [41]:
y_predict = model5.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2338,    2,    6,    1,    1,    3,    3,    2,    5,    3],
       [   0, 2517,   11,    3,    3,    1,    8,    7,   14,    1],
       [  10,    4, 2250,    4,    3,    0,    5,   17,    8,    0],
       [   4,    3,   41, 2196,    0,   30,    1,   24,   22,    5],
       [   1,    5,   14,    0, 2174,    6,    9,   26,   16,   55],
       [   6,    0,    7,   23,    0, 2009,   18,    3,   21,    8],
       [  23,    2,    1,    0,    3,    4, 2188,    0,    8,    0],
       [   1,    6,   12,    3,    3,    0,    1, 2331,    7,    8],
       [  17,    5,   20,    3,    2,   18,   12,    5, 2156,    8],
       [   6,    4,    7,   20,   23,   15,    0,   53,   22, 2146]])>

In [42]:
model6 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'tanh'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'tanh'),
    keras.layers.Dense(20, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model6.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model6.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.3861 - accuracy: 0.8981
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1673 - accuracy: 0.9513
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1203 - accuracy: 0.9640
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0949 - accuracy: 0.9716
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0766 - accuracy: 0.9768


In [43]:
model6.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 2ms/step - loss: 0.1541 - accuracy: 0.9552


[0.15410082042217255, 0.9551514983177185]

In [44]:
y_predict = model6.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2324,    2,    8,   12,    3,    0,    4,    1,    9,    1],
       [   0, 2539,   10,    5,    2,    0,    1,    2,    6,    0],
       [   8,   14, 2189,   37,    9,    0,    5,   19,   16,    4],
       [   1,    3,   12, 2270,    2,    4,    0,   14,   15,    5],
       [   2,    1,   26,   11, 2188,    2,   17,   12,    4,   43],
       [  20,    7,    4,  148,    7, 1843,   20,    3,   34,    9],
       [  12,    6,   11,    6,    3,    3, 2170,    0,   17,    1],
       [   7,   14,    6,   26,    6,    1,    1, 2278,    2,   31],
       [  15,   24,   12,   76,    5,    4,    6,    5, 2084,   15],
       [  12,    5,    0,   30,   30,    9,    2,   20,    9, 2179]])>

In [45]:
model7 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'relu'),
    keras.layers.Dense(20, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model7.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model7.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.4924 - accuracy: 0.8683
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1981 - accuracy: 0.9424
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1475 - accuracy: 0.9567
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1187 - accuracy: 0.9642
Epoch 5/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.0987 - accuracy: 0.9702


In [46]:
model7.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1182 - accuracy: 0.9646


[0.1181737408041954, 0.9645887613296509]

In [47]:
y_predict = model1.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2326,    1,    7,    3,    3,    2,   12,    4,    5,    1],
       [   0, 2527,   13,    1,    3,    2,    5,    4,    6,    4],
       [   5,    3, 2223,   13,   15,    2,    7,   20,   12,    1],
       [   4,    2,   24, 2197,    4,   36,    3,   26,   25,    5],
       [   1,    2,    9,    1, 2251,    1,    9,    6,    5,   21],
       [  15,    0,    5,   31,    7, 1988,   23,    5,   17,    4],
       [  13,    0,    3,    0,    8,    8, 2189,    1,    7,    0],
       [   3,   15,   13,    2,   11,    1,    2, 2311,    5,    9],
       [  14,   13,   21,   18,    7,   15,   14,    7, 2123,   14],
       [  10,    5,    0,   17,   79,   13,    1,   34,   11, 2126]])>

In [48]:
model8 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model8.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model8.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.4222 - accuracy: 0.8845
Epoch 2/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1877 - accuracy: 0.9435
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1370 - accuracy: 0.9586
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1088 - accuracy: 0.9671
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0854 - accuracy: 0.9749


In [49]:
model8.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1100 - accuracy: 0.9667


[0.11000808328390121, 0.9666666388511658]

In [50]:
y_predict = model8.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2328,    1,    4,    3,    6,    2,    4,    2,    9,    5],
       [   0, 2526,    9,    3,    3,    2,    2,    6,   11,    3],
       [   8,    2, 2222,   15,   12,    1,    4,   22,   13,    2],
       [   6,    0,   19, 2207,    2,   26,    0,   23,   29,   14],
       [   1,    2,    8,    0, 2181,    1,    4,   10,    4,   95],
       [   8,    0,    3,   24,    4, 2013,   11,    4,   14,   14],
       [  15,    5,    4,    0,   11,   12, 2167,    1,   14,    0],
       [   3,   10,    9,    2,    5,    1,    1, 2309,    5,   27],
       [   8,    9,   13,   15,    7,   14,    5,    6, 2143,   26],
       [   3,    4,    1,    8,   19,    4,    0,   17,    6, 2234]])>

In [51]:
model9 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model9.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model9.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.3959 - accuracy: 0.8901
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1817 - accuracy: 0.9456
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1280 - accuracy: 0.9603
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0957 - accuracy: 0.9713
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0764 - accuracy: 0.9768


In [52]:
model9.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 2ms/step - loss: 0.1132 - accuracy: 0.9655


[0.1131664291024208, 0.9654545187950134]

In [53]:
y_predict = model9.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2322,    1,    7,    2,    7,    4,   14,    1,    5,    1],
       [   0, 2543,    4,    2,    4,    3,    6,    0,    2,    1],
       [   4,    5, 2234,   16,   12,    2,    4,   20,    4,    0],
       [   3,    5,   11, 2229,    4,   46,    1,   16,    8,    3],
       [   1,    3,    6,    1, 2262,    2,    6,    7,    2,   16],
       [   5,    0,    1,   18,    7, 2036,   19,    2,    5,    2],
       [   5,    3,    0,    0,    7,   10, 2200,    1,    3,    0],
       [   2,   24,    8,    9,   10,    3,    1, 2302,    5,    8],
       [  13,   15,   20,   29,    8,   38,   20,    8, 2088,    7],
       [   9,    5,    0,   21,   95,   21,    1,   51,    7, 2086]])>

In [54]:
model10 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model10.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model10.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.2826 - accuracy: 0.9172
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1220 - accuracy: 0.9628
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0856 - accuracy: 0.9736
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0647 - accuracy: 0.9791
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0502 - accuracy: 0.9839


In [55]:
model10.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.0988 - accuracy: 0.9706


[0.09884919226169586, 0.970562756061554]

In [56]:
y_predict = model10.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2313,    4,    4,    0,    4,    4,   15,    1,    9,   10],
       [   0, 2539,    8,    4,    4,    0,    4,    0,    4,    2],
       [   2,    4, 2240,   20,    5,    0,    2,   13,   12,    3],
       [   1,    1,   18, 2221,    1,   34,    3,    7,   26,   14],
       [   0,    1,    4,    1, 2230,    1,    5,    6,    5,   53],
       [   3,    1,    3,   21,    3, 2012,   19,    0,   16,   17],
       [   2,    0,    0,    0,   10,    8, 2189,    0,   20,    0],
       [   1,   16,    7,   24,    6,    1,    3, 2266,    6,   42],
       [   6,   12,   13,   10,    2,    7,    8,    4, 2163,   21],
       [   2,    2,    1,    3,   23,    4,    1,    8,    5, 2247]])>

In [57]:
model11 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'sigmoid'),
    keras.layers.Dense(40, activation = 'sigmoid'),
    keras.layers.Dense(10, activation = 'softmax')
])

model11.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model11.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.8063 - accuracy: 0.7999
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.2548 - accuracy: 0.9288
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1775 - accuracy: 0.9493
Epoch 4/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1387 - accuracy: 0.9600
Epoch 5/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1137 - accuracy: 0.9675


In [58]:
model11.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1353 - accuracy: 0.9601


[0.13529349863529205, 0.9600865840911865]

In [59]:
y_predict = model11.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2330,    0,    5,    0,    7,    3,    4,    1,    9,    5],
       [   0, 2497,    8,    4,    3,    2,    5,    7,   33,    6],
       [  15,    1, 2192,   19,   14,    1,    9,   23,   23,    4],
       [   4,    2,   14, 2197,    2,   28,    0,   28,   40,   11],
       [   5,    2,    5,    0, 2239,    2,   12,    5,    4,   32],
       [  16,    0,    3,   32,    9, 1983,   18,    0,   25,    9],
       [  14,    1,    3,    0,   17,    8, 2172,    0,   14,    0],
       [   1,   10,    7,    7,   11,    4,    0, 2261,    7,   64],
       [   8,    6,    8,   16,   11,    9,   12,    3, 2154,   19],
       [   6,    2,    0,    6,   81,   14,    1,   20,   13, 2153]])>

In [60]:
model12 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'relu'),
    keras.layers.Dense(40, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model12.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model12.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.3209 - accuracy: 0.9053
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1408 - accuracy: 0.9568
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1022 - accuracy: 0.9685
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0811 - accuracy: 0.9749
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0680 - accuracy: 0.9792


In [61]:
model12.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1140 - accuracy: 0.9681


[0.1139836460351944, 0.9680952429771423]

In [62]:
y_predict = model12.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2342,    0,    2,    0,    3,    1,    6,    3,    5,    2],
       [   0, 2516,   21,    1,    7,    0,    5,    7,    7,    1],
       [   9,    0, 2240,    3,   12,    3,    2,   21,    7,    4],
       [   7,    2,   41, 2169,    1,   46,    1,   22,   26,   11],
       [   1,    2,    4,    0, 2259,    0,    3,   10,    0,   27],
       [   8,    1,    3,   11,    7, 2022,   20,    0,   12,   11],
       [  20,    1,    4,    0,   12,    7, 2181,    0,    4,    0],
       [   0,    5,    6,    1,    9,    2,    0, 2337,    4,    8],
       [  17,    7,   22,   15,   11,   20,   18,    9, 2105,   22],
       [   7,    3,    0,    6,   46,   12,    0,   25,    5, 2192]])>

In [63]:
model13 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'tanh'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'tanh'),
    keras.layers.Dense(40, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model13.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model13.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.3195 - accuracy: 0.9094
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1411 - accuracy: 0.9576
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1031 - accuracy: 0.9689
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0812 - accuracy: 0.9744
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0630 - accuracy: 0.9800


In [64]:
model13.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1066 - accuracy: 0.9699


[0.1066049113869667, 0.9699134230613708]

In [65]:
y_predict = model13.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2340,    0,    7,    0,    2,    0,    5,    3,    4,    3],
       [   0, 2529,   10,    3,    7,    0,    4,    4,    4,    4],
       [   8,    3, 2222,   26,    9,    1,    4,   20,    6,    2],
       [   6,    2,   12, 2243,    4,   10,    2,   16,   19,   12],
       [   3,    1,    9,    0, 2260,    0,    1,    6,    3,   23],
       [  12,    0,    4,   42,   11, 1952,   22,    2,   29,   21],
       [  12,    0,    2,    1,   13,    3, 2196,    0,    2,    0],
       [   3,    6,    9,    5,    5,    0,    1, 2318,    5,   20],
       [  15,    6,   12,   20,   10,    9,   10,    8, 2145,   11],
       [   3,    2,    0,    9,   56,    1,    1,   19,    5, 2200]])>

In [66]:
model14 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'relu'),
    keras.layers.Dense(40, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model14.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model14.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.4155 - accuracy: 0.8819
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1829 - accuracy: 0.9439
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1353 - accuracy: 0.9578
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1057 - accuracy: 0.9675
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0865 - accuracy: 0.9737


In [67]:
model14.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1181 - accuracy: 0.9647


[0.11808064579963684, 0.9647186398506165]

In [68]:
y_predict = model14.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2328,    0,    4,    1,    4,    1,    5,    1,   11,    9],
       [   0, 2493,   14,    5,    4,    1,    3,    8,   30,    7],
       [   5,    4, 2193,   17,   15,    2,    3,   42,   16,    4],
       [   1,    0,   10, 2239,    3,   23,    0,   15,   20,   15],
       [   1,    1,    5,    2, 2215,    2,    2,   14,    5,   59],
       [   6,    0,    5,   39,    4, 1992,    8,    4,   15,   22],
       [  15,    3,    4,    2,   14,   20, 2152,    4,   15,    0],
       [   1,    3,    6,   10,    7,    0,    0, 2302,   11,   32],
       [   7,    4,   13,   26,    6,    9,    4,    6, 2138,   33],
       [   2,    2,    0,    8,   24,    5,    1,   13,    8, 2233]])>

In [69]:
model15 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model15.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model15.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.4503 - accuracy: 0.8788
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.2043 - accuracy: 0.9390
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1505 - accuracy: 0.9547
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1206 - accuracy: 0.9631
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0986 - accuracy: 0.9708


In [70]:
model15.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 2ms/step - loss: 0.1232 - accuracy: 0.9628


[0.12323790788650513, 0.9628138542175293]

In [71]:
y_predict = model15.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2296,    1,    5,    1,    5,   27,   15,    2,    9,    3],
       [   0, 2531,   10,    1,    4,    5,    4,    1,    7,    2],
       [   8,    6, 2192,   18,   22,    7,    8,   21,   17,    2],
       [   2,    3,   16, 2210,    2,   61,    1,   10,   16,    5],
       [   0,    2,    8,    0, 2221,    7,    7,    9,    3,   49],
       [   2,    0,    3,   20,    5, 2039,   15,    0,    6,    5],
       [   5,    0,    3,    1,    9,   15, 2186,    3,    7,    0],
       [   1,   17,    9,   17,   15,    6,    0, 2275,    7,   25],
       [   5,   15,    7,   28,   11,   41,   12,    6, 2106,   15],
       [   3,    5,    0,   17,   38,   25,    1,   15,    7, 2185]])>