In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras

In [2]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()


In [3]:
x_train2 = x_train.reshape(len(x_train), 28 * 28)
df1 = pd.DataFrame(x_train2)


In [4]:
df1

0    1    2    3    4    5    6    7    8    9    ...  774  775  776  \
0        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
2        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
3        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
4        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
59995    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59996    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59997    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59998    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59999    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   

       777  778  779  780  781  782  783  
0        0    0    0    0    0    0    0  
1        0    0    0    0    0    0    0  
2        0    0    0    0    0    0    0  
3        0    0    0    0    0    0    0  
4        0    0    0    0    0    0    0  
...    ...  ...  ...  ...  ...  ...  ...  
59995    0    0    0    0    0    0    0  
59996    0    0    0    0    0    0    0  
59997    0    0    0    0    0    0    0  
59998    0    0    0    0    0    0    0  
59999    0    0    0    0    0    0    0  

[60000 rows x 784 columns]

In [5]:
df1_target = pd.DataFrame(y_train)

In [6]:
df1_target

0
0      5
1      0
2      4
3      1
4      9
...   ..
59995  8
59996  3
59997  5
59998  6
59999  8

[60000 rows x 1 columns]

In [7]:
df1['target'] = df1_target[0]
df1.head()

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  782  \
0  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
1  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
2  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
3  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
4  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   

   783  target  
0    0       5  
1    0       0  
2    0       4  
3    0       1  
4    0       9  

[5 rows x 785 columns]

# We did the merging for X_train and y_train, now lets do it for X_test and y_test

In [8]:
x_test2 = x_test.reshape(len(x_test), 28 * 28)
df2 = pd.DataFrame(x_test2)
df2_target = pd.DataFrame(y_test)
df2['target'] = df2_target[0]
df2.head()

##MERGING HAS BEEN DONE. WE NOW HAVE DF1 and DF2

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  782  \
0  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
1  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
2  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
3  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
4  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   

   783  target  
0    0       7  
1    0       2  
2    0       1  
3    0       0  
4    0       4  

[5 rows x 785 columns]

In [9]:
##NOW GETTING THE DF IN WHICH WE WILL MERGE ALL OF THESE
df3 = pd.concat([df1, df2], ignore_index = True)
df3

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  \
0      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
1      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
2      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
3      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
4      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
...   .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
69995  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69996  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69997  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69998  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69999  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   

       782  783  target  
0        0    0       5  
1        0    0       0  
2        0    0       4  
3        0    0       1  
4        0    0       9  
...    ...  ...     ...  
69995    0    0       2  
69996    0    0       3  
69997    0    0       4  
69998    0    0       5  
69999    0    0       6  

[70000 rows x 785 columns]

In [10]:
# y = df3['target']
# y = pd.DataFrame(y)
# y.head()
df_train = df3.sample(frac=0.67,random_state=5)
df_test = df3.drop(df_train.index)
df_train

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  \
6628   0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
2777   0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
7414   0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
63950  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
44249  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
...   .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
67428  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
53945  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
68902  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
6719   0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
53043  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   

       782  783  target  
6628     0    0       2  
2777     0    0       6  
7414     0    0       2  
63950    0    0       9  
44249    0    0       3  
...    ...  ...     ...  
67428    0    0       8  
53945    0    0       4  
68902    0    0       2  
6719     0    0       3  
53043    0    0       8  

[46900 rows x 785 columns]

In [11]:
y_train = df_train['target']
y_train = pd.DataFrame(y_train)
y_train.head()
# df_train = df_train.drop('target', axis = 1, inplace = True)
# df_train.head()

target
6628        2
2777        6
7414        2
63950       9
44249       3

In [12]:
df_train = df_train.drop('target', axis=1)


In [13]:
df_train.head()
df_test

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  \
0      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
2      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
4      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
10     0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
11     0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
...   .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
69991  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69993  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69994  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69995  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69996  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   

       782  783  target  
0        0    0       5  
2        0    0       4  
4        0    0       9  
10       0    0       3  
11       0    0       5  
...    ...  ...     ...  
69991    0    0       8  
69993    0    0       0  
69994    0    0       1  
69995    0    0       2  
69996    0    0       3  

[23100 rows x 785 columns]

In [14]:
y_test = df_test['target']
y_test = pd.DataFrame(y_test)
y_test.head()

target
0        5
2        4
4        9
10       3
11       5

In [15]:
df_test = df_test.drop('target', axis=1)


In [16]:
df_test.head()

0    1    2    3    4    5    6    7    8    9    ...  774  775  776  777  \
0     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
2     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
4     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
10    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
11    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   

    778  779  780  781  782  783  
0     0    0    0    0    0    0  
2     0    0    0    0    0    0  
4     0    0    0    0    0    0  
10    0    0    0    0    0    0  
11    0    0    0    0    0    0  

[5 rows x 784 columns]

# Converting these into NumPy arrays for use in the ANN model

In [17]:
x_train = df_train.to_numpy()
x_train
x_test = df_test.to_numpy()
y_train = y_train.to_numpy()
y_test = y_test.to_numpy()

# Performing the required pre-processing

In [18]:
x_train = x_train/255
x_test = x_test/255

In [19]:
#x_train[0]

In [20]:
X_trainf = x_train.reshape(len(x_train), 28 * 28)
#we choose to flatten the data in order to make the first input layer of the neural network have 784 values, since we currently have values stored in 28*28 form

In [21]:
X_testf = x_test.reshape(len(x_test), 28*28)

# MODEL 1 -- 150 neurons, 2 layers, sigmoid

In [22]:
model1 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'sigmoid'),
    keras.layers.Dense(10, activation = 'softmax')
])

model1.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model1.fit(X_trainf, y_train, epochs = 5)



Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.5650 - accuracy: 0.8607
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.2122 - accuracy: 0.9382
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1565 - accuracy: 0.9536
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1220 - accuracy: 0.9630
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0995 - accuracy: 0.9707


In [23]:
model1.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 936us/step - loss: 0.1247 - accuracy: 0.9626


[0.12465974688529968, 0.9625540971755981]

In [24]:
y_predict = model1.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 856us/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2188,    0,   10,    2,    5,   12,   21,    0,   15,    4],
       [   0, 2592,    6,    0,    2,    3,    1,    5,    7,    1],
       [   4,    1, 2235,    3,   10,    2,    3,   16,   22,    1],
       [   2,   13,   33, 2202,    1,   76,    4,   23,   27,    8],
       [   0,    7,   11,    0, 2175,    1,   15,   10,    8,   35],
       [   5,    7,    8,   11,    5, 2028,   20,    3,   12,    6],
       [  10,    5,    7,    0,    6,   13, 2254,    1,   13,    0],
       [   4,    6,   28,    1,   11,    2,    0, 2333,    2,   13],
       [   6,   17,    9,   11,    3,   14,   10,    5, 2149,    4],
       [   3,    5,    3,    6,   66,   11,    0,   42,   21, 2079]])>

# MODEL 2 -- 100 Neurons, 3 Hidden Layers

In [25]:
model2 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'sigmoid'),
    keras.layers.Dense(20, activation = 'sigmoid'),
    keras.layers.Dense(10, activation = 'softmax')
])

model2.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model2.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 1.1344 - accuracy: 0.7138
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.3287 - accuracy: 0.9188
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.2178 - accuracy: 0.9426
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1684 - accuracy: 0.9542
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1381 - accuracy: 0.9624


In [26]:
model2.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1618 - accuracy: 0.9529


[0.16182491183280945, 0.9528571367263794]

In [27]:
y_predict = model2.predict(X_testf)

722/722 [==============================] - 1s 936us/step


In [28]:
y_predict[0]

array([1.2406220e-03, 1.5482254e-04, 8.0141152e-05, 3.3101782e-02,
       6.5008127e-05, 9.5920068e-01, 2.0622700e-05, 5.7135650e-04,
       2.1515063e-03, 3.4132942e-03], dtype=float32)

In [29]:
np.argmax(y_predict[0]) #gives the maximum value out of the given ones

5

In [30]:
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array

In [31]:
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices


In [32]:
cm #this is the confusion matrix, we are supposed to do this for all 15 of the models. Preferable if we beautify this a bit using matPlotLib, or seaborn if permitted by sir

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2193,    0,    5,    3,    8,    8,   30,    4,    5,    1],
       [   0, 2553,    4,   14,    0,    2,   10,    7,   22,    5],
       [   5,    2, 2203,   20,   15,    4,    7,   16,   23,    2],
       [   4,    9,   40, 2166,    0,   68,    6,   27,   60,    9],
       [   8,    4,   10,    0, 2151,    2,   20,    5,   11,   51],
       [  16,    4,    4,   24,    8, 1982,   20,    8,   29,   10],
       [  15,    1,    8,    0,    9,    8, 2247,    1,   20,    0],
       [   7,    4,   28,   10,    6,    7,    0, 2302,    1,   35],
       [   2,   13,   10,   16,    8,   24,   10,    6, 2128,   11],
       [   5,    1,    0,   11,   62,    9,    2,   39,   21, 2086]])>

# MODEL 3 -- 150 Neurons, 2 Hidden Layers, ReLU

In [33]:
model3 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model3.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model3.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.2982 - accuracy: 0.9127
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1292 - accuracy: 0.9611
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0916 - accuracy: 0.9723
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0704 - accuracy: 0.9786
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0547 - accuracy: 0.9823


In [34]:
model3.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1037 - accuracy: 0.9712


[0.10373817384243011, 0.9711688160896301]

In [35]:
y_predict = model3.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 910us/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2221,    0,    8,    2,    1,    3,   13,    2,    6,    1],
       [   0, 2587,    3,    5,    2,    4,    0,    3,    7,    6],
       [   5,    5, 2210,    7,    5,    3,    3,   19,   38,    2],
       [   1,    6,   14, 2280,    0,   44,    3,   12,   25,    4],
       [   3,    5,    7,    1, 2157,    3,   14,   13,    7,   52],
       [   7,    1,    2,   13,    0, 2052,   11,    4,   11,    4],
       [   8,    6,    1,    0,    7,   18, 2260,    4,    5,    0],
       [   1,    5,   10,    5,    2,    2,    0, 2355,    3,   17],
       [   9,    7,    2,   13,    1,   17,    8,    3, 2156,   12],
       [   4,    0,    0,    9,   15,    9,    1,   26,   16, 2156]])>

In [36]:
model4 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'tanh'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model4.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model4.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.2972 - accuracy: 0.9147
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1369 - accuracy: 0.9594
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0929 - accuracy: 0.9712
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0694 - accuracy: 0.9792
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0533 - accuracy: 0.9836


In [37]:
model4.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1028 - accuracy: 0.9693


[0.10279754549264908, 0.9693073630332947]

In [38]:
y_predict = model4.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 907us/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2207,    0,   14,    2,    2,    7,   16,    2,    4,    3],
       [   0, 2607,    1,    1,    1,    1,    1,    2,    3,    0],
       [   4,    9, 2239,   10,    5,    1,    5,    4,   18,    2],
       [   0,   11,   19, 2300,    0,   28,    1,   11,   13,    6],
       [   2,    5,   10,    1, 2155,    4,   11,   12,   12,   50],
       [   5,    5,    3,   23,    1, 2036,   11,    3,   11,    7],
       [  12,    8,    3,    0,    7,   14, 2251,    2,   12,    0],
       [   0,   16,   29,    9,    4,    2,    0, 2324,    3,   13],
       [   3,   17,    6,   25,    1,   20,    3,    6, 2143,    4],
       [   1,    9,    1,   13,   24,   12,    1,   28,   18, 2129]])>

In [39]:
model5 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'relu'),
    keras.layers.Dense(20, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model5.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model5.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.3707 - accuracy: 0.8917
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1688 - accuracy: 0.9498
Epoch 3/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1252 - accuracy: 0.9621
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1023 - accuracy: 0.9693
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0848 - accuracy: 0.9743


In [40]:
model5.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1139 - accuracy: 0.9675


[0.11390715092420578, 0.9674891829490662]

In [41]:
y_predict = model5.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 976us/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2208,    0,   21,    2,    1,    3,   12,    0,    6,    4],
       [   1, 2578,   10,    6,    2,    1,    1,    5,   13,    0],
       [   4,    0, 2239,    6,    9,    2,    4,   15,   16,    2],
       [   0,    5,   27, 2281,    0,   43,    0,   12,   15,    6],
       [   2,    5,    2,    1, 2157,    1,   12,    6,   11,   65],
       [   8,    2,    9,   34,    3, 2017,   11,    1,   15,    5],
       [  19,    4,    8,    0,   11,   16, 2242,    0,    9,    0],
       [   5,    9,   15,    3,    6,    1,    0, 2338,    2,   21],
       [   5,    7,    6,   22,    3,   20,    7,    5, 2142,   11],
       [   3,    4,    1,   17,   16,    6,    0,   33,    9, 2147]])>

In [42]:
model6 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'tanh'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'tanh'),
    keras.layers.Dense(20, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model6.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model6.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.3844 - accuracy: 0.9008
Epoch 2/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1624 - accuracy: 0.9520
Epoch 3/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1169 - accuracy: 0.9649
Epoch 4/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.0922 - accuracy: 0.9723
Epoch 5/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.0759 - accuracy: 0.9772


In [43]:
model6.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1176 - accuracy: 0.9656


[0.11763507127761841, 0.965584397315979]

In [44]:
y_predict = model6.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2205,    0,    8,    3,   11,    4,   11,    0,    7,    8],
       [   0, 2576,    7,    1,    4,    3,    2,    4,   18,    2],
       [   5,    3, 2218,   12,    8,    4,    3,   10,   29,    5],
       [   2,   10,   25, 2252,    2,   50,    1,    9,   24,   14],
       [   1,    4,    3,    0, 2152,    0,   10,    7,    6,   79],
       [  12,    5,    6,   15,    0, 2014,   16,    4,   21,   12],
       [  11,    5,    5,    0,   16,    7, 2248,    0,   17,    0],
       [   4,    6,   14,    4,    7,    3,    0, 2312,    6,   44],
       [   5,    6,    3,   14,    7,   11,    5,    1, 2158,   18],
       [   2,    3,    0,    4,   29,    5,    0,   15,    8, 2170]])>

In [45]:
model7 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'relu'),
    keras.layers.Dense(20, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model7.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model7.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.4986 - accuracy: 0.8685
Epoch 2/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.2050 - accuracy: 0.9404
Epoch 3/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1494 - accuracy: 0.9561
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1176 - accuracy: 0.9655
Epoch 5/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.0967 - accuracy: 0.9713


In [46]:
model7.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1197 - accuracy: 0.9639


[0.11965736746788025, 0.9638528227806091]

In [47]:
y_predict = model1.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2188,    0,   10,    2,    5,   12,   21,    0,   15,    4],
       [   0, 2592,    6,    0,    2,    3,    1,    5,    7,    1],
       [   4,    1, 2235,    3,   10,    2,    3,   16,   22,    1],
       [   2,   13,   33, 2202,    1,   76,    4,   23,   27,    8],
       [   0,    7,   11,    0, 2175,    1,   15,   10,    8,   35],
       [   5,    7,    8,   11,    5, 2028,   20,    3,   12,    6],
       [  10,    5,    7,    0,    6,   13, 2254,    1,   13,    0],
       [   4,    6,   28,    1,   11,    2,    0, 2333,    2,   13],
       [   6,   17,    9,   11,    3,   14,   10,    5, 2149,    4],
       [   3,    5,    3,    6,   66,   11,    0,   42,   21, 2079]])>

In [48]:
model8 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model8.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model8.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.4201 - accuracy: 0.8855
Epoch 2/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1900 - accuracy: 0.9439
Epoch 3/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1363 - accuracy: 0.9584
Epoch 4/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1023 - accuracy: 0.9685
Epoch 5/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.0808 - accuracy: 0.9750


In [49]:
model8.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1123 - accuracy: 0.9645


[0.11232537031173706, 0.9645021557807922]

In [50]:
y_predict = model8.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2200,    0,    6,    8,    4,   11,   12,    1,    8,    7],
       [   0, 2574,    5,   13,    2,    5,    2,    5,    7,    4],
       [   6,    2, 2210,   34,   16,    1,    1,   13,   13,    1],
       [   0,    8,   14, 2323,    1,   16,    0,   14,    7,    6],
       [   2,    6,    2,    1, 2165,    3,    7,    9,    5,   62],
       [   8,    2,    2,   60,    1, 2002,   10,    2,    9,    9],
       [  10,    4,    3,    0,   10,   40, 2231,    2,    9,    0],
       [   4,    5,   13,   15,    6,    1,    0, 2339,    1,   16],
       [   5,   13,    8,   56,    3,   29,    4,    7, 2077,   26],
       [   4,    2,    0,   16,   23,    4,    0,   25,    3, 2159]])>

In [51]:
model9 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model9.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model9.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.3921 - accuracy: 0.8916
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1822 - accuracy: 0.9451
Epoch 3/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1314 - accuracy: 0.9601
Epoch 4/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1008 - accuracy: 0.9692
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0785 - accuracy: 0.9758


In [52]:
model9.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1071 - accuracy: 0.9685


[0.1071430966258049, 0.968528151512146]

In [53]:
y_predict = model9.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2213,    0,   11,    2,    4,    9,    5,    1,    9,    3],
       [   0, 2592,    3,    2,    4,    0,    0,    4,   10,    2],
       [   6,    9, 2220,    8,    8,    0,    1,   22,   21,    2],
       [   1,    8,   22, 2277,    3,   20,    0,   15,   27,   16],
       [   3,    4,    9,    0, 2186,    2,    7,    8,    5,   38],
       [   7,    3,    8,   27,    5, 2005,   10,    4,   21,   15],
       [  22,    5,    4,    0,    9,   13, 2232,    2,   22,    0],
       [   2,   10,   15,    6,    9,    1,    0, 2326,    6,   25],
       [   4,    8,    3,   13,    5,    6,    3,    2, 2170,   14],
       [   4,    3,    0,    5,   33,    2,    0,   23,   14, 2152]])>

In [54]:
model10 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model10.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model10.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.2770 - accuracy: 0.9203
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1190 - accuracy: 0.9633
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0830 - accuracy: 0.9745
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0637 - accuracy: 0.9796
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0503 - accuracy: 0.9839


In [55]:
model10.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.0978 - accuracy: 0.9703


[0.09780839830636978, 0.9703030586242676]

In [56]:
y_predict = model10.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2213,    0,   12,    4,    3,    4,    7,    2,    5,    7],
       [   0, 2565,    8,    9,    2,    1,    4,    5,   20,    3],
       [   3,    1, 2240,    7,    4,    0,    3,   14,   22,    3],
       [   1,    3,   22, 2295,    0,   18,    0,    8,   35,    7],
       [   0,    2,   12,    0, 2192,    2,    4,    3,   10,   37],
       [   9,    1,    7,   27,    1, 2015,   14,    2,   25,    4],
       [  16,    4,    3,    0,   17,    9, 2245,    1,   14,    0],
       [   1,    2,   25,    3,    4,    1,    0, 2323,    8,   33],
       [   8,    4,   13,   13,    2,    6,    5,    2, 2165,   10],
       [   1,    0,    3,   11,   22,    6,    0,   14,   18, 2161]])>

In [57]:
model11 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'sigmoid'),
    keras.layers.Dense(40, activation = 'sigmoid'),
    keras.layers.Dense(10, activation = 'softmax')
])

model11.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model11.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.8599 - accuracy: 0.7731
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.2552 - accuracy: 0.9318
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1707 - accuracy: 0.9525
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1296 - accuracy: 0.9631
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1052 - accuracy: 0.9695


In [58]:
model11.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1316 - accuracy: 0.9616


[0.13160865008831024, 0.96155846118927]

In [59]:
y_predict = model11.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2193,    2,    9,    2,    5,   11,   24,    0,    5,    6],
       [   0, 2573,    6,   14,    0,    3,    2,   11,    5,    3],
       [   7,    2, 2198,   19,   15,    1,   11,   26,   15,    3],
       [   0,    8,   16, 2279,    1,   38,    1,   26,   12,    8],
       [   4,    3,    4,    1, 2159,    5,   17,   10,    4,   55],
       [  11,    3,    6,   28,    3, 2019,   15,    5,    8,    7],
       [  14,    5,    7,    0,   12,   21, 2240,    0,   10,    0],
       [   5,    3,   10,    7,    2,    1,    0, 2350,    0,   22],
       [   9,   17,    4,   44,    6,   25,   10,    8, 2080,   25],
       [   5,    1,    2,    7,   35,    8,    0,   49,    8, 2121]])>

In [60]:
model12 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'relu'),
    keras.layers.Dense(40, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model12.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model12.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.3247 - accuracy: 0.9055
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1437 - accuracy: 0.9567
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1067 - accuracy: 0.9663
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0823 - accuracy: 0.9741
Epoch 5/5
1466/1466 [==============================] - 4s 3ms/step - loss: 0.0680 - accuracy: 0.9783


In [61]:
model12.evaluate(X_testf, y_test)

722/722 [==============================] - 2s 3ms/step - loss: 0.1154 - accuracy: 0.9663


[0.1153566762804985, 0.9663203358650208]

In [62]:
y_predict = model12.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 2s 2ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2200,    0,   17,    1,    3,    9,   13,    1,    6,    7],
       [   0, 2586,    4,    1,    5,    3,    0,    5,   11,    2],
       [   1,    1, 2237,    6,   10,    4,    7,   12,   17,    2],
       [   1,    5,   34, 2232,    4,   68,    2,   17,   10,   16],
       [   0,    3,    1,    0, 2177,    1,    9,    7,    2,   62],
       [   7,    1,    6,   16,    3, 2027,   11,    4,   13,   17],
       [  17,    4,    3,    0,   17,   17, 2238,    1,   12,    0],
       [   0,    7,   12,    0,   11,    2,    0, 2330,    1,   37],
       [   6,    6,   11,   17,    5,   22,    7,    4, 2117,   33],
       [   1,    1,    1,    9,   15,    4,    1,   21,    5, 2178]])>

In [63]:
model13 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'tanh'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'tanh'),
    keras.layers.Dense(40, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model13.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model13.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 4s 2ms/step - loss: 0.3247 - accuracy: 0.9080
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1444 - accuracy: 0.9572
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1022 - accuracy: 0.9683
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0781 - accuracy: 0.9755
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0618 - accuracy: 0.9810


In [64]:
model13.evaluate(X_testf, y_test)

722/722 [==============================] - 2s 3ms/step - loss: 0.1123 - accuracy: 0.9685


[0.11230622231960297, 0.9684848189353943]

In [65]:
y_predict = model13.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2214,    0,    6,    2,    3,    4,   22,    0,    3,    3],
       [   0, 2603,    5,    1,    2,    0,    1,    2,    3,    0],
       [   4,    3, 2247,   12,    3,    1,   10,    3,   13,    1],
       [   2,   14,   24, 2270,    1,   38,    5,   11,   19,    5],
       [   2,    4,   12,    0, 2157,    3,   36,    8,    6,   34],
       [  11,    3,    2,   21,    3, 2005,   29,    2,   25,    4],
       [  11,    5,    1,    0,    5,    3, 2271,    0,   13,    0],
       [   2,    8,   28,    9,    9,    1,    0, 2326,    3,   14],
       [  11,   10,    4,   13,    1,   11,   13,    3, 2157,    5],
       [   2,   10,    0,   12,   35,    5,    0,   33,   17, 2122]])>

In [66]:
model14 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'relu'),
    keras.layers.Dense(40, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model14.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model14.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.4243 - accuracy: 0.8849
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1815 - accuracy: 0.9449
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1318 - accuracy: 0.9603
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1051 - accuracy: 0.9672
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0862 - accuracy: 0.9731


In [67]:
model14.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 2ms/step - loss: 0.1210 - accuracy: 0.9638


[0.12100733071565628, 0.9638095498085022]

In [68]:
y_predict = model14.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2227,    0,    2,    2,    4,    2,   11,    1,    5,    3],
       [   0, 2596,    4,    3,    1,    0,    1,    3,    7,    2],
       [  15,   15, 2161,   13,   20,    1,    9,   18,   42,    3],
       [   8,   11,   16, 2227,    0,   45,    3,   14,   54,   11],
       [   2,    7,    0,    0, 2203,    2,   12,    6,    5,   25],
       [  17,    3,    3,   16,    4, 2006,   31,    2,   10,   13],
       [  12,    9,    0,    0,   14,    4, 2260,    2,    8,    0],
       [   2,    7,   15,    2,    8,    1,    0, 2336,    6,   23],
       [  12,   10,    1,    7,    3,   16,   11,    2, 2158,    8],
       [   6,    5,    0,    3,   76,    4,    0,   29,   23, 2090]])>

In [69]:
model15 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model15.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model15.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 6s 4ms/step - loss: 0.4602 - accuracy: 0.8788
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.2041 - accuracy: 0.9397
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1538 - accuracy: 0.9543
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1235 - accuracy: 0.9626
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1033 - accuracy: 0.9693


In [70]:
model15.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1284 - accuracy: 0.9598


[0.12842616438865662, 0.9597835540771484]

In [71]:
y_predict = model15.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2192,    0,   10,   11,    2,   10,   18,    0,   10,    4],
       [   0, 2598,    4,    5,    0,    3,    1,    2,    4,    0],
       [   5,   13, 2211,   23,    9,    1,    5,   12,   17,    1],
       [   1,   14,   20, 2291,    0,   22,    1,   12,   20,    8],
       [   2,    7,    7,    2, 2157,    1,   24,    4,    9,   49],
       [   5,    6,    7,   46,    1, 2000,   12,    2,   17,    9],
       [  15,   14,    7,    1,    8,   42, 2209,    0,   13,    0],
       [   7,   13,   24,    8,   13,    5,    0, 2284,    5,   41],
       [   6,   31,    3,   41,    2,   24,    6,    2, 2100,   13],
       [   4,    8,    4,   12,   30,    6,    1,   22,   20, 2129]])>