In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras

In [2]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()


In [3]:
x_train2 = x_train.reshape(len(x_train), 28 * 28)
df1 = pd.DataFrame(x_train2)


In [4]:
df1

0    1    2    3    4    5    6    7    8    9    ...  774  775  776  \
0        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
2        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
3        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
4        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
59995    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59996    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59997    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59998    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59999    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   

       777  778  779  780  781  782  783  
0        0    0    0    0    0    0    0  
1        0    0    0    0    0    0    0  
2        0    0    0    0    0    0    0  
3        0    0    0    0    0    0    0  
4        0    0    0    0    0    0    0  
...    ...  ...  ...  ...  ...  ...  ...  
59995    0    0    0    0    0    0    0  
59996    0    0    0    0    0    0    0  
59997    0    0    0    0    0    0    0  
59998    0    0    0    0    0    0    0  
59999    0    0    0    0    0    0    0  

[60000 rows x 784 columns]

In [5]:
df1_target = pd.DataFrame(y_train)

In [6]:
df1_target

0
0      5
1      0
2      4
3      1
4      9
...   ..
59995  8
59996  3
59997  5
59998  6
59999  8

[60000 rows x 1 columns]

In [7]:
df1['target'] = df1_target[0]
df1.head()

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  782  \
0  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
1  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
2  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
3  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
4  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   

   783  target  
0    0       5  
1    0       0  
2    0       4  
3    0       1  
4    0       9  

[5 rows x 785 columns]

# We did the merging for X_train and y_train, now lets do it for X_test and y_test

In [8]:
x_test2 = x_test.reshape(len(x_test), 28 * 28)
df2 = pd.DataFrame(x_test2)
df2_target = pd.DataFrame(y_test)
df2['target'] = df2_target[0]
df2.head()

##MERGING HAS BEEN DONE. WE NOW HAVE DF1 and DF2

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  782  \
0  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
1  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
2  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
3  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
4  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   

   783  target  
0    0       7  
1    0       2  
2    0       1  
3    0       0  
4    0       4  

[5 rows x 785 columns]

In [9]:
##NOW GETTING THE DF IN WHICH WE WILL MERGE ALL OF THESE
df3 = pd.concat([df1, df2], ignore_index = True)
df3

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  \
0      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
1      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
2      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
3      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
4      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
...   .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
69995  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69996  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69997  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69998  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69999  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   

       782  783  target  
0        0    0       5  
1        0    0       0  
2        0    0       4  
3        0    0       1  
4        0    0       9  
...    ...  ...     ...  
69995    0    0       2  
69996    0    0       3  
69997    0    0       4  
69998    0    0       5  
69999    0    0       6  

[70000 rows x 785 columns]

In [10]:
# y = df3['target']
# y = pd.DataFrame(y)
# y.head()
df_train = df3.sample(frac=0.67,random_state=42)
df_test = df3.drop(df_train.index)
df_train

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  \
46730  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
48393  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
41416  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
34506  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
43725  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
...   .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
12056  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
393    0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
63024  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
11837  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
57774  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   

       782  783  target  
46730    0    0       8  
48393    0    0       4  
41416    0    0       8  
34506    0    0       7  
43725    0    0       7  
...    ...  ...     ...  
12056    0    0       1  
393      0    0       8  
63024    0    0       4  
11837    0    0       3  
57774    0    0       7  

[46900 rows x 785 columns]

In [11]:
y_train = df_train['target']
y_train = pd.DataFrame(y_train)
y_train.head()
# df_train = df_train.drop('target', axis = 1, inplace = True)
# df_train.head()

target
46730       8
48393       4
41416       8
34506       7
43725       7

In [12]:
df_train = df_train.drop('target', axis=1)


In [13]:
df_train.head()
df_test

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  \
2      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
5      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
10     0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
12     0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
15     0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
...   .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
69982  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69985  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69988  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69989  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69996  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   

       782  783  target  
2        0    0       4  
5        0    0       2  
10       0    0       3  
12       0    0       3  
15       0    0       7  
...    ...  ...     ...  
69982    0    0       5  
69985    0    0       2  
69988    0    0       5  
69989    0    0       6  
69996    0    0       3  

[23100 rows x 785 columns]

In [14]:
y_test = df_test['target']
y_test = pd.DataFrame(y_test)
y_test.head()

target
2        4
5        2
10       3
12       3
15       7

In [15]:
df_test = df_test.drop('target', axis=1)


In [16]:
df_test.head()

0    1    2    3    4    5    6    7    8    9    ...  774  775  776  777  \
2     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
5     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
10    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
12    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
15    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   

    778  779  780  781  782  783  
2     0    0    0    0    0    0  
5     0    0    0    0    0    0  
10    0    0    0    0    0    0  
12    0    0    0    0    0    0  
15    0    0    0    0    0    0  

[5 rows x 784 columns]

# Converting these into NumPy arrays for use in the ANN model

In [17]:
x_train = df_train.to_numpy()
x_train
x_test = df_test.to_numpy()
y_train = y_train.to_numpy()
y_test = y_test.to_numpy()

# Performing the required pre-processing

In [18]:
x_train = x_train/255
x_test = x_test/255

In [19]:
#x_train[0]

In [20]:
X_trainf = x_train.reshape(len(x_train), 28 * 28)
#we choose to flatten the data in order to make the first input layer of the neural network have 784 values, since we currently have values stored in 28*28 form

In [21]:
X_testf = x_test.reshape(len(x_test), 28*28)

# MODEL 1 -- 150 neurons, 2 layers, sigmoid

In [22]:
model1 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'sigmoid'),
    keras.layers.Dense(10, activation = 'softmax')
])

model1.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model1.fit(X_trainf, y_train, epochs = 5)



Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.5886 - accuracy: 0.8512
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.2142 - accuracy: 0.9365
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1554 - accuracy: 0.9539
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1204 - accuracy: 0.9645
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0973 - accuracy: 0.9715


In [23]:
model1.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 982us/step - loss: 0.1226 - accuracy: 0.9632


[0.12262634932994843, 0.963246762752533]

In [24]:
y_predict = model1.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 784us/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2216,    1,    1,    2,    3,    2,    7,    1,    3,    8],
       [   1, 2607,   10,    3,    3,    1,    3,    9,    4,    6],
       [  14,    2, 2249,    1,   14,    0,    7,   17,    3,    0],
       [   6,   12,   36, 2281,    2,   20,    2,   21,   12,    9],
       [   3,    6,    7,    0, 2238,    1,   12,    5,    4,   61],
       [  26,    8,    7,   24,    9, 1927,   37,    4,   13,   11],
       [  15,    7,    3,    0,    8,    8, 2160,    0,    8,    0],
       [   7,    8,   16,    4,    7,    0,    0, 2264,    2,   26],
       [  23,   26,   26,   10,    6,   12,   22,    6, 2135,   19],
       [   9,    8,    4,   10,   26,    6,    1,   24,    8, 2174]])>

# MODEL 2 -- 100 Neurons, 3 Hidden Layers

In [25]:
model2 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'sigmoid'),
    keras.layers.Dense(20, activation = 'sigmoid'),
    keras.layers.Dense(10, activation = 'softmax')
])

model2.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model2.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 1.0750 - accuracy: 0.7381
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.3247 - accuracy: 0.9197
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.2156 - accuracy: 0.9423
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1672 - accuracy: 0.9546
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1373 - accuracy: 0.9622


In [26]:
model2.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1587 - accuracy: 0.9547


[0.1586770862340927, 0.9546753168106079]

In [27]:
y_predict = model2.predict(X_testf)

722/722 [==============================] - 1s 868us/step


In [28]:
y_predict[0]

array([1.2552934e-05, 2.5209551e-05, 1.0056124e-03, 7.0695287e-06,
       9.8430461e-01, 3.0137846e-04, 1.0331342e-03, 4.2952041e-04,
       4.2106295e-03, 8.6702518e-03], dtype=float32)

In [29]:
np.argmax(y_predict[0]) #gives the maximum value out of the given ones

4

In [30]:
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array

In [31]:
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices


In [32]:
cm #this is the confusion matrix, we are supposed to do this for all 15 of the models. Preferable if we beautify this a bit using matPlotLib, or seaborn if permitted by sir

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2190,    1,   13,    5,    3,   11,    6,    8,    5,    2],
       [   0, 2578,   15,    5,    0,    0,    2,   10,   19,   18],
       [  22,    5, 2211,   16,   16,    0,    3,   13,   17,    4],
       [  11,    3,   26, 2270,    0,   34,    1,   26,   18,   12],
       [   1,    8,    8,    0, 2215,    2,   10,    9,   10,   74],
       [  20,    4,    2,   31,    3, 1950,   16,    2,   26,   12],
       [  19,    6,    6,    0,   17,   22, 2121,    0,   18,    0],
       [   5,    6,   17,    9,    8,    2,    0, 2252,    3,   32],
       [   4,   23,   24,   31,    6,   20,    7,    2, 2134,   34],
       [   5,    3,    2,   21,   42,   12,    1,   37,   15, 2132]])>

# MODEL 3 -- 150 Neurons, 2 Hidden Layers, ReLU

In [33]:
model3 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model3.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model3.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.2881 - accuracy: 0.9172
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1244 - accuracy: 0.9614
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0882 - accuracy: 0.9725
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0679 - accuracy: 0.9786
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0531 - accuracy: 0.9827


In [34]:
model3.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1111 - accuracy: 0.9671


[0.11110863834619522, 0.9671428799629211]

In [35]:
y_predict = model3.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 860us/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2189,    1,   15,    6,    3,    5,   12,    4,    8,    1],
       [   1, 2613,    8,    5,    2,    0,    2,    9,    4,    3],
       [   2,    4, 2262,    9,    8,    1,    2,   10,    9,    0],
       [   0,    5,   24, 2333,    1,    8,    1,    5,   21,    3],
       [   0,    6,   13,    0, 2247,    1,   25,    7,    8,   30],
       [   4,    3,    7,   53,    5, 1918,   16,    4,   40,   16],
       [  10,    7,    1,    1,    0,    1, 2177,    0,   12,    0],
       [   1,    6,   30,    1,    2,    1,    1, 2271,    8,   13],
       [   4,   15,   25,   24,    3,    6,   13,    4, 2186,    5],
       [   1,    5,    4,   29,   28,    6,    3,   20,   29, 2145]])>

In [36]:
model4 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'tanh'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model4.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model4.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.3016 - accuracy: 0.9133
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1424 - accuracy: 0.9575
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0996 - accuracy: 0.9695
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0742 - accuracy: 0.9773
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0604 - accuracy: 0.9813


In [37]:
model4.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 980us/step - loss: 0.1038 - accuracy: 0.9690


[0.10376088321208954, 0.9690476059913635]

In [38]:
y_predict = model4.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 862us/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2204,    1,    3,    6,    3,   10,    8,    2,    6,    1],
       [   1, 2609,    7,    5,    4,    0,    4,    9,    8,    0],
       [  12,    3, 2210,   24,   13,    3,    4,   21,   17,    0],
       [   0,    2,    7, 2311,    0,   37,    2,   12,   28,    2],
       [   1,    1,    4,    0, 2295,    4,    8,    5,    4,   15],
       [   9,    0,    3,   20,    2, 1996,   17,    1,   13,    5],
       [  10,    8,    3,    1,    9,   13, 2160,    0,    5,    0],
       [   3,    7,    9,    4,   13,    3,    0, 2277,    4,   14],
       [   5,   10,    6,   12,    8,   16,   13,    4, 2205,    6],
       [   2,    5,    1,   17,   70,   20,    2,   23,   12, 2118]])>

In [39]:
model5 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'relu'),
    keras.layers.Dense(20, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model5.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model5.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.3862 - accuracy: 0.8861
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1704 - accuracy: 0.9486
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1253 - accuracy: 0.9618
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0993 - accuracy: 0.9697
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0844 - accuracy: 0.9728


In [40]:
model5.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1148 - accuracy: 0.9668


[0.11481737345457077, 0.9668398499488831]

In [41]:
y_predict = model5.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2212,    0,    3,    2,    1,    4,    6,    6,    6,    4],
       [   1, 2611,    6,    2,    5,    1,    4,    7,    7,    3],
       [  12,    9, 2229,    7,   11,    3,    5,   11,   19,    1],
       [   2,    9,   33, 2253,    2,   36,    1,   16,   41,    8],
       [   3,    3,   10,    0, 2278,    1,   11,    4,    2,   25],
       [   8,    2,    3,   21,    2, 1979,   17,    1,   16,   17],
       [  27,    5,    3,    0,    3,    9, 2154,    0,    8,    0],
       [   0,   12,   15,    0,    8,    0,    0, 2272,    7,   20],
       [   6,   16,   15,    3,    3,   15,   16,    4, 2192,   15],
       [   2,    2,    0,    4,   55,   12,    0,   23,   18, 2154]])>

In [42]:
model6 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'tanh'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'tanh'),
    keras.layers.Dense(20, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model6.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model6.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.3795 - accuracy: 0.9033
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1626 - accuracy: 0.9536
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1199 - accuracy: 0.9640
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0935 - accuracy: 0.9723
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0759 - accuracy: 0.9767


In [43]:
model6.evaluate(X_testf, y_test)

722/722 [==============================] - 2s 2ms/step - loss: 0.1435 - accuracy: 0.9575


[0.14349910616874695, 0.9575324654579163]

In [44]:
y_predict = model6.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2215,    0,    6,    1,    3,    2,    4,    0,   13,    0],
       [   1, 2610,    8,    1,   10,    0,    1,    3,    9,    4],
       [  17,    6, 2245,    4,    8,    1,    3,   10,   13,    0],
       [  12,   16,   48, 2177,    0,   17,    2,   12,  108,    9],
       [   1,    4,   11,    1, 2287,    2,    9,    6,    4,   12],
       [  39,    9,    5,   25,    8, 1896,   23,    1,   46,   14],
       [  20,    4,    7,    1,    7,    9, 2145,    0,   16,    0],
       [   4,    9,   31,    2,   16,    0,    0, 2242,    9,   21],
       [   8,   12,    9,    4,    4,    2,    7,    2, 2231,    6],
       [  11,    4,    1,    7,  102,    3,    1,   21,   49, 2071]])>

In [45]:
model7 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'relu'),
    keras.layers.Dense(20, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model7.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model7.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 1ms/step - loss: 0.4866 - accuracy: 0.8748
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1945 - accuracy: 0.9435
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1437 - accuracy: 0.9580
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1159 - accuracy: 0.9661
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0967 - accuracy: 0.9707


In [46]:
model7.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1300 - accuracy: 0.9614


[0.12995396554470062, 0.9613853096961975]

In [47]:
y_predict = model1.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 898us/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2216,    1,    1,    2,    3,    2,    7,    1,    3,    8],
       [   1, 2607,   10,    3,    3,    1,    3,    9,    4,    6],
       [  14,    2, 2249,    1,   14,    0,    7,   17,    3,    0],
       [   6,   12,   36, 2281,    2,   20,    2,   21,   12,    9],
       [   3,    6,    7,    0, 2238,    1,   12,    5,    4,   61],
       [  26,    8,    7,   24,    9, 1927,   37,    4,   13,   11],
       [  15,    7,    3,    0,    8,    8, 2160,    0,    8,    0],
       [   7,    8,   16,    4,    7,    0,    0, 2264,    2,   26],
       [  23,   26,   26,   10,    6,   12,   22,    6, 2135,   19],
       [   9,    8,    4,   10,   26,    6,    1,   24,    8, 2174]])>

In [48]:
model8 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model8.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model8.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 3s 1ms/step - loss: 0.4355 - accuracy: 0.8778
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1894 - accuracy: 0.9426
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1389 - accuracy: 0.9574
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1077 - accuracy: 0.9679
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0858 - accuracy: 0.9737


In [49]:
model8.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1077 - accuracy: 0.9665


[0.10767311602830887, 0.9664502143859863]

In [50]:
y_predict = model8.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 967us/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2201,    0,   15,    5,    1,    4,    9,    0,    7,    2],
       [   1, 2608,   11,    4,    4,    0,    3,    8,    4,    4],
       [   8,    3, 2252,    7,   11,    1,    3,   10,   12,    0],
       [   3,    7,   23, 2299,    1,   16,    2,   17,   27,    6],
       [   1,    4,   19,    0, 2250,    0,   10,    7,    7,   39],
       [  11,    7,    6,   31,    5, 1960,   19,    2,   14,   11],
       [  18,    6,    5,    0,    4,   13, 2156,    0,    7,    0],
       [   4,    6,   17,    4,    8,    0,    1, 2274,    5,   15],
       [   5,   18,   13,   32,    4,    8,    9,    5, 2179,   12],
       [   5,    9,    2,   12,   42,    9,    1,   29,   15, 2146]])>

In [51]:
model9 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model9.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model9.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.3973 - accuracy: 0.8906
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1824 - accuracy: 0.9456
Epoch 3/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1305 - accuracy: 0.9610
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0992 - accuracy: 0.9697
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0788 - accuracy: 0.9759


In [52]:
model9.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.0995 - accuracy: 0.9697


[0.09952650219202042, 0.9696536660194397]

In [53]:
y_predict = model9.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 976us/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2199,    0,    3,    3,    5,    7,    9,    2,    9,    7],
       [   1, 2594,   12,    5,    6,    1,    4,   10,    7,    7],
       [   9,    4, 2248,    5,   11,    1,    3,   11,   14,    1],
       [   3,    3,   26, 2288,    1,   37,    2,   15,   24,    2],
       [   2,    4,    6,    0, 2295,    1,    6,    4,    4,   15],
       [   7,    3,    2,   23,    6, 1980,   19,    0,   16,   10],
       [   9,    5,    3,    1,   11,   10, 2165,    0,    5,    0],
       [   1,    7,   16,    3,   12,    0,    0, 2276,    8,   11],
       [   5,   10,   13,   11,    2,   12,    6,    1, 2216,    9],
       [   3,    4,    1,   10,   61,   14,    0,   24,   15, 2138]])>

In [54]:
model10 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model10.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model10.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.2748 - accuracy: 0.9209
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1145 - accuracy: 0.9657
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0795 - accuracy: 0.9755
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0603 - accuracy: 0.9812
Epoch 5/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.0467 - accuracy: 0.9850


In [55]:
model10.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.0863 - accuracy: 0.9740


[0.08630749583244324, 0.9740259647369385]

In [56]:
y_predict = model10.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2215,    2,    4,    2,    2,    4,    7,    2,    5,    1],
       [   1, 2614,    7,    2,    2,    0,    2,   10,    7,    2],
       [  14,    6, 2252,    6,    6,    0,    2,    7,   12,    2],
       [   1,    7,   20, 2319,    1,    9,    1,   13,   24,    6],
       [   8,    3,    7,    0, 2253,    0,    5,    8,    4,   49],
       [  13,    2,    4,   27,    2, 1978,    8,    0,   25,    7],
       [  12,    7,    1,    1,    5,    3, 2167,    0,   13,    0],
       [   2,    7,   15,    1,    4,    2,    1, 2294,    4,    4],
       [   9,   12,    5,   10,    4,    6,    5,    6, 2218,   10],
       [   4,    6,    1,    8,   14,   10,    0,   25,   12, 2190]])>

In [57]:
model11 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'sigmoid'),
    keras.layers.Dense(40, activation = 'sigmoid'),
    keras.layers.Dense(10, activation = 'softmax')
])

model11.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model11.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.8557 - accuracy: 0.7776
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.2447 - accuracy: 0.9337
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1722 - accuracy: 0.9519
Epoch 4/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1331 - accuracy: 0.9623
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1086 - accuracy: 0.9691


In [58]:
model11.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1317 - accuracy: 0.9607


[0.13165366649627686, 0.9607359170913696]

In [59]:
y_predict = model11.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2206,    1,    3,    4,    5,    4,    9,    2,    9,    1],
       [   1, 2596,   14,    5,    6,    2,    2,    9,   11,    1],
       [  20,    6, 2209,   11,   18,    1,    7,    7,   28,    0],
       [   1,    8,   34, 2260,    3,   29,    1,   14,   43,    8],
       [   1,    3,   13,    0, 2285,    0,   10,    5,    6,   14],
       [  18,    2,    3,   25,    6, 1947,   17,    1,   39,    8],
       [  11,    5,    5,    0,    9,    9, 2160,    0,   10,    0],
       [   6,    9,   22,    5,   17,    1,    1, 2245,    6,   22],
       [   6,   20,   15,    8,    6,    9,    7,    6, 2204,    4],
       [   6,    5,    1,   16,   82,   20,    2,   22,   35, 2081]])>

In [60]:
model12 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'relu'),
    keras.layers.Dense(40, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model12.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model12.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.3351 - accuracy: 0.9020
Epoch 2/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1468 - accuracy: 0.9558
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1082 - accuracy: 0.9661
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0830 - accuracy: 0.9741
Epoch 5/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.0679 - accuracy: 0.9780


In [61]:
model12.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1280 - accuracy: 0.9633


[0.12796370685100555, 0.9632900357246399]

In [62]:
y_predict = model12.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2229,    0,    1,    0,    0,    0,    5,    1,    6,    2],
       [   1, 2597,   13,    0,    3,    0,    4,    9,   18,    2],
       [  26,    4, 2243,    4,   10,    0,    1,    6,   11,    2],
       [  10,    8,   37, 2219,    2,   42,    2,   11,   57,   13],
       [   3,    6,   18,    0, 2266,    0,    6,   13,    6,   19],
       [  24,    5,    4,   13,    2, 1938,   32,    3,   28,   17],
       [  28,    6,    6,    0,    8,    7, 2145,    0,    9,    0],
       [  11,    7,   28,    1,    6,    0,    1, 2256,    7,   17],
       [  20,    6,   16,    5,    7,    3,   12,    3, 2197,   16],
       [   7,    4,    2,    1,   38,    6,    3,   21,   26, 2162]])>

In [63]:
model13 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'tanh'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'tanh'),
    keras.layers.Dense(40, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model13.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model13.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 1ms/step - loss: 0.3193 - accuracy: 0.9087
Epoch 2/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1475 - accuracy: 0.9555
Epoch 3/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1052 - accuracy: 0.9678
Epoch 4/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.0816 - accuracy: 0.9743
Epoch 5/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.0664 - accuracy: 0.9796


In [64]:
model13.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1062 - accuracy: 0.9687


[0.10622717440128326, 0.9687445759773254]

In [65]:
y_predict = model13.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2209,    1,    0,    5,    3,    9,    4,    0,    8,    5],
       [   0, 2608,    8,    5,    6,    0,    5,    4,    9,    2],
       [  16,    6, 2235,   18,   10,    0,    4,    7,   10,    1],
       [   4,    4,   12, 2340,    0,   13,    0,    7,   17,    4],
       [   1,    4,    4,    0, 2290,    1,    6,    5,    4,   22],
       [   5,    5,    2,   52,    5, 1946,   16,    1,   27,    7],
       [  12,    4,    3,    1,   12,    7, 2161,    0,    9,    0],
       [   4,    8,   18,   10,   10,    5,    0, 2250,    5,   24],
       [  10,    8,   12,   21,    4,   11,    4,    3, 2203,    9],
       [   7,   10,    1,   23,   45,   13,    2,   17,   16, 2136]])>

In [66]:
model14 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'relu'),
    keras.layers.Dense(40, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model14.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model14.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.4125 - accuracy: 0.8830
Epoch 2/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1831 - accuracy: 0.9446
Epoch 3/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1342 - accuracy: 0.9594
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1060 - accuracy: 0.9675
Epoch 5/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.0877 - accuracy: 0.9730


In [67]:
model14.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1215 - accuracy: 0.9642


[0.12149626761674881, 0.9642423987388611]

In [68]:
y_predict = model14.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2211,    0,    4,    5,    3,    5,    3,    1,    9,    3],
       [   1, 2554,   17,   17,    4,    2,    3,   32,    9,    8],
       [  12,    0, 2248,   12,   11,    0,    2,   12,   10,    0],
       [   3,    1,   13, 2342,    0,   21,    0,   11,    9,    1],
       [   3,    3,   14,    1, 2238,    1,    9,   11,    7,   50],
       [  10,    1,    5,   42,    5, 1963,   15,    2,   17,    6],
       [  23,    6,    3,    2,    6,   18, 2139,    1,   11,    0],
       [   6,    2,   13,   10,    5,    1,    0, 2285,    2,   10],
       [  10,   10,   14,   59,    2,    9,    3,    3, 2164,   11],
       [   3,    3,    0,   26,   38,   14,    1,   37,   18, 2130]])>

In [69]:
model15 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model15.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model15.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.4741 - accuracy: 0.8717
Epoch 2/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.2063 - accuracy: 0.9402
Epoch 3/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1555 - accuracy: 0.9543
Epoch 4/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1233 - accuracy: 0.9632
Epoch 5/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1029 - accuracy: 0.9696


In [70]:
model15.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1284 - accuracy: 0.9608


[0.1284199208021164, 0.9608225226402283]

In [71]:
y_predict = model15.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2189,    0,    5,    7,    0,   11,    9,    1,   15,    7],
       [   1, 2596,    7,    5,    3,    1,    4,    9,   14,    7],
       [   2,    6, 2194,   19,   13,    1,    3,   16,   52,    1],
       [   2,    8,   19, 2263,    1,   28,    0,   15,   57,    8],
       [   2,    5,   12,    0, 2217,    2,   10,    5,   20,   64],
       [   8,    5,    3,   36,    2, 1949,   13,    0,   39,   11],
       [  14,    4,    6,    0,    5,   15, 2147,    1,   17,    0],
       [   6,    7,   16,    5,    8,    3,    0, 2249,   11,   29],
       [   4,   15,    5,   11,    2,    9,    5,    0, 2227,    7],
       [   6,    5,    0,   14,   31,   10,    2,   14,   24, 2164]])>