In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras

In [2]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()


In [3]:
x_train2 = x_train.reshape(len(x_train), 28 * 28)
df1 = pd.DataFrame(x_train2)


In [4]:
df1

0    1    2    3    4    5    6    7    8    9    ...  774  775  776  \
0        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
2        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
3        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
4        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
59995    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59996    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59997    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59998    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59999    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   

       777  778  779  780  781  782  783  
0        0    0    0    0    0    0    0  
1        0    0    0    0    0    0    0  
2        0    0    0    0    0    0    0  
3        0    0    0    0    0    0    0  
4        0    0    0    0    0    0    0  
...    ...  ...  ...  ...  ...  ...  ...  
59995    0    0    0    0    0    0    0  
59996    0    0    0    0    0    0    0  
59997    0    0    0    0    0    0    0  
59998    0    0    0    0    0    0    0  
59999    0    0    0    0    0    0    0  

[60000 rows x 784 columns]

In [5]:
df1_target = pd.DataFrame(y_train)

In [6]:
df1_target

0
0      5
1      0
2      4
3      1
4      9
...   ..
59995  8
59996  3
59997  5
59998  6
59999  8

[60000 rows x 1 columns]

In [7]:
df1['target'] = df1_target[0]
df1.head()

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  782  \
0  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
1  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
2  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
3  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
4  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   

   783  target  
0    0       5  
1    0       0  
2    0       4  
3    0       1  
4    0       9  

[5 rows x 785 columns]

# We did the merging for X_train and y_train, now lets do it for X_test and y_test

In [8]:
x_test2 = x_test.reshape(len(x_test), 28 * 28)
df2 = pd.DataFrame(x_test2)
df2_target = pd.DataFrame(y_test)
df2['target'] = df2_target[0]
df2.head()

##MERGING HAS BEEN DONE. WE NOW HAVE DF1 and DF2

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  782  \
0  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
1  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
2  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
3  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
4  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   

   783  target  
0    0       7  
1    0       2  
2    0       1  
3    0       0  
4    0       4  

[5 rows x 785 columns]

In [9]:
##NOW GETTING THE DF IN WHICH WE WILL MERGE ALL OF THESE
df3 = pd.concat([df1, df2], ignore_index = True)
df3

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  \
0      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
1      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
2      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
3      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
4      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
...   .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
69995  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69996  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69997  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69998  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69999  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   

       782  783  target  
0        0    0       5  
1        0    0       0  
2        0    0       4  
3        0    0       1  
4        0    0       9  
...    ...  ...     ...  
69995    0    0       2  
69996    0    0       3  
69997    0    0       4  
69998    0    0       5  
69999    0    0       6  

[70000 rows x 785 columns]

In [10]:
# y = df3['target']
# y = pd.DataFrame(y)
# y.head()
df_train = df3.sample(frac=0.67,random_state=1)
df_test = df3.drop(df_train.index)
df_train

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  \
6670   0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
49567  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
50796  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
22310  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
54037  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
...   .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
39143  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
20265  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
1429   0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
15439  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
33756  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   

       782  783  target  
6670     0    0       6  
49567    0    0       2  
50796    0    0       7  
22310    0    0       5  
54037    0    0       7  
...    ...  ...     ...  
39143    0    0       3  
20265    0    0       2  
1429     0    0       3  
15439    0    0       1  
33756    0    0       9  

[46900 rows x 785 columns]

In [11]:
y_train = df_train['target']
y_train = pd.DataFrame(y_train)
y_train.head()
# df_train = df_train.drop('target', axis = 1, inplace = True)
# df_train.head()

target
6670        6
49567       2
50796       7
22310       5
54037       7

In [12]:
df_train = df_train.drop('target', axis=1)


In [13]:
df_train.head()
df_test

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  \
1      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
4      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
5      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
6      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
7      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
...   .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
69984  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69988  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69992  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69994  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69997  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   

       782  783  target  
1        0    0       0  
4        0    0       9  
5        0    0       2  
6        0    0       1  
7        0    0       3  
...    ...  ...     ...  
69984    0    0       1  
69988    0    0       5  
69992    0    0       9  
69994    0    0       1  
69997    0    0       4  

[23100 rows x 785 columns]

In [14]:
y_test = df_test['target']
y_test = pd.DataFrame(y_test)
y_test.head()

target
1       0
4       9
5       2
6       1
7       3

In [15]:
df_test = df_test.drop('target', axis=1)


In [16]:
df_test.head()

0    1    2    3    4    5    6    7    8    9    ...  774  775  776  777  \
1    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
4    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
5    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
6    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
7    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   

   778  779  780  781  782  783  
1    0    0    0    0    0    0  
4    0    0    0    0    0    0  
5    0    0    0    0    0    0  
6    0    0    0    0    0    0  
7    0    0    0    0    0    0  

[5 rows x 784 columns]

# Converting these into NumPy arrays for use in the ANN model

In [17]:
x_train = df_train.to_numpy()
x_train
x_test = df_test.to_numpy()
y_train = y_train.to_numpy()
y_test = y_test.to_numpy()

# Performing the required pre-processing

In [18]:
x_train = x_train/255
x_test = x_test/255

In [19]:
#x_train[0]

In [20]:
X_trainf = x_train.reshape(len(x_train), 28 * 28)
#we choose to flatten the data in order to make the first input layer of the neural network have 784 values, since we currently have values stored in 28*28 form

In [21]:
X_testf = x_test.reshape(len(x_test), 28*28)

# MODEL 1 -- 150 neurons, 2 layers, sigmoid

In [22]:
model1 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'sigmoid'),
    keras.layers.Dense(10, activation = 'softmax')
])

model1.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model1.fit(X_trainf, y_train, epochs = 5)



Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.5811 - accuracy: 0.8555
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.2146 - accuracy: 0.9376
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1571 - accuracy: 0.9546
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1225 - accuracy: 0.9643
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0996 - accuracy: 0.9717


In [23]:
model1.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 939us/step - loss: 0.1164 - accuracy: 0.9644


[0.11641556024551392, 0.9644156098365784]

In [24]:
y_predict = model1.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 807us/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2241,    1,    6,    1,    7,    5,   20,    3,   16,    5],
       [   0, 2540,    6,    6,    4,    0,    4,    7,   13,    5],
       [   3,    4, 2162,   15,   11,    1,    5,   13,   15,    4],
       [   0,    4,   23, 2218,    0,   17,    3,   13,   25,    3],
       [   1,    5,    5,    2, 2160,    1,   16,    6,   10,   68],
       [  12,    5,    5,   49,    9, 1893,   22,    4,   39,   14],
       [   9,    8,    7,    0,    8,    5, 2259,    0,    7,    0],
       [   0,   12,   13,    4,   16,    0,    1, 2335,    2,   20],
       [   3,   23,    3,   20,    3,    6,    9,    7, 2223,   10],
       [   5,    3,    1,   14,   27,    5,    1,   18,   11, 2247]])>

# MODEL 2 -- 100 Neurons, 3 Hidden Layers

In [25]:
model2 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'sigmoid'),
    keras.layers.Dense(20, activation = 'sigmoid'),
    keras.layers.Dense(10, activation = 'softmax')
])

model2.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model2.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 1.1451 - accuracy: 0.7146
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.3195 - accuracy: 0.9232
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.2071 - accuracy: 0.9454
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1590 - accuracy: 0.9567
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1305 - accuracy: 0.9648


In [26]:
model2.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 982us/step - loss: 0.1477 - accuracy: 0.9583


[0.14765708148479462, 0.958268404006958]

In [27]:
y_predict = model2.predict(X_testf)

722/722 [==============================] - 1s 962us/step


In [28]:
y_predict[0]

array([9.9611920e-01, 1.4044691e-03, 3.2196112e-04, 8.0811253e-05,
       2.0963341e-06, 7.8629103e-04, 1.0872180e-05, 1.0830233e-03,
       2.2790773e-05, 1.6842045e-04], dtype=float32)

In [29]:
np.argmax(y_predict[0]) #gives the maximum value out of the given ones

0

In [30]:
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array

In [31]:
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices


In [32]:
cm #this is the confusion matrix, we are supposed to do this for all 15 of the models. Preferable if we beautify this a bit using matPlotLib, or seaborn if permitted by sir

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2240,    1,    9,    1,    5,    9,   17,    5,   14,    4],
       [   1, 2536,    6,    9,    6,    2,    2,   11,   10,    2],
       [  15,    8, 2125,   14,   18,    1,    8,   20,   22,    2],
       [   3,    4,   24, 2178,    0,   48,    2,   12,   30,    5],
       [   2,    2,    8,    0, 2190,    4,   15,    8,    3,   42],
       [  10,    2,    2,   25,   11, 1937,   29,    2,   17,   17],
       [   6,    4,   11,    0,   13,   23, 2238,    0,    8,    0],
       [   2,   10,   33,    0,   11,    0,    0, 2324,    1,   22],
       [   4,   27,    7,   18,    8,   16,   14,    3, 2193,   17],
       [   8,    2,    2,    9,   67,   20,    3,   32,   14, 2175]])>

# MODEL 3 -- 150 Neurons, 2 Hidden Layers, ReLU

In [33]:
model3 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model3.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model3.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.2947 - accuracy: 0.9126
Epoch 2/5
1466/1466 [==============================] - 4s 2ms/step - loss: 0.1307 - accuracy: 0.9608
Epoch 3/5
1466/1466 [==============================] - 5s 3ms/step - loss: 0.0939 - accuracy: 0.9704
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0715 - accuracy: 0.9767
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0571 - accuracy: 0.9819


In [34]:
model3.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 2ms/step - loss: 0.0932 - accuracy: 0.9727


[0.09317970275878906, 0.9727272987365723]

In [35]:
y_predict = model3.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 2s 2ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2262,    1,   10,    1,    1,    7,    6,    2,   12,    3],
       [   0, 2544,    7,    6,    5,    0,    4,    7,    8,    4],
       [   4,    2, 2199,    6,    3,    2,    0,   14,    3,    0],
       [   2,    1,   24, 2237,    0,   14,    0,    6,   20,    2],
       [   1,    3,    7,    0, 2174,    2,    8,   20,    4,   55],
       [   4,    3,    4,   34,    3, 1975,    5,    1,   15,    8],
       [  11,    4,    5,    1,    9,   24, 2235,    1,   13,    0],
       [   1,   10,   15,    1,    3,    0,    0, 2359,    3,   11],
       [   2,   12,   12,   16,    4,    4,    1,    8, 2240,    8],
       [   5,    1,    2,   13,   15,    6,    0,   36,    9, 2245]])>

In [36]:
model4 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'tanh'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model4.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model4.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 6s 3ms/step - loss: 0.2990 - accuracy: 0.9131
Epoch 2/5
1466/1466 [==============================] - 5s 3ms/step - loss: 0.1423 - accuracy: 0.9570
Epoch 3/5
1466/1466 [==============================] - 4s 2ms/step - loss: 0.0987 - accuracy: 0.9706
Epoch 4/5
1466/1466 [==============================] - 5s 4ms/step - loss: 0.0751 - accuracy: 0.9772
Epoch 5/5
1466/1466 [==============================] - 13s 9ms/step - loss: 0.0553 - accuracy: 0.9835


In [37]:
model4.evaluate(X_testf, y_test)

722/722 [==============================] - 2s 3ms/step - loss: 0.1023 - accuracy: 0.9684


[0.10231774300336838, 0.9683982729911804]

In [38]:
y_predict = model4.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 3s 4ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2265,    0,    3,    1,    3,    3,   20,    1,    8,    1],
       [   0, 2540,    5,    9,    6,    0,    5,    7,    9,    4],
       [   9,    3, 2124,   16,    7,    0,   10,   38,   25,    1],
       [   1,    2,   11, 2236,    0,   21,    2,    8,   23,    2],
       [   1,    1,    2,    1, 2223,    1,   19,    3,    5,   18],
       [  10,    2,    4,   33,    6, 1930,   35,    3,   19,   10],
       [   6,    2,    1,    1,   11,    2, 2276,    0,    4,    0],
       [   0,    5,    5,    9,    9,    1,    1, 2355,    5,   13],
       [   4,   13,    1,   16,    5,   11,   14,    8, 2230,    5],
       [   8,    3,    0,   11,   61,    8,    0,   34,   16, 2191]])>

In [39]:
model5 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'relu'),
    keras.layers.Dense(20, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model5.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model5.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 22s 15ms/step - loss: 0.3712 - accuracy: 0.8894
Epoch 2/5
1466/1466 [==============================] - 8s 5ms/step - loss: 0.1616 - accuracy: 0.9525
Epoch 3/5
1466/1466 [==============================] - 4s 3ms/step - loss: 0.1220 - accuracy: 0.9641
Epoch 4/5
1466/1466 [==============================] - 4s 3ms/step - loss: 0.0998 - accuracy: 0.9701
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0842 - accuracy: 0.9742


In [40]:
model5.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1164 - accuracy: 0.9658


[0.11644002795219421, 0.9657575488090515]

In [41]:
y_predict = model5.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2258,    1,    8,    1,    0,    1,   13,    3,   20,    0],
       [   0, 2551,    9,    7,    5,    1,    2,    5,    5,    0],
       [   7,   16, 2170,   15,    8,    1,    3,    6,    5,    2],
       [   2,    8,   21, 2245,    0,    7,    0,    5,   14,    4],
       [   3,    1,    6,    1, 2216,    0,   15,    3,    4,   25],
       [   8,    7,    2,   56,   11, 1908,   25,    2,   21,   12],
       [  12,    5,    4,    2,    8,    6, 2262,    0,    4,    0],
       [   2,   18,   29,    8,   13,    0,    1, 2312,    1,   19],
       [   4,   29,   18,   25,    5,    2,   12,    4, 2200,    8],
       [  11,    1,    3,   26,   72,    7,    1,   13,   11, 2187]])>

In [42]:
model6 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'tanh'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'tanh'),
    keras.layers.Dense(20, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model6.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model6.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.3930 - accuracy: 0.8962
Epoch 2/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1639 - accuracy: 0.9522
Epoch 3/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1185 - accuracy: 0.9647
Epoch 4/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.0943 - accuracy: 0.9720
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0762 - accuracy: 0.9769


In [43]:
model6.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 2ms/step - loss: 0.1096 - accuracy: 0.9679


[0.10963241755962372, 0.9679220914840698]

In [44]:
y_predict = model6.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 2s 2ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2279,    0,    3,    0,    3,    1,    7,    1,    9,    2],
       [   0, 2544,    6,    8,    5,    0,    4,    6,    9,    3],
       [   7,    5, 2154,    7,   12,    6,    6,   21,   15,    0],
       [   7,    2,   26, 2208,    0,   30,    3,   11,   10,    9],
       [   4,    3,    3,    0, 2167,    1,   12,    5,    5,   74],
       [   8,    0,    0,   14,    4, 1985,   22,    0,    8,   11],
       [  16,    2,    3,    1,   11,    7, 2259,    0,    3,    1],
       [   2,   14,   17,    4,    9,    0,    1, 2332,    4,   20],
       [   8,   15,    8,   18,    6,   25,   18,    2, 2196,   11],
       [  11,    2,    1,    6,   25,   12,    1,   25,   14, 2235]])>

In [45]:
model7 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'relu'),
    keras.layers.Dense(20, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model7.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model7.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 4s 2ms/step - loss: 0.4965 - accuracy: 0.8710
Epoch 2/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.2067 - accuracy: 0.9392
Epoch 3/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1512 - accuracy: 0.9557
Epoch 4/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1184 - accuracy: 0.9648
Epoch 5/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.0987 - accuracy: 0.9702


In [46]:
model7.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1211 - accuracy: 0.9646


[0.12111889570951462, 0.9645887613296509]

In [47]:
y_predict = model1.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2241,    1,    6,    1,    7,    5,   20,    3,   16,    5],
       [   0, 2540,    6,    6,    4,    0,    4,    7,   13,    5],
       [   3,    4, 2162,   15,   11,    1,    5,   13,   15,    4],
       [   0,    4,   23, 2218,    0,   17,    3,   13,   25,    3],
       [   1,    5,    5,    2, 2160,    1,   16,    6,   10,   68],
       [  12,    5,    5,   49,    9, 1893,   22,    4,   39,   14],
       [   9,    8,    7,    0,    8,    5, 2259,    0,    7,    0],
       [   0,   12,   13,    4,   16,    0,    1, 2335,    2,   20],
       [   3,   23,    3,   20,    3,    6,    9,    7, 2223,   10],
       [   5,    3,    1,   14,   27,    5,    1,   18,   11, 2247]])>

In [48]:
model8 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model8.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model8.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.4384 - accuracy: 0.8794
Epoch 2/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1965 - accuracy: 0.9413
Epoch 3/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1458 - accuracy: 0.9559
Epoch 4/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1117 - accuracy: 0.9669
Epoch 5/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.0892 - accuracy: 0.9726


In [49]:
model8.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1062 - accuracy: 0.9673


[0.10624600201845169, 0.9673160314559937]

In [50]:
y_predict = model8.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2261,    1,    5,    2,    2,    6,   12,    2,   10,    4],
       [   0, 2537,    7,    7,    7,    1,    7,    3,   12,    4],
       [   2,    4, 2176,   15,    9,    1,   10,    6,   10,    0],
       [   1,    2,   23, 2199,    0,   34,    3,   13,   28,    3],
       [   1,    2,    9,    0, 2205,    3,   15,    8,    1,   30],
       [   8,    4,    1,   19,    3, 1969,   20,    4,   15,    9],
       [  10,    7,    1,    1,    5,    9, 2265,    1,    4,    0],
       [   2,   12,   28,    0,   11,    1,    1, 2336,    3,    9],
       [  10,   26,    9,    8,    6,    8,    8,    4, 2221,    7],
       [  15,    2,    6,   13,   53,   13,    0,   42,   12, 2176]])>

In [51]:
model9 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model9.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model9.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 4s 2ms/step - loss: 0.4014 - accuracy: 0.8889
Epoch 2/5
1466/1466 [==============================] - 4s 3ms/step - loss: 0.1891 - accuracy: 0.9428
Epoch 3/5
1466/1466 [==============================] - 4s 2ms/step - loss: 0.1379 - accuracy: 0.9585
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1053 - accuracy: 0.9684
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0838 - accuracy: 0.9750


In [52]:
model9.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 2ms/step - loss: 0.1037 - accuracy: 0.9678


[0.10365161299705505, 0.9677922129631042]

In [53]:
y_predict = model9.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2263,    1,    3,    1,    3,    3,   14,    1,   15,    1],
       [   0, 2521,    8,   17,    5,    1,    7,    6,   13,    7],
       [   8,    2, 2158,    9,    8,    4,   10,   10,   24,    0],
       [   5,    2,   13, 2216,    0,   25,    2,    9,   32,    2],
       [   0,    2,    5,    0, 2183,    1,   13,    6,    9,   55],
       [  10,    1,    3,   21,    4, 1965,   21,    0,   19,    8],
       [  11,    8,    1,    0,    9,    7, 2260,    0,    7,    0],
       [   3,    9,   14,    4,   10,    2,    1, 2329,    7,   24],
       [   2,   14,    7,   17,    3,    6,    9,    4, 2239,    6],
       [   8,    1,    2,   15,   39,    9,    1,   17,   18, 2222]])>

In [54]:
model10 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model10.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model10.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.2731 - accuracy: 0.9212
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1190 - accuracy: 0.9635
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0836 - accuracy: 0.9743
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0612 - accuracy: 0.9804
Epoch 5/5
1466/1466 [==============================] - 4s 3ms/step - loss: 0.0485 - accuracy: 0.9844


In [55]:
model10.evaluate(X_testf, y_test)

722/722 [==============================] - 2s 2ms/step - loss: 0.0998 - accuracy: 0.9711


[0.09978106617927551, 0.9711255431175232]

In [56]:
y_predict = model10.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 2s 2ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2273,    0,    8,    1,    4,    2,    6,    2,    7,    2],
       [   0, 2552,   10,    4,    7,    0,    3,    6,    2,    1],
       [   5,    2, 2200,    3,    3,    0,    1,   12,    6,    1],
       [   4,    0,   35, 2237,    0,   14,    0,    7,    7,    2],
       [   2,    2,    5,    0, 2235,    1,    5,    5,    1,   18],
       [   8,    0,    6,   20,    3, 1975,   13,    6,   10,   11],
       [  19,   11,   10,    0,   12,    6, 2242,    1,    2,    0],
       [   2,    8,   25,    1,   12,    0,    0, 2347,    1,    7],
       [   5,   28,   29,   31,    5,   11,   14,    7, 2168,    9],
       [  12,    2,    0,   17,   61,    7,    0,   27,    2, 2204]])>

In [57]:
model11 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'sigmoid'),
    keras.layers.Dense(40, activation = 'sigmoid'),
    keras.layers.Dense(10, activation = 'softmax')
])

model11.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model11.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 5s 3ms/step - loss: 0.8316 - accuracy: 0.7829
Epoch 2/5
1466/1466 [==============================] - 5s 3ms/step - loss: 0.2618 - accuracy: 0.9289
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1783 - accuracy: 0.9503
Epoch 4/5
1466/1466 [==============================] - 4s 2ms/step - loss: 0.1358 - accuracy: 0.9612
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1102 - accuracy: 0.9686


In [58]:
model11.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 2ms/step - loss: 0.1293 - accuracy: 0.9626


[0.12925319373607635, 0.9625974297523499]

In [59]:
y_predict = model11.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2270,    1,    4,    1,    2,    3,   11,    4,    9,    0],
       [   0, 2535,    9,    8,    5,    3,    2,    7,   11,    5],
       [  16,    3, 2136,   18,    8,    7,   11,   22,    9,    3],
       [   3,    2,   22, 2195,    0,   52,    0,   14,   12,    6],
       [   5,    5,    2,    0, 2160,    2,   20,    8,    6,   66],
       [  14,    2,    5,   24,    5, 1966,    9,    1,   12,   14],
       [  21,    7,    8,    0,   10,   11, 2241,    0,    5,    0],
       [   3,    7,   17,    5,    8,    2,    1, 2333,    0,   27],
       [   7,   26,   12,   29,    6,   29,    6,    6, 2172,   14],
       [  13,    1,    1,   14,   30,   16,    1,   23,    5, 2228]])>

In [60]:
model12 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'relu'),
    keras.layers.Dense(40, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model12.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model12.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 4s 2ms/step - loss: 0.3096 - accuracy: 0.9088
Epoch 2/5
1466/1466 [==============================] - 4s 2ms/step - loss: 0.1349 - accuracy: 0.9587
Epoch 3/5
1466/1466 [==============================] - 4s 3ms/step - loss: 0.0993 - accuracy: 0.9696
Epoch 4/5
1466/1466 [==============================] - 7s 5ms/step - loss: 0.0802 - accuracy: 0.9739
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0645 - accuracy: 0.9790


In [61]:
model12.evaluate(X_testf, y_test)

722/722 [==============================] - 2s 2ms/step - loss: 0.1040 - accuracy: 0.9682


[0.10402534902095795, 0.9682251214981079]

In [62]:
y_predict = model12.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2283,    0,    2,    2,    1,    1,    5,    2,    6,    3],
       [   2, 2535,    9,    2,    8,    0,    5,   12,    7,    5],
       [  14,    2, 2178,    7,    4,    3,    3,   10,   10,    2],
       [   7,    2,   29, 2189,    0,   31,    1,   15,    9,   23],
       [   7,    2,    5,    0, 2187,    0,    7,   11,    1,   54],
       [  11,    1,    2,   30,    4, 1949,    9,    2,   14,   30],
       [  19,    2,    3,    0,    9,   20, 2245,    0,    5,    0],
       [   1,    3,   20,    0,    6,    0,    1, 2348,    3,   21],
       [  13,   10,   15,   12,    6,   17,    6,    7, 2182,   39],
       [  10,    0,    3,    3,   23,    3,    0,   19,    1, 2270]])>

In [63]:
model13 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'tanh'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'tanh'),
    keras.layers.Dense(40, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model13.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model13.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 4s 2ms/step - loss: 0.3144 - accuracy: 0.9112
Epoch 2/5
1466/1466 [==============================] - 5s 3ms/step - loss: 0.1460 - accuracy: 0.9566
Epoch 3/5
1466/1466 [==============================] - 4s 3ms/step - loss: 0.1067 - accuracy: 0.9678
Epoch 4/5
1466/1466 [==============================] - 4s 3ms/step - loss: 0.0826 - accuracy: 0.9750
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0669 - accuracy: 0.9789


In [64]:
model13.evaluate(X_testf, y_test)

722/722 [==============================] - 2s 2ms/step - loss: 0.1088 - accuracy: 0.9678


[0.10884936898946762, 0.9678354859352112]

In [65]:
y_predict = model13.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 2ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2219,    1,   12,    0,    1,   17,   36,    1,   16,    2],
       [   0, 2556,    3,    5,    5,    1,    5,    6,    1,    3],
       [   4,    3, 2155,   19,    5,    2,   11,    5,   28,    1],
       [   0,    6,   13, 2211,    0,   31,    3,    5,   35,    2],
       [   2,    2,    4,    2, 2214,    3,   17,    4,    6,   20],
       [   5,    1,    1,   19,    5, 2001,   12,    0,    4,    4],
       [   2,    6,    1,    0,    4,   15, 2270,    1,    4,    0],
       [   2,   12,   16,   10,    9,    3,    2, 2315,   11,   23],
       [   3,   21,    2,    8,    2,   11,   13,    1, 2242,    4],
       [   9,    5,    1,   20,   49,   29,    1,   23,   21, 2174]])>

In [66]:
model14 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'relu'),
    keras.layers.Dense(40, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model14.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model14.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.4133 - accuracy: 0.8865
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1824 - accuracy: 0.9455
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1329 - accuracy: 0.9603
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1052 - accuracy: 0.9680
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0860 - accuracy: 0.9737


In [67]:
model14.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 2ms/step - loss: 0.1081 - accuracy: 0.9675


[0.10813406109809875, 0.9675324559211731]

In [68]:
y_predict = model14.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2271,    1,    4,    0,    1,    5,   10,    2,   10,    1],
       [   0, 2533,    7,    4,    6,    1,    9,    9,   12,    4],
       [   7,    2, 2176,    7,    4,    1,    9,   19,    8,    0],
       [   2,    5,   29, 2180,    0,   50,    0,   20,   18,    2],
       [   2,    5,    6,    0, 2168,    1,   18,   10,    7,   57],
       [   8,    3,    4,   14,    4, 1975,   16,    2,   18,    8],
       [  10,    2,    4,    0,    4,    8, 2271,    0,    4,    0],
       [   3,   11,   15,    1,    8,    0,    0, 2354,    3,    8],
       [   4,   21,    9,   19,    2,   10,   14,    8, 2216,    4],
       [   8,    2,    2,   11,   20,   15,    1,   49,   18, 2206]])>

In [69]:
model15 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model15.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model15.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.4872 - accuracy: 0.8656
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.2010 - accuracy: 0.9403
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1529 - accuracy: 0.9543
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1235 - accuracy: 0.9634
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1013 - accuracy: 0.9698


In [70]:
model15.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1225 - accuracy: 0.9629


[0.1224532201886177, 0.9629004597663879]

In [71]:
y_predict = model15.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2264,    0,    7,    1,    7,    5,    9,    1,    9,    2],
       [   0, 2529,    7,   12,    8,    0,    3,   10,   11,    5],
       [   9,    2, 2161,   15,   18,    1,    5,   12,    6,    4],
       [   3,    2,   15, 2235,    1,   20,    1,   12,   10,    7],
       [   1,    1,    3,    0, 2222,    2,   12,    5,    1,   27],
       [  12,    3,    2,   60,    9, 1924,   12,    2,   10,   18],
       [  15,   10,    7,    1,   28,   12, 2230,    0,    0,    0],
       [   3,    5,   26,    4,   18,    0,    0, 2319,    2,   26],
       [   8,   19,   16,   38,   18,    8,   11,    7, 2153,   29],
       [  11,    1,    3,   16,   63,    5,    0,   22,    5, 2206]])>