In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras

In [2]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()


In [3]:
x_train2 = x_train.reshape(len(x_train), 28 * 28)
df1 = pd.DataFrame(x_train2)


In [4]:
df1

0    1    2    3    4    5    6    7    8    9    ...  774  775  776  \
0        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
2        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
3        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
4        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
59995    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59996    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59997    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59998    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59999    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   

       777  778  779  780  781  782  783  
0        0    0    0    0    0    0    0  
1        0    0    0    0    0    0    0  
2        0    0    0    0    0    0    0  
3        0    0    0    0    0    0    0  
4        0    0    0    0    0    0    0  
...    ...  ...  ...  ...  ...  ...  ...  
59995    0    0    0    0    0    0    0  
59996    0    0    0    0    0    0    0  
59997    0    0    0    0    0    0    0  
59998    0    0    0    0    0    0    0  
59999    0    0    0    0    0    0    0  

[60000 rows x 784 columns]

In [5]:
df1_target = pd.DataFrame(y_train)

In [6]:
df1_target

0
0      5
1      0
2      4
3      1
4      9
...   ..
59995  8
59996  3
59997  5
59998  6
59999  8

[60000 rows x 1 columns]

In [7]:
df1['target'] = df1_target[0]
df1.head()

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  782  \
0  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
1  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
2  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
3  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
4  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   

   783  target  
0    0       5  
1    0       0  
2    0       4  
3    0       1  
4    0       9  

[5 rows x 785 columns]

# We did the merging for X_train and y_train, now lets do it for X_test and y_test

In [8]:
x_test2 = x_test.reshape(len(x_test), 28 * 28)
df2 = pd.DataFrame(x_test2)
df2_target = pd.DataFrame(y_test)
df2['target'] = df2_target[0]
df2.head()

##MERGING HAS BEEN DONE. WE NOW HAVE DF1 and DF2

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  782  \
0  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
1  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
2  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
3  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
4  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   

   783  target  
0    0       7  
1    0       2  
2    0       1  
3    0       0  
4    0       4  

[5 rows x 785 columns]

In [9]:
##NOW GETTING THE DF IN WHICH WE WILL MERGE ALL OF THESE
df3 = pd.concat([df1, df2], ignore_index = True)
df3

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  \
0      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
1      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
2      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
3      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
4      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
...   .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
69995  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69996  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69997  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69998  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69999  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   

       782  783  target  
0        0    0       5  
1        0    0       0  
2        0    0       4  
3        0    0       1  
4        0    0       9  
...    ...  ...     ...  
69995    0    0       2  
69996    0    0       3  
69997    0    0       4  
69998    0    0       5  
69999    0    0       6  

[70000 rows x 785 columns]

In [10]:
# y = df3['target']
# y = pd.DataFrame(y)
# y.head()
df_train = df3.sample(frac=0.67,random_state=2)
df_test = df3.drop(df_train.index)
df_train

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  \
7142   0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
27818  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
43572  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
52877  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
39845  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
...   .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
52791  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69593  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
58920  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
1817   0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
40184  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   

       782  783  target  
7142     0    0       8  
27818    0    0       5  
43572    0    0       6  
52877    0    0       6  
39845    0    0       7  
...    ...  ...     ...  
52791    0    0       7  
69593    0    0       1  
58920    0    0       9  
1817     0    0       5  
40184    0    0       3  

[46900 rows x 785 columns]

In [11]:
y_train = df_train['target']
y_train = pd.DataFrame(y_train)
y_train.head()
# df_train = df_train.drop('target', axis = 1, inplace = True)
# df_train.head()

target
7142        8
27818       5
43572       6
52877       6
39845       7

In [12]:
df_train = df_train.drop('target', axis=1)


In [13]:
df_train.head()
df_test

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  \
3      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
5      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
7      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
9      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
12     0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
...   .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
69984  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69988  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69989  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69991  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
69998  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   

       782  783  target  
3        0    0       1  
5        0    0       2  
7        0    0       3  
9        0    0       4  
12       0    0       3  
...    ...  ...     ...  
69984    0    0       1  
69988    0    0       5  
69989    0    0       6  
69991    0    0       8  
69998    0    0       5  

[23100 rows x 785 columns]

In [14]:
y_test = df_test['target']
y_test = pd.DataFrame(y_test)
y_test.head()

target
3        1
5        2
7        3
9        4
12       3

In [15]:
df_test = df_test.drop('target', axis=1)


In [16]:
df_test.head()

0    1    2    3    4    5    6    7    8    9    ...  774  775  776  777  \
3     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
5     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
7     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
9     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
12    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   

    778  779  780  781  782  783  
3     0    0    0    0    0    0  
5     0    0    0    0    0    0  
7     0    0    0    0    0    0  
9     0    0    0    0    0    0  
12    0    0    0    0    0    0  

[5 rows x 784 columns]

# Converting these into NumPy arrays for use in the ANN model

In [17]:
x_train = df_train.to_numpy()
x_train
x_test = df_test.to_numpy()
y_train = y_train.to_numpy()
y_test = y_test.to_numpy()

# Performing the required pre-processing

In [18]:
x_train = x_train/255
x_test = x_test/255

In [19]:
#x_train[0]

In [20]:
X_trainf = x_train.reshape(len(x_train), 28 * 28)
#we choose to flatten the data in order to make the first input layer of the neural network have 784 values, since we currently have values stored in 28*28 form

In [21]:
X_testf = x_test.reshape(len(x_test), 28*28)

# MODEL 1 -- 150 neurons, 2 layers, sigmoid

In [22]:
model1 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'sigmoid'),
    keras.layers.Dense(10, activation = 'softmax')
])

model1.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model1.fit(X_trainf, y_train, epochs = 5)



Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.5835 - accuracy: 0.8601
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.2091 - accuracy: 0.9394
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1504 - accuracy: 0.9557
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1160 - accuracy: 0.9661
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0925 - accuracy: 0.9731


In [23]:
model1.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 965us/step - loss: 0.1175 - accuracy: 0.9639


[0.11748803406953812, 0.9638528227806091]

In [24]:
y_predict = model1.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 865us/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2253,    0,    1,    5,    1,   11,   17,    3,   10,    4],
       [   1, 2543,   12,   14,    3,    0,    4,    6,   14,    3],
       [   9,    7, 2216,   32,   14,    0,    6,   12,   19,    4],
       [   5,    3,   20, 2214,    2,   20,    3,    9,   27,    8],
       [   2,    5,    4,    3, 2169,    0,   19,    4,    7,   50],
       [   7,    4,    5,   31,    6, 1957,   22,    2,   21,   13],
       [  12,    6,    4,    0,    4,    8, 2210,    0,    8,    0],
       [   3,    7,   26,    3,   10,    7,    2, 2337,    3,   23],
       [  11,   15,    6,   18,    4,    9,   11,    1, 2185,   16],
       [   9,    4,    2,   21,   24,    9,    1,   22,   12, 2181]])>

# MODEL 2 -- 100 Neurons, 3 Hidden Layers

In [25]:
model2 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'sigmoid'),
    keras.layers.Dense(20, activation = 'sigmoid'),
    keras.layers.Dense(10, activation = 'softmax')
])

model2.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model2.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 1.1177 - accuracy: 0.7126
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.3763 - accuracy: 0.9103
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.2469 - accuracy: 0.9368
Epoch 4/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1911 - accuracy: 0.9496
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1564 - accuracy: 0.9587


In [26]:
model2.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1841 - accuracy: 0.9497


[0.18406683206558228, 0.949696958065033]

In [27]:
y_predict = model2.predict(X_testf)

722/722 [==============================] - 1s 940us/step


In [28]:
y_predict[0]

array([6.1354680e-05, 9.9281436e-01, 2.3227914e-03, 1.2395429e-04,
       1.0546061e-04, 7.0239651e-07, 1.6301287e-04, 2.1458147e-03,
       2.0899461e-03, 1.7254542e-04], dtype=float32)

In [29]:
np.argmax(y_predict[0]) #gives the maximum value out of the given ones

1

In [30]:
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array

In [31]:
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices


In [32]:
cm #this is the confusion matrix, we are supposed to do this for all 15 of the models. Preferable if we beautify this a bit using matPlotLib, or seaborn if permitted by sir

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2235,    0,    2,   10,    3,   16,   13,    7,   16,    3],
       [   0, 2520,   17,   11,    0,    1,    5,   10,   29,    7],
       [  11,   14, 2179,   27,    6,   10,   13,   17,   39,    3],
       [  11,    0,   31, 2139,    1,   55,    1,   15,   49,    9],
       [   0,    3,    5,    1, 2125,    2,   25,    2,   13,   87],
       [  14,    0,    7,   15,   11, 1962,   19,    1,   25,   14],
       [  17,    5,   15,    1,   20,   24, 2159,    0,   10,    1],
       [   7,   10,   13,   10,    9,    7,    1, 2323,    6,   35],
       [   8,   10,    8,   21,   14,   19,   10,    7, 2149,   30],
       [   8,    3,    0,    6,   32,   12,    4,   59,   14, 2147]])>

# MODEL 3 -- 150 Neurons, 2 Hidden Layers, ReLU

In [33]:
model3 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model3.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model3.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.2934 - accuracy: 0.9155
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1273 - accuracy: 0.9617
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0929 - accuracy: 0.9714
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0712 - accuracy: 0.9775
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0576 - accuracy: 0.9820


In [34]:
model3.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1004 - accuracy: 0.9709


[0.10044079273939133, 0.9709091186523438]

In [35]:
y_predict = model3.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 930us/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2252,    0,    5,    1,    5,    9,   20,    0,    8,    5],
       [   1, 2556,    8,   14,    0,    0,    2,    3,    9,    7],
       [   3,    6, 2256,   16,    7,    1,    3,    8,   10,    9],
       [   1,    3,   21, 2213,    1,   41,    3,    3,   17,    8],
       [   0,    3,    4,    2, 2197,    1,    8,    3,    6,   39],
       [  11,    2,    2,    5,    3, 2000,   21,    2,   14,    8],
       [   4,    5,    2,    0,    2,    7, 2231,    0,    1,    0],
       [   2,    3,   19,   10,    6,    4,    0, 2354,    5,   18],
       [   7,   12,   12,   23,    5,   12,   12,    1, 2179,   13],
       [  10,    2,    0,   13,   27,    8,    2,   22,   11, 2190]])>

In [36]:
model4 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'tanh'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model4.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model4.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.3044 - accuracy: 0.9107
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1406 - accuracy: 0.9574
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0959 - accuracy: 0.9709
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0719 - accuracy: 0.9781
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0550 - accuracy: 0.9830


In [37]:
model4.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1032 - accuracy: 0.9693


[0.10323482006788254, 0.9693073630332947]

In [38]:
y_predict = model4.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 931us/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2257,    0,    1,    2,    6,   11,   14,    3,    9,    2],
       [   1, 2574,    4,    5,    2,    1,    3,    2,    7,    1],
       [   6,   15, 2198,   23,   21,    3,    2,   20,   29,    2],
       [   3,    8,   12, 2209,    2,   34,    1,    8,   22,   12],
       [   0,    4,    0,    0, 2202,    1,    7,    3,    4,   42],
       [   7,    3,    3,   14,    9, 1987,   14,    5,   17,    9],
       [  13,    6,    6,    1,    4,    6, 2207,    1,    8,    0],
       [   1,    8,   12,    3,    5,    2,    1, 2378,    3,    8],
       [  11,   13,    0,    8,    9,   10,    5,    4, 2198,   18],
       [   8,    7,    1,   10,   31,    7,    1,   31,    8, 2181]])>

In [39]:
model5 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'relu'),
    keras.layers.Dense(20, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model5.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model5.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.3574 - accuracy: 0.8925
Epoch 2/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1562 - accuracy: 0.9534
Epoch 3/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.1176 - accuracy: 0.9637
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0953 - accuracy: 0.9709
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0791 - accuracy: 0.9753


In [40]:
model5.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1284 - accuracy: 0.9632


[0.1284457892179489, 0.963203489780426]

In [41]:
y_predict = model5.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 989us/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2256,    0,    7,   11,    4,    3,   10,    2,    9,    3],
       [   0, 2558,   17,    6,    0,    0,    1,   10,    7,    1],
       [   3,    5, 2246,   15,    7,    3,    1,   29,    8,    2],
       [   3,    2,   28, 2230,    2,    7,    0,   13,   21,    5],
       [   1,   10,   10,    0, 2175,    0,   12,   11,   10,   34],
       [  14,    2,    6,   52,    5, 1910,   19,    5,   40,   15],
       [  12,    9,   10,    0,    7,    4, 2201,    0,    9,    0],
       [   1,    3,   16,    6,   13,    4,    1, 2354,    4,   19],
       [   8,   21,   18,   19,    2,    4,    7,    5, 2186,    6],
       [  12,    4,    4,   33,   32,    7,    1,   36,   22, 2134]])>

In [42]:
model6 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'tanh'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'tanh'),
    keras.layers.Dense(20, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model6.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model6.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.4037 - accuracy: 0.8948
Epoch 2/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1652 - accuracy: 0.9519
Epoch 3/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1211 - accuracy: 0.9642
Epoch 4/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0934 - accuracy: 0.9722
Epoch 5/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.0747 - accuracy: 0.9777


In [43]:
model6.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1268 - accuracy: 0.9630


[0.12677767872810364, 0.9630302786827087]

In [44]:
y_predict = model6.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2263,    0,    3,    2,    4,    5,   14,    3,    6,    5],
       [   1, 2565,   14,    6,    4,    1,    3,    2,    4,    0],
       [   6,    9, 2260,   10,    9,    1,    4,    8,   10,    2],
       [   4,    4,   45, 2171,    4,   25,    3,   12,   36,    7],
       [   4,    5,    8,    0, 2204,    0,   11,    6,    8,   17],
       [  10,    3,    9,   13,   10, 1946,   31,    5,   26,   15],
       [   9,    9,   15,    1,    8,    7, 2198,    0,    5,    0],
       [   5,   14,   28,    1,   16,    3,    2, 2334,    2,   16],
       [  17,   22,   26,    9,    4,    8,   14,    5, 2160,   11],
       [  10,    9,    7,   11,   49,    5,    1,   34,   14, 2145]])>

In [45]:
model7 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(30, activation = 'relu'),
    keras.layers.Dense(20, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model7.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model7.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 2s 1ms/step - loss: 0.4992 - accuracy: 0.8672
Epoch 2/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.2028 - accuracy: 0.9416
Epoch 3/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1478 - accuracy: 0.9568
Epoch 4/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1179 - accuracy: 0.9654
Epoch 5/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.0973 - accuracy: 0.9710


In [46]:
model7.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1385 - accuracy: 0.9581


[0.13852088153362274, 0.9580519199371338]

In [47]:
y_predict = model1.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2253,    0,    1,    5,    1,   11,   17,    3,   10,    4],
       [   1, 2543,   12,   14,    3,    0,    4,    6,   14,    3],
       [   9,    7, 2216,   32,   14,    0,    6,   12,   19,    4],
       [   5,    3,   20, 2214,    2,   20,    3,    9,   27,    8],
       [   2,    5,    4,    3, 2169,    0,   19,    4,    7,   50],
       [   7,    4,    5,   31,    6, 1957,   22,    2,   21,   13],
       [  12,    6,    4,    0,    4,    8, 2210,    0,    8,    0],
       [   3,    7,   26,    3,   10,    7,    2, 2337,    3,   23],
       [  11,   15,    6,   18,    4,    9,   11,    1, 2185,   16],
       [   9,    4,    2,   21,   24,    9,    1,   22,   12, 2181]])>

In [48]:
model8 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model8.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model8.fit(X_trainf, y_train, epochs = 5)


Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.4100 - accuracy: 0.8881
Epoch 2/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1842 - accuracy: 0.9452
Epoch 3/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1350 - accuracy: 0.9596
Epoch 4/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1036 - accuracy: 0.9683
Epoch 5/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.0832 - accuracy: 0.9736


In [49]:
model8.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1166 - accuracy: 0.9661


[0.11659473180770874, 0.9660605788230896]

In [50]:
y_predict = model8.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2273,    0,    0,    3,    1,    4,    9,    2,    5,    8],
       [   1, 2545,   12,   11,    3,    0,    2,    6,   15,    5],
       [   7,   10, 2228,   16,   18,    0,    4,   19,   11,    6],
       [   7,    1,   11, 2221,    4,   19,    2,    7,   17,   22],
       [   3,    1,    4,    0, 2202,    0,    8,    1,    1,   43],
       [  13,    5,    5,   13,   14, 1945,   13,    3,   23,   34],
       [  14,    6,    2,    1,    7,    6, 2210,    0,    6,    0],
       [  11,   10,   16,    8,   23,    3,    1, 2312,    2,   35],
       [  15,   13,    5,   12,   10,    5,    8,    0, 2167,   41],
       [  12,    2,    2,   10,   25,    4,    1,   13,    3, 2213]])>

In [51]:
model9 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model9.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model9.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.3850 - accuracy: 0.8948
Epoch 2/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1748 - accuracy: 0.9482
Epoch 3/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1229 - accuracy: 0.9630
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0921 - accuracy: 0.9721
Epoch 5/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.0722 - accuracy: 0.9781


In [52]:
model9.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1036 - accuracy: 0.9686


[0.10360664129257202, 0.9686146974563599]

In [53]:
y_predict = model9.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2250,    0,    2,    2,    2,   14,   13,    1,   15,    6],
       [   1, 2555,    9,   15,    4,    0,    3,    5,    7,    1],
       [   8,   12, 2236,   22,    6,    5,    4,   13,   10,    3],
       [   5,    2,   12, 2236,    0,   19,    0,    8,   24,    5],
       [   3,    2,    4,    1, 2188,    0,   17,    5,   10,   33],
       [   7,    1,    4,   25,    4, 1993,   12,    0,   14,    8],
       [  12,    6,    4,    2,    2,   11, 2204,    1,   10,    0],
       [   1,    8,   19,   18,   14,   10,    1, 2333,    3,   14],
       [   9,   15,    4,   19,    4,   13,    9,    2, 2192,    9],
       [   9,    4,    0,   16,   29,   12,    1,   16,   10, 2188]])>

In [54]:
model10 = keras.Sequential([
    keras.layers.Dense(75, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(75, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model10.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model10.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.2666 - accuracy: 0.9212
Epoch 2/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.1125 - accuracy: 0.9654
Epoch 3/5
1466/1466 [==============================] - 2s 2ms/step - loss: 0.0760 - accuracy: 0.9761
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0572 - accuracy: 0.9822
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0430 - accuracy: 0.9863


In [55]:
model10.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1122 - accuracy: 0.9662


[0.11217816919088364, 0.9662337899208069]

In [56]:
y_predict = model10.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2279,    0,    0,    2,    0,    7,    5,    1,    7,    4],
       [   1, 2566,    6,    2,    5,    0,    3,    4,   10,    3],
       [  40,   16, 2172,   24,   18,    1,    3,    6,   32,    7],
       [   7,    3,   11, 2206,    2,   52,    1,    1,   23,    5],
       [   3,    2,    1,    0, 2209,    1,    7,    3,    2,   35],
       [  11,    2,    2,    8,    1, 2005,   18,    0,   14,    7],
       [  14,    5,    1,    0,    4,   15, 2205,    0,    7,    1],
       [  15,    6,   18,   13,   16,    9,    1, 2290,    2,   51],
       [  17,   14,    1,   14,    5,   18,    6,    1, 2180,   20],
       [  12,    3,    0,   12,   20,   19,    1,    6,    4, 2208]])>

In [57]:
model11 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'sigmoid'),
    keras.layers.Dense(40, activation = 'sigmoid'),
    keras.layers.Dense(10, activation = 'softmax')
])

model11.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model11.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.8720 - accuracy: 0.7755
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.2563 - accuracy: 0.9307
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1749 - accuracy: 0.9513
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1352 - accuracy: 0.9611
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1087 - accuracy: 0.9686


In [58]:
model11.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 1ms/step - loss: 0.1497 - accuracy: 0.9568


[0.14969955384731293, 0.9567965269088745]

In [59]:
y_predict = model11.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2254,    0,    2,    2,    4,    8,    8,    4,   19,    4],
       [   1, 2516,   14,   15,    2,    5,    2,   10,   33,    2],
       [   9,    7, 2198,   22,   18,    3,    5,   11,   44,    2],
       [   4,    2,   23, 2187,    2,   21,    0,    5,   51,   16],
       [   3,    3,    7,    0, 2156,    0,    8,    4,    9,   73],
       [  15,    3,    8,   33,   13, 1928,    9,    1,   44,   14],
       [  25,    5,   10,    0,   19,   17, 2159,    1,   16,    0],
       [   6,    7,   25,    6,   13,    5,    1, 2318,   13,   27],
       [  10,   11,    6,    4,   10,   11,    0,    1, 2208,   15],
       [  10,    4,    0,   15,   31,    9,    1,   19,   18, 2178]])>

In [60]:
model12 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'relu'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'relu'),
    keras.layers.Dense(40, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model12.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model12.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.3124 - accuracy: 0.9079
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1361 - accuracy: 0.9588
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0976 - accuracy: 0.9695
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0802 - accuracy: 0.9760
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0666 - accuracy: 0.9794


In [61]:
model12.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 2ms/step - loss: 0.1294 - accuracy: 0.9631


[0.12944239377975464, 0.9631168842315674]

In [62]:
y_predict = model12.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2281,    0,    1,    1,    0,    3,   13,    1,    4,    1],
       [   1, 2553,    7,    3,    5,    1,   13,    5,   12,    0],
       [  18,    9, 2218,   13,    7,    0,   13,   21,   18,    2],
       [  15,    2,   17, 2196,    3,   22,    7,    4,   39,    6],
       [   4,    0,    8,    0, 2191,    2,   38,    4,    6,   10],
       [  12,    1,    3,   27,    4, 1970,   32,    1,   10,    8],
       [  20,    2,    1,    0,    1,    3, 2223,    0,    2,    0],
       [  12,    8,   18,    2,   11,    3,    4, 2345,    7,   11],
       [  32,   10,    4,    4,    4,   18,   26,    5, 2168,    5],
       [  22,    5,    0,   19,   62,    9,    4,   37,   24, 2103]])>

In [63]:
model13 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'tanh'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'tanh'),
    keras.layers.Dense(40, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model13.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model13.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.3121 - accuracy: 0.9119
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1365 - accuracy: 0.9596
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1003 - accuracy: 0.9699
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0770 - accuracy: 0.9761
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0617 - accuracy: 0.9801


In [64]:
model13.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 2ms/step - loss: 0.1235 - accuracy: 0.9642


[0.12354868650436401, 0.9642423987388611]

In [65]:
y_predict = model13.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2273,    0,    5,    3,    5,    3,    7,    1,    8,    0],
       [   1, 2557,    9,   12,    0,    0,    4,    5,   12,    0],
       [   6,    3, 2265,    9,   10,    2,    3,    7,   14,    0],
       [   6,    3,   39, 2201,    3,   19,    1,    9,   26,    4],
       [   4,   11,   10,    2, 2203,    0,   15,    2,    7,    9],
       [   9,    2,    5,   25,    8, 1952,   19,    2,   39,    7],
       [  19,    2,   11,    0,    8,    5, 2194,    0,   13,    0],
       [   6,    8,   38,    4,   17,    1,    1, 2335,    5,    6],
       [  14,   10,    8,   11,    9,    7,    6,    0, 2208,    3],
       [  13,    9,    6,   14,   74,   11,    1,   32,   39, 2086]])>

In [66]:
model14 = keras.Sequential([
    keras.layers.Dense(60, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'relu'),
    keras.layers.Dense(40, activation = 'tanh'),
    keras.layers.Dense(10, activation = 'softmax')
])

model14.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model14.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 4s 2ms/step - loss: 0.4101 - accuracy: 0.8860
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1791 - accuracy: 0.9462
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1313 - accuracy: 0.9600
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1029 - accuracy: 0.9686
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.0865 - accuracy: 0.9731


In [67]:
model14.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 2ms/step - loss: 0.1215 - accuracy: 0.9633


[0.12154223024845123, 0.9632900357246399]

In [68]:
y_predict = model14.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 2ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2266,    0,    3,    4,    3,    4,   10,    2,   11,    2],
       [   1, 2545,   13,   15,    2,    0,    1,    4,   18,    1],
       [  10,   13, 2215,   18,    9,    0,    1,   25,   25,    3],
       [   4,    5,   16, 2231,    3,   10,    1,    7,   30,    4],
       [   4,    6,    6,    3, 2192,    0,   12,    5,    8,   27],
       [  10,    5,    2,   60,    7, 1924,   11,    3,   31,   15],
       [  18,   10,    3,    4,    5,    8, 2183,    0,   21,    0],
       [   4,   11,   18,   10,   14,    2,    1, 2344,    4,   13],
       [  11,   14,    5,   13,    7,    6,    4,    3, 2209,    4],
       [  12,    6,    1,   29,   35,    8,    2,   33,   16, 2143]])>

In [69]:
model15 = keras.Sequential([
    keras.layers.Dense(50, input_shape=(784,), activation = 'sigmoid'), #we call it dense since every node in one layer is connected to every node in the next layer    
    keras.layers.Dense(50, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model15.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model15.fit(X_trainf, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.4488 - accuracy: 0.8742
Epoch 2/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1999 - accuracy: 0.9414
Epoch 3/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1497 - accuracy: 0.9552
Epoch 4/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1209 - accuracy: 0.9647
Epoch 5/5
1466/1466 [==============================] - 3s 2ms/step - loss: 0.1014 - accuracy: 0.9698


In [70]:
model15.evaluate(X_testf, y_test)

722/722 [==============================] - 1s 2ms/step - loss: 0.1345 - accuracy: 0.9593


[0.1345440000295639, 0.9593073725700378]

In [71]:
y_predict = model15.predict(X_testf)
# y_predict[0]
#np.argmax(y_predict[0]) #gives the maximum value out of the given ones
predicted_labels = [np.argmax(i) for i in y_predict] #we are getting exactly what has been predicted and putting it into a predicted labels array
cm = tf.math.confusion_matrix(labels=y_test,predictions=predicted_labels) #tensorflow has inbuilt provisions to build confusion matrices
cm

722/722 [==============================] - 1s 1ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[2253,    0,    3,    3,    4,    6,   18,    2,    7,    9],
       [   1, 2547,   17,    8,    3,    1,    2,    7,    9,    5],
       [   7,    7, 2259,    7,    9,    0,    4,    9,   14,    3],
       [   6,    4,   45, 2172,    6,   26,    1,   12,   21,   18],
       [   0,    2,    7,    0, 2184,    0,   12,    2,    4,   52],
       [  12,    4,   15,   40,   13, 1918,   28,    2,   14,   22],
       [  11,    6,    9,    0,    7,    8, 2203,    1,    7,    0],
       [   4,    8,   24,    6,   17,    4,    1, 2332,    2,   23],
       [  15,   24,   18,   26,   17,   12,    6,    5, 2120,   33],
       [   7,    5,    5,   14,   36,    6,    1,   34,    5, 2172]])>